libraries/chain/controller.cpp, libraries/testing/tester.cpp, tests/separate_prod_fin_test.py, unittests/finality_test_cluster.cpp
- Moves create and send vote off the main thread.
- Also adds test to verify `vote-threads=0` works for a finalizer without a producer.
Resolves #58
=> IF: Move create and send vote off the main thread

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, plugins/producer_plugin/producer_plugin.cpp
The active finalizer policy associated with the qc should be used when logging the qc, not the head block finalizer policy.
Resolves #103
=> Use correct finalizer_policy for logging

libraries/libfc/include/fc/network/listener.hpp, plugins/state_history_plugin/tests/session_test.cpp
There is a bit of a threading trap with `fc::listener`'s current implementation. Consider usage something along the lines of,
```c++
named_thread_pool<struct ship>   thread_pool;  //running on multiple threads
std::list<connection> connections;
fc::create_listener<Protocol>(thread_pool.get_executor(), _log, accept_timeout, address, "", [this](Protocol::socket&& socket) {
connections.emplace_back(new connection(std::move(socket)));
});
```
While the callback will never be called across multiple threads at once (ensuring `connections` will never be touched by multiple threads simultaneously _here at this location_), presumably somewhere else in the code needs to remove items from `connections` which, without any form of additional synchronization, would be a problem.
What one might be …
=> template `fc::listener`'s Executor

tests/PerformanceHarness/NodeosPluginArgs/generate_nodeos_plugin_args_class_files.py
As of Python 3.12 unrecognized escape sequences produce a `SyntaxWarning`
=> fix Python `SyntaxWarning`s during build due to unrecognized escape sequences

libraries/state_history/include/eosio/state_history/log.hpp
Without a buffer size passed to these components in the de/compression pipeline, boost iostreams seems to send data through byte-by-byte. Adding a buffer improves performance nearly double for populating initial state. In leap 5.0: ~12m30s, after #33: ~6m20s, this PR: ~3m15s.
Certainly open to being schooled on how to better utilize boost iostreams if I missed a better way; this very pessimistic default buffering behavior was surprising.
=> use a buffer for state_history's boost iostreams de/compression pipeline improving performance

libraries/chain/controller.cpp, libraries/testing/include/eosio/testing/tester.hpp, libraries/testing/tester.cpp, unittests/finality_test_cluster.hpp, unittests/finality_tests.cpp, unittests/finalizer_update_tests.cpp, unittests/forked_tests.cpp
This is needed for IBC proof tests.
=> libtester: return transaction trace for `setfinalizer` host function. 

libraries/chain/block_header_state.cpp, libraries/chain/block_state.cpp, libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/block_header_state.hpp, libraries/chain/include/eosio/chain/finality/finalizer_policy.hpp, libraries/chain/include/eosio/chain/finality/instant_finality_extension.hpp, libraries/chain/include/eosio/chain/finality/proposer_policy.hpp, libraries/testing/include/eosio/testing/tester.hpp, unittests/block_header_tests.cpp, unittests/producer_schedule_if_tests.cpp, unittests/svnn_ibc_tests.cpp
Instead of placing the entire producer (proposer) schedule in the `instant_finality_extension`, only put a diff of the proposer schedule in the extension.
Along with #118 Resolves #5
=> IF: Use proposer diffs in instant_finality_extension

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/config.hpp, libraries/chain/include/eosio/chain/finality/proposer_policy.hpp, libraries/chain/webassembly/privileged.cpp
Increase the maximum number of proposer (producers) in Savanna from 125 to 64K. This matches the maximum number of allowed finalizers.
=> Increase max proposers to match max finalizers

libraries/libfc/test/test_ordered_diff.cpp
Fix
```
libraries/libfc/test/test_ordered_diff.cpp:195:7:   required from here
libraries/boost/libs/test/include/boost/test/tools/assertion.hpp:72:13: warning: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Wsign-compare] 
```
=> Fix a different signedness warning in ordered_diff_moveable_test

libraries/chain/block_state.cpp, libraries/chain/include/eosio/chain/block_header_state.hpp, libraries/chain/include/eosio/chain/block_state.hpp
Add proposed finalizer policy to SHiP finality_data stream
Resolves https://github.com/AntelopeIO/spring/issues/123
=> Add proposed finalizer policy to SHiP finality_data stream

libraries/chain/block_header_state.cpp, libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/block_header_state.hpp, libraries/chain/include/eosio/chain/block_header_state_legacy.hpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/testing/include/eosio/testing/tester.hpp, unittests/finality_tests.cpp
In that case, duplicate policies can become pending for the same block.
Resolves #130.
Also added a test which demonstrates the issue when the fix is not present.
=> Correctly support when finality advances multiple blocks at a time.

libraries/libfc/secp256k1/CMakeLists.txt
Time for another awesome libsecp256k1 update. v0.5.0 improves signing performance by about ~10% in my tests. The improvement is via `https://github.com/bitcoin-core/secp256k1/pull/1058`
=> upgrade to libsecp256k1 v0.5.0; improves k1 signing performance ~10%

plugins/net_plugin/net_plugin.cpp
When syncing do not mark a block as applied until it is actually applied to the chain state. 
Reverting this commit: https://github.com/AntelopeIO/leap/commit/fdeb7fcb0f464b48d190e678104fd6042d6e10a1 with the comment "GH-2125 If we have the block in our dispatcher list then it is applied". The comment is wrong. A block that is in the dispatcher list is not necessarily applied. We can not assume that a block is applied just because we have added it to our received block list. We distinguish from received blocks and applied blocks in `sync_manager` to know the current state of syncing. The indication that the block is already applied confused `sync_manager` so that it doesn't request the correct blocks.
Introduced in https://github.com/AntelopeIO/leap/pull/2290
Resolves #141
=> [1.0-beta1] P2P: Fix switch from lib catchup to head catchup

libraries/testing/include/eosio/testing/tester.hpp, libraries/testing/tester.cpp, unittests/auth_tests.cpp
This PR (and subsequent ones) addresses those requirements:
* for any unit test which can be run in both Legacy and Savanna (majority of our unit tests are), we would like CICD to run it in both modes,
* for any tests which can be only run in Legacy or Savanna, place in a separate file,
* we want to easily turn off and remove Legacy testing some time in the future
This is the first PR which demonstrates how running both modes can be achieved. After it is approved, it will be applied to other tests.
Both `BOOST_AUTO_TEST_CASE_TEMPLATE` and `BOOST_FIXTURE_TEST_CASE_TEMPLATE` work. Either involves about the same amount of coding. If an original test already use `tester chain;` declaration, `BOOST_AUTO_TEST_CASE_TEMPLATE` requires fewer changes; if it uses a fixture, …
=> Add support to run unit tests in both Legacy and Savanna (Part 1)

tests/nodeos_startup_catchup.py
Adds test for #146 
Use different sync-fetch-span options for syncing up.
Fails before #146: https://github.com/AntelopeIO/spring/actions/runs/9104723740
=> [1.0-beta1] Test: P2P: Add different sync-fetch-span for catchup test

plugins/net_plugin/net_plugin.cpp, tests/nodeos_startup_catchup.py
When syncing do not mark a block as applied until it is actually applied to the chain state. 
Reverting this commit: https://github.com/AntelopeIO/leap/commit/fdeb7fcb0f464b48d190e678104fd6042d6e10a1 with the comment "GH-2125 If we have the block in our dispatcher list then it is applied". The comment is wrong. A block that is in the dispatcher list is not necessarily applied. We can not assume that a block is applied just because we have added it to our received block list. We distinguish from received blocks and applied blocks in `sync_manager` to know the current state of syncing. The indication that the block is already applied confused `sync_manager` so that it doesn't request the correct blocks.
Introduced in https://github.com/AntelopeIO/leap/pull/2290
Merges `release/1.0-beta1` …
=> [1.0-beta1 -> main] P2P: Fix switch from lib catchup to head catchup

plugins/net_plugin/net_plugin.cpp
Test failure: https://github.com/AntelopeIO/spring/actions/runs/9114438126/job/25059003107?pr=149
The producing node (Node03) was stuck in LIB catchup. Since blocks can be processed inside controller during a fork and not call `sync_master->sync_recv_block` with `blk_applied==true`. 
This is similar to the issue addressed in #27. In the #27, a handshake with the wrong information was sent. In this case no handshake was sent at all as it become synced up during a fork switch. I believe this issue was masked by #147 because it was incorrectly reporting blocks as applied. Without this improper reporting of applied blocks a fork switch that applies up to synced would not call  `sync_master->sync_recv_block` with `blk_applied==true` and not move node out of LIB catchup.
Now also send out …
=> [1.0-beta1] P2P: Fix stuck in peer syncing state

plugins/net_plugin/net_plugin.cpp
Test failure: https://github.com/AntelopeIO/spring/actions/runs/9114438126/job/25059003107?pr=149
The producing node (Node03) was stuck in LIB catchup. Since blocks can be processed inside controller during a fork and not call `sync_master->sync_recv_block` with `blk_applied==true`. 
This is similar to the issue addressed in #27. In the #27, a handshake with the wrong information was sent. In this case no handshake was sent at all as it become synced up during a fork switch. I believe this issue was masked by #147 because it was incorrectly reporting blocks as applied. Without this improper reporting of applied blocks a fork switch that applies up to synced would not call  `sync_master->sync_recv_block` with `blk_applied==true` and not move node out of LIB catchup.
Now also send out …
=> [1.0-beta1 -> main] P2P: Fix stuck in peer syncing state

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/vote_processor.hpp, libraries/testing/tester.cpp, unittests/finality_test_cluster.hpp
- Do not post to vote thread pool if thread pool is not active.
- This fixes a memory leak when there are no vote threads; which is why the original PR was targeted to `1.0-beta1` instead of `main`
- A producer should notify vote processor that it has produced a block
- I believe this resolves issue #139 
- Update the tester wait on votes to be consistent
Merges `release/1.0-beta1` into `main` including #158 
Resolves #139
Resolves #143
=> [1.0-beta1 -> main] Vote processing fix

unittests/api_tests.cpp
=> Test: Modify light_validation_skip_cfa to work for both savanna and legacy

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp
- Change a `warn` level log to `info` since it does not necessarily indicate any issue.
- Add block ids to fork database log output.
- Add additional fork database log output at shutdown.
=> Improve fork database logging

unittests/snapshot_tests.cpp
Update `snapshot_tests` to run in Legacy and Savanna modes.
This is done as a separate PR since the handling is a little different than previous tests: combinations of modes (`Legacy` and `Savanna`) and snapshot suites (`variant_snapshot_suite, buffered_snapshot_suite, json_snapshot_suite`) need to be considered.
=> Make unit tests run in both Legacy and Savanna (Part 3, snapshot_tests)

unittests/block_tests.cpp, unittests/chain_tests.cpp, unittests/database_tests.cpp, unittests/restart_chain_tests.cpp
Update `block_tests`, `chain_tests`, `database_tests`, and `restart_chain_tests` to run in both Legacy and Savanna.
=> Make unit tests run in both Legacy and Savanna (Part 4,  block_tests, chain_tests, database_tests, restart_chain_tests)

unittests/dry_run_trx_tests.cpp
Update `dry_run_trx_tests` to run in both Legacy and Savanna.
This update uses a slightly different approach from previous ones as `dry_run_trx_tests` defines its own test fixture. That fixture is templated to support both Legacy and Savanna. This approach will be used for other tests which have their own fixtures.
=> Make unit tests run in both Legacy and Savanna (Part 5, dry_run_trx_tests)

libraries/chain/block_state.cpp, unittests/block_tests.cpp
- `action_mroot` can be empty if `onblock` fails
- Add test for a failing `onblock`
Resolves #168
=> Remove invalid assertion for action_mroot

unittests/misc_tests.cpp
=> Update misc_tests to run in both Legacy and Savanna

libraries/testing/include/eosio/testing/tester.hpp, libraries/testing/tester.cpp, unittests/CMakeLists.txt, unittests/wasm_tests.cpp
* Add a new constructor `savanna_tester(const fc::temp_directory&, bool)`
* Update `wasm_test`s to run in both Legacy and Savanna
=> Update wasm_tests to run both modes

libraries/chain/block_header_state.cpp, libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/block_header_state.hpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/finality/instant_finality_extension.hpp, libraries/chain/include/eosio/chain/global_property_object.hpp, libraries/chain/include/eosio/chain/transaction_context.hpp, libraries/chain/transaction_context.cpp, libraries/chain/webassembly/privileged.cpp, unittests/block_header_tests.cpp
The chainbase `global_property_object` was used to store `finalizer_policy` during block construction as a means to provide automatic rollback if the transaction/block failed. See https://github.com/AntelopeIO/spring/pull/99. However, `finalizer_policy` contains non-shared types of `std::vector` and `fc::crypto::blslib::bls_public_key`. 
This PR solves the problem of avoiding side-effects of proposed finalizer policy made in an aborted transaction in a different way than committing the speculative changes into the `global_property_object` in `chainbase`. Now we store the speculative changes in the transaction context. Then if we commit the transaction, it copies them over (assuming they are not nullopt) from the transaction context to the building block. This avoids having to add a shared …
=> [1.0-beta1.1] Store proposed producers and proposed finalizers in building block

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/global_property_object.hpp, libraries/chain/include/eosio/chain/transaction_context.hpp, libraries/chain/transaction_context.cpp, libraries/chain/webassembly/privileged.cpp
The chainbase `global_property_object` was used to store `finalizer_policy` during block construction as a means to provide automatic rollback if the transaction/block failed. See https://github.com/AntelopeIO/spring/pull/99. However, `finalizer_policy` contains non-shared types of `std::vector` and `fc::crypto::blslib::bls_public_key`. 
This PR solves the problem of avoiding side-effects of proposed finalizer policy made in an aborted transaction in a different way than committing the speculative changes into the `global_property_object` in `chainbase`. Now we store the speculative changes in the transaction context. Then if we commit the transaction, it copies them over (assuming they are not nullopt) from the transaction context to the building block. This avoids having to add a shared …
=> Store proposed producers and proposed finalizers in building block

libraries/chain/block_header_state.cpp, tests/TestHarness/Cluster.py, tests/transition_to_if.py
- Add test of `setfinalizer` after transition to Savanna
- Fix double logging of finalizer change
=> Test: Add integration test of setfinalizers after transition

unittests/CMakeLists.txt, unittests/wasm_config_tests.cpp
This one involves adapting `BOOST_DATA_TEST_CASE_F`.
=> Update wasm_config_tests to run in both Legacy and Savanna

plugins/net_plugin/net_plugin.cpp
Test failure #190. The test creates a large fork and reestablishes the network between two large forked nodes. While the producer D was syncing into the network (which a very small sync-fetch-span == 5) it got stuck in lib catchup. Since it thought it was in lib catchup it would not send its produced blocks.
- Fix for continuing to sync from a peer when we are receiving a group of blocks that we have already completely received. Go ahead and get the next range as the next range of blocks could be needed to resolve a large fork.
Resolves #190
=> [1.0-beta1.2] P2P: Fix stuck in lib catchup

unittests/partitioned_block_log_tests.cpp
Update `partitioned_block_log_tests` to run under savanna and legacy
Resolves #175
=> Update partitioned_block_log_tests to run under savanna and legacy

plugins/net_plugin/net_plugin.cpp
Test failure #190. The test creates a large fork and reestablishes the network between two large forked nodes. While the producer D was syncing into the network (which a very small sync-fetch-span == 5) it got stuck in lib catchup. Since it thought it was in lib catchup it would not send its produced blocks.
- Fix for continuing to sync from a peer when we are receiving a group of blocks that we have already completely received. Go ahead and get the next range as the next range of blocks could be needed to resolve a large fork.
Merges `release/1.0-beta1` into `main` including #199 
Resolves #190
=> [1.0-beta1.2 -> main] P2P: Fix stuck in lib catchup

libraries/chain/controller.cpp, unittests/producer_schedule_if_tests.cpp, unittests/producer_schedule_tests.cpp
Producer authority `eosio.prods` was not being updated under Savanna. 
Multisigs failed (see #169) because the producer authorities were not updated when the producer schedule changed.
Partly resolves #169
=> Update eosio.prods auth under savanna

.cicd/defaults.json
Reference contracts change for default libtester PR https://github.com/AntelopeIO/reference-contracts/pull/95 has been merged. Change reference contracts target back to `main`.
=> Change reference contracts target back to main

libraries/chain/fork_database.cpp
Without this change it's possible for forkdb to return a block that does not match the block number requested which is causing a ship test malfunction.
Consider a forkdb that is rooted at block 300, has a head that is 300, and no block log exists, something calls `get_block_id_for_num(299)`
https://github.com/AntelopeIO/spring/blob/2b1228eba2bc87c34be6269b21e7085e94d466a5/libraries/chain/controller.cpp#L5201-L5208
so,
https://github.com/AntelopeIO/spring/blob/2b1228eba2bc87c34be6269b21e7085e94d466a5/libraries/chain/controller.cpp#L1140-L1142
ultimately,
https://github.com/AntelopeIO/spring/blob/2b1228eba2bc87c34be6269b21e7085e94d466a5/libraries/chain/fork_database.cpp#L532-L534
notice above that the first parameter will be the block id for block 300. then, …
=> check root block num before returning it when `include_root_t::yes`

libraries/chain/controller.cpp
Fix `terminate-at-block` option to work for transition blocks.
Resolves #216
=> Fix terminate-at-block for transition blocks

libraries/chain/controller.cpp, tests/nodeos_read_terminate_at_block_test.py
- Do not switch fork database to savanna unless irreversible apply completes otherwise fork database is left in an inconsistent state.
- Add another test case to `tests/nodeos_read_terminate_at_block_test.py` for terminate after savanna transition in irreversible mode.
Resolves #216
=> [1.0-beta2] Fix terminate-at-block for transition block

plugins/net_plugin/net_plugin.cpp
Instead of ignoring a verify catchup while in `lib_catchup`, send handshake to peer. Should avoid the peer thinking it is still syncing from it.
Resolves #224
=> [1.0-beta2] P2P: Send handshake when in lib_catchup and verify catchup is called

plugins/net_plugin/net_plugin.cpp
Instead of ignoring a verify catchup while in `lib_catchup`, send handshake to peer. Should avoid the peer thinking it is still syncing from it.
Merges `release/1.0-beta2` into `main` including #241 
Resolves #224
=> [1.0-beta2 -> main] P2P: Send handshake when in lib_catchup and verify catchup is called

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/fork_database.hpp, unittests/fork_db_tests.cpp
Fork database `add` with `mark_valid` would not mark the `block_state` validated if the fork database already contained the `block_state`. This PR fixes that which also fixes `terminate-at-block` unable to remove error `removing the block and its descendants would remove the current head block` during a transition.
Resolves #216
=> [1.0-beta2] Fix fork_database add with mark_valid

libraries/state_history/abi.cpp
This adds the missing pieces of `finality_data` to state history's ABI. Resolves #243
=> add rest of `finality_data` to state history abi

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/fork_database.hpp, unittests/fork_db_tests.cpp
Fork database `add` with `mark_valid` would not mark the `block_state` validated if the fork database already contained the `block_state`. This PR fixes that which also fixes `terminate-at-block` unable to remove error `removing the block and its descendants would remove the current head block` during a transition.
Merges `release/1.0-beta2` into `main` including #252 
Resolves #216
=> [1.0-beta2 -> main] Fix fork_database add with mark_valid

tests/nodeos_chainbase_allocation_test.py
Update test to allow time for blocks to reach and be processed by the irreversible node before creating snapshot.
Resolves #246
=> [1.0-beta2] Test: Allow time for blocks to reach snapshot node

tests/nodeos_chainbase_allocation_test.py
Update test to allow time for blocks to reach and be processed by the irreversible node before creating snapshot.
Merges `release/1.0-beta2` into `main` including #253 
Resolves #246
=> [1.0-beta2 -> main] Test: Allow time for blocks to reach snapshot node

libraries/state_history/abi.cpp
Backport #251 to `release/1.0-beta2`
=> [1.0-beta2] add rest of finality_data to ship abi

libraries/chain/controller.cpp, libraries/chain/finality/finalizer.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/finality/finalizer.hpp, libraries/testing/tester.cpp, plugins/net_plugin/net_plugin.cpp, unittests/finalizer_tests.cpp
- Do not consider voting until within 30 seconds of head block timestamp
- Do not broadcast votes if syncing from peer
Resolves #259
=> Avoid voting until caught up with network

libraries/chain/controller.cpp, libraries/chain/finality/finalizer.cpp, libraries/chain/include/eosio/chain/finality/finalizer.hpp
If a node deletes their finalizer safety information file, they may lose critical safety information such as the block they should be locked on. But in some cases, this information can be recovered based on the evidence in the QCs attached to blocks that the node receives from peers.
When processing a QC in a block, node checks to see if any of the finalizer keys it manages are represented in the QC as a strong vote. If that block is more recent than the current lock in the finalizer safety information file for that finalizer key, then update the lock.
Resolves #135
=> Update finalizer safety info file based on received QC

unittests/api_tests.cpp
The checktime tests provide a useful indication of timeouts working correctly. However, they rely on wall clock time which can vary on ci/cd machines with many tests running concurrently. Tweak timeouts to allow more time for tests to complete.
Resolves #65
=> Test: Increase checktime test timeouts

plugins/chain_plugin/test/test_account_query_db.cpp, tests/chain_plugin_tests.cpp, tests/get_producers_tests.cpp, tests/get_table_tests.cpp, tests/test_chain_plugin.cpp, tests/test_snapshot_information.cpp, unittests/api_tests.cpp, unittests/auth_tests.cpp, unittests/block_tests.cpp, unittests/chain_tests.cpp, unittests/currency_tests.cpp, unittests/database_tests.cpp, unittests/dry_run_trx_tests.cpp, unittests/eosio.token_tests.cpp, unittests/eosio_system_tester.hpp, unittests/partitioned_block_log_tests.cpp, unittests/protocol_feature_tests.cpp, unittests/ram_tests.cpp, unittests/read_only_trx_tests.cpp, unittests/restart_chain_tests.cpp, unittests/snapshot_tests.cpp, unittests/state_history_tests.cpp, unittests/wasm_config_tests.cpp, unittests/wasm_tests.cpp, unittests/whitelist_blacklist_tests.cpp
Remove extra block production not needed that only slow down test execution.
Partially #264
=> Test: Remove production of unneeded blocks

tests/ship_log.cpp
Manually craft a leap 3.x structured state history log and then read it back with current log reading code. Resolves #225. Both eosio and leap3 formats are treated identical in the code so don't see much of a need to craft an eosio formatted log.
A reminder on the differences,
https://github.com/AntelopeIO/spring/blob/3f78e0f134a819f5977c1d0747fbdb141392a83a/libraries/state_history/include/eosio/state_history/log.hpp#L194-L203
=> add test that leap3 and eosio state history log entries can be read

plugins/net_plugin/include/eosio/net_plugin/protocol.hpp, plugins/net_plugin/net_plugin.cpp
P2P syncing was using fork database head for a limited factor on how far ahead to request blocks. With the recent change to ingest blocks quickly into the fork database (https://github.com/AntelopeIO/leap/pull/2385), this allowed the fork database to load hundred of thousands of blocks ahead of chain head.
Use chain head instead of fork database head for sync ahead calculation.
Resolves #278
=> [1.0-beta2] P2P: Prevent syncing from running ahead of chain head

plugins/net_plugin/include/eosio/net_plugin/protocol.hpp, plugins/net_plugin/net_plugin.cpp
P2P syncing was using fork database head for a limited factor on how far ahead to request blocks. With the recent change to ingest blocks quickly into the fork database (https://github.com/AntelopeIO/leap/pull/2385), this allowed the fork database to load hundred of thousands of blocks ahead of chain head.
Use chain head instead of fork database head for sync ahead calculation.
Merges `release/1.0-beta2` into `release/1.0-beta3` including #282 
Resolves #278
=> [1.0-beta2 -> 1.0-beta3] P2P: Prevent syncing from running ahead of chain head

.github/workflows/build.yaml, .github/workflows/release.yaml, CMakeLists.txt, package.cmake
Renames the Debian package from `spring` to `antelope-spring` to avoid clashing with an already named `spring` package in Debian & Ubuntu standard package repo. Resolves #213
Unfortunately, will need to change both cdt & reference-contracts after merging this to update the expected package name.
=> rename debian package to 'antelope-spring' to avoid conflict

.github/workflows/release.yaml
Since we're going to have to change downstream users of the dev package anyways due to #287, might as well make this change now too so we can resolve #50
=> change `experimental-binaries` to `antelope-spring-experimental-binaries` to avoid version overlap with leap packages

plugins/net_plugin/net_plugin.cpp
Since blocks are processed immediately into the fork database when received, there is no longer any reason to request ahead of the existing range. Under normal circumstances a node will receive blocks from its peer and process them into the fork database. While those blocks are being applied additional blocks can be requested from the network. Care is taken to make sure that the fork database does not out run the chain head by more than `sync-fetch-span`.
Resolves #281
=> [1.0-beta2] P2P: Fix multiple range requests while syncing

plugins/net_plugin/net_plugin.cpp
Since blocks are processed immediately into the fork database when received, there is no longer any reason to request ahead of the existing range. Under normal circumstances a node will receive blocks from its peer and process them into the fork database. While those blocks are being applied additional blocks can be requested from the network. Care is taken to make sure that the fork database does not out run the chain head by more than `sync-fetch-span`.
Merges `release/1.0-beta3` into `main` including #291 & #294
Resolves #281
=> [1.0-beta3 -> main] P2P: Fix multiple range requests while syncing

libraries/state_history/include/eosio/state_history/log_catalog.hpp, libraries/state_history/include/eosio/state_history/log_config.hpp, tests/ship_log.cpp
In the early days, ship would truncate its log any time the applied block number was less than the log's head block. But this could lead to substantial chunks of the log being removed in the case of a replay or resync (such as when restarting from a snapshot).[^1]
So instead, sometime in leap, the log behavior was modified such that when the applied block number decreases relative to the head of the log, the log would check if the blockid in the log matched that as the new applied block. If it matched, it'd do nothing, since that is indicative of a replay or resync. If it did not match, the log would be truncated as before, since that is indicative of a new fork being applied.
The log rewrite in spring 1.0 maintains this strategy. However, the blockid duplication check is performed in the …
=> [1.0-beta3] avoid unnecessary state history log "unrotations" that can remove retained logs on replay/resync

plugins/net_plugin/net_plugin.cpp
A node will set `peer_syncing_from_us` to `false` on a `request_message` of `none` or if it receives a handshake indicating it is synced. This PR sets `peer_syncing_from_us` to `false` if a node receive a recent block from the network as blocks are only relayed after they are validated. Therefore, if we receive a recent block from a peer we know that peer can't be syncing from us even if they have failed to send us a handshake letting us know they are up to date.
Resolves #302
=> [1.0-beta2] P2P: Set peer_syncing_from_us to false when a recent block is received

plugins/net_plugin/net_plugin.cpp
A node will set `peer_syncing_from_us` to `false` on a `request_message` of `none` or if it receives a handshake indicating it is synced. This PR sets `peer_syncing_from_us` to `false` if a node receive a recent block from the network as blocks are only relayed after they are validated. Therefore, if we receive a recent block from a peer we know that peer can't be syncing from us even if they have failed to send us a handshake letting us know they are up to date.
Merges `release/1.0-beta2` into `release/1.0-beta3` including #315
Resolves #302
=> [1.0-beta2 -> 1.0-beta3] P2P: Set peer_syncing_from_us to false when a recent block is received

libraries/state_history/include/eosio/state_history/log_catalog.hpp, plugins/state_history_plugin/state_history_plugin.cpp, tests/ship_log.cpp
Avoid state history finality log failure and node shutdown if savanna transition is forked out. Resolves #289. This is a fairly simple change that erases all finality data log files and reopens a fresh head log when savanna finality data is removed (which can only happen upon the transition being forked out).
An even simpler alternative would be to always write the `std::optional<finality_data_t>` out, which we could do instead, but that puts a little more burden on consumers.
=> [1.0-beta3] clear state history's finality log if savanna transition is forked out

libraries/chain/controller.cpp
To avoid confusion, report actual LIB (the root of the fork database) instead of the calculated LIB.
Resolves #319
=> Report forkdb root for lib instead of calculated lib

libraries/chain/block_header_state.cpp, libraries/chain/block_state.cpp, libraries/chain/include/eosio/chain/block_state.hpp, libraries/state_history/abi.cpp, unittests/CMakeLists.txt, unittests/block_state_tests.cpp
SHiP `finality_data` should only include the finalizer policy when it goes from proposed to pending. This PR renames the existing field `finality_data_t::proposed_finalizer_policy` to `finality_data_t::pending_finalizer_policy` (but keeping the same type std::optional<finalizer_policy>) to capture the semantic change, and changes the logic to include the finalizer policy only when it goes from proposed to pending
Adds a test to check pending_finalizer_policy in finality_data.
https://github.com/AntelopeIO/abieos/pull/32 is created in abieos repo for corresponding SHiP protocol changes.
Resolves https://github.com/AntelopeIO/spring/issues/320
=> Provide finalizer policy in SHiP finality_data only when it gets promoted to pending

tests/ship_streamer_test.py
Make test more reliable by waiting on next producer (`c`) to produce instead of only waiting on existing producer to produce. By waiting for producer `c`, this gives plenty of time for the non producing node to see producer `b` and shutdown.
Resolves #321
=> Test: SHiP test: make test more reliable

libraries/state_history/include/eosio/state_history/log_catalog.hpp, plugins/state_history_plugin/state_history_plugin.cpp, tests/ship_log.cpp
main merge of #301:
Avoid state history finality log failure and node shutdown if savanna transition is forked out. Resolves #289. This is a fairly simple change that erases all finality data log files and reopens a fresh head log when savanna finality data is removed (which can only happen upon the transition being forked out).
An even simpler alternative would be to always write the `std::optional<finality_data_t>` out, which we could do instead, but that puts a little more burden on consumers.
=> [1.0-beta3 -> main] clear state history's finality log if savanna transition is forked out

tests/p2p_sync_throttle_test.py
Before measuring the throttled node sync throttling make sure it has the begin block.
Resolves #326
=> Test: P2P throttle test: Wait for begin block before measuring sync

benchmark/bls.cpp, libraries/custom_appbase/tests/CMakeLists.txt, libraries/libfc/CMakeLists.txt, libraries/libfc/test/CMakeLists.txt, libraries/testing/CMakeLists.txt, plugins/http_plugin/tests/CMakeLists.txt, plugins/resource_monitor_plugin/test/CMakeLists.txt, plugins/trace_api_plugin/test/CMakeLists.txt, tests/CMakeLists.txt, tests/trx_generator/CMakeLists.txt
Boost unit test framework can be used via header-only or by linking to a static library (or dynamic library). See https://www.boost.org/doc/libs/1_85_0/libs/test/doc/html/boost_test/usage_variants.html. Mixing these up can cause linker failures and/or ODR violations. If this sounds familiar, we previously had a mix ups fixed in AntelopeIO/leap#807. It appears we've mixed these up again in leap5 with the boost submodularization.
For example, in fc,
https://github.com/AntelopeIO/spring/blob/09d979b0e250b4bdefc693aeaee471b1dbd112f5/libraries/libfc/CMakeLists.txt#L105-L106
The `Boost::unit_test_framework` target will link the Boost unit test static library. But then in `test_fc` the header-only usage variant is used,
https://github.com/AntelopeIO/spring/blob/09d979b0e250b4bdefc693aeaee471b1dbd …
=> fix `Boost::unit_test_framework` linkage -- don't mix header & static library usage variants

libraries/testing/include/eosio/testing/tester.hpp
`base_tester` used to have an empty virtual destructor: `virtual ~base_tester() {}`. Having a destructor disables the implicit move constructor.
My `savanna_cluster` has `tester` as a base class of its node. It is convenient because we can call all the `tester` methods directly.
However, in a recent change as a PR review request, I updated  the nodes from the `savanna_cluster` to be stored in a `std::vector` instead of a `std::array`. `std::vector` requires its elements to have a  default and a move constructor.
To address this issue, in the recently merged PR, I removed `virtual ~base_tester() {}`, which has the side effect of re-enabling the default move constructor, so `savanna_cluster` compiled fine. However it created compilation warnings in other tests such as:
```
In file included …
```
=> Fix compilation warning due to missing `base_tester` destructor.

tools/reproducible.Dockerfile
This small Dockerfile stage is only used during manual building of the reproducible builds -- not in CI -- and was missed during #287
=> fix instance of missed `antelope-spring` package rename in `reproducible.Dockerfile`

libraries/chain/block_state.cpp, unittests/block_state_tests.cpp
If the bitset size of strong_votes or weak_votes in q QC does not match the number of finalizers for the factive finalizer policy the QC refers to, reject the QC.
This PR also adds  tests for the validation.
Resolves https://github.com/AntelopeIO/spring/issues/334
=> Reject a QC if bitset size of its strong_votes or weak_votes is invalid

libraries/chain/block_state.cpp, libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/block_state.hpp
Move tracking of Savanna pending LIB into fork database. The fork database is in charge of tracking and persisting cached current pending Savanna LIB.
Resolves #333
=> Move savanna pending lib calculation to forkdb add()

plugins/net_plugin/net_plugin.cpp
Shutting down a node that is synching can result in many log messages like:
```
info  2024-07-11T13:06:43.744 net-2     net_plugin.cpp:1457           _close               ] ["eos.p2p.eosusa.io:9882 - 1bd8339" - 3 35.131.184.46:9882] closing
info  2024-07-11T13:06:43.744 net-2     net_plugin.cpp:1457           _close               ] ["eos.p2p.eosusa.io:9882 - 1bd8339" - 3 35.131.184.46:9882] closing
info  2024-07-11T13:06:43.744 net-2     net_plugin.cpp:1457           _close               ] ["eos.p2p.eosusa.io:9882 - 1bd8339" - 3 35.131.184.46:9882] closing
info  2024-07-11T13:06:43.744 net-2     net_plugin.cpp:1457           _close               ] ["eos.p2p.eosusa.io:9882 - 1bd8339" - 3 35.131.184.46:9882] closing
info  2024-07-11T13:06:43.744 net-2     net_plugin.cpp:1457 …
```
=> P2P: Reduce log spam of close on shutdown

.github/workflows/build.yaml
Add `build/PerformanceHarnessScenarioRunnerLogs` to log paths captured by CI/CD for performance run logs. Performance runs copy their output to `PerformanceHarnessScenarioRunnerLogs` after the run. If they fail that directory needs to be captured otherwise there are no logs. See for example: https://github.com/AntelopeIO/spring/actions/runs/9896737400/job/27340099533#step:4:2208
=> Add performance logs to captured CI/CD log tar

libraries/chain/abi_serializer.cpp, libraries/chain/block_header_state.cpp, libraries/chain/block_header_state_legacy.cpp, libraries/chain/block_state.cpp, libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/abi_serializer.hpp, libraries/chain/include/eosio/chain/block_header.hpp, libraries/chain/include/eosio/chain/block_header_state.hpp, libraries/chain/include/eosio/chain/block_state.hpp, libraries/chain/include/eosio/chain/finality/finality_extension.hpp, libraries/testing/include/eosio/testing/tester.hpp, plugins/net_plugin/net_plugin.cpp, unittests/block_header_tests.cpp, unittests/finality_proof.hpp, unittests/finality_tests.cpp, unittests/finalizer_update_tests.cpp, unittests/producer_schedule_if_tests.cpp, unittests/producer_schedule_savanna_tests.cpp, unittests/vote_processor_tests.cpp
=> Rename instant_finality_extension to finality_extension

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/testing/tester.cpp, unittests/state_history_tests.cpp
Make SHiP unit tests run in both Savanna and Legacy:
* Fix a bug in libtester `produce_blocks()` which enables voting when it should not.
* Fix `test_splitted_log` such that it works in Savanna.
* Fix `test_fork` such that it works in Savanna.
* Update the rest of SHiP unit tests to work in both Savanna and Legacy.
Resolved https://github.com/AntelopeIO/spring/issues/179
=> Fix a bug in libtester `produce_blocks` and make SHiP unit tests work in both Savanna and Legacy

libraries/chain/controller.cpp
The `block_handle_accessor::apply<>()`'s `head` in `add_to_snapshot()` goes unused, and then `get_block_state_to_snapshot()` just calls `block_handle_accessor::apply<>()` again,
https://github.com/AntelopeIO/spring/blob/feeb75a2592eda08fe1fed224255b36e67ba62a2/libraries/chain/controller.cpp#L2054-L2068
So no need for the outer `apply` here in `add_to_snapshot()` afaict
=> undo an unneeded nested `block_handle_accessor::apply()`

libraries/chain/controller.cpp
Make sure vote_processor threads have stopped before writing out the `chain_head` to avoid modifications to the `block_state` while writing. Note `fork_db` was already being written out after the vote processor threads were shutdown.
Resolves #369
=> Write chain_head after vote threads have stopped

unittests/forked_tests_savanna.cpp
Fix a couple of sign compare warnings like
```
unittests/forked_tests_savanna.cpp:232:4:   required from here
libraries/boost/libs/test/include/boost/test/tools/old/impl.hpp:107:17:  warning: comparison of integer expressions of different signedness: ‘const long unsigned int’ and      ‘const int’ [-Wsign-compare]
107 |     return left == right;
```
=> Fix sign-compare warnings in forked_tests_savanna.cpp

libraries/libfc/test/io/test_random_access_file.cpp
clang18 flags this with `warning: variable length arrays in C++ are a Clang extension`.
=> don't use a VLA to avoid clang warning

libraries/chain/authorization_manager.cpp, libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/authorization_manager.hpp, libraries/chain/include/eosio/chain/resource_limits.hpp, libraries/chain/include/eosio/chain/snapshot.hpp, libraries/chain/resource_limits.cpp, libraries/chain/snapshot.cpp, unittests/snapshot_tests.cpp
Adds progress logs during snapshot loading; can look something like
```
info  2024-07-24T03:30:21.700 nodeos    controller.cpp:1831           startup              ] Starting initialization from snapshot and no block log, this may take a significant amount of time
info  2024-07-24T03:30:26.008 nodeos    snapshot.hpp:418              progress             ] Snapshot initialization 2% complete
info  2024-07-24T03:30:31.001 nodeos    snapshot.hpp:418              progress             ] Snapshot initialization 4% complete
info  2024-07-24T03:30:36.003 nodeos    snapshot.hpp:418              progress             ] Snapshot initialization 17% complete
info  2024-07-24T03:30:41.008 nodeos    snapshot.hpp:418              progress             ] Snapshot initialization 28% complete
...
info …
```
=> add progress logs during snapshot loading

tools/reproducible.Dockerfile
Update the pinned build to clang 18.1.8. Normally I wouldn't have advocated for moving from 17->18 but I stumbled on a c++20 feature that while it's in libstdc++10, is still missing from libc++17 but just added to libc++18: `jthread`. There seems to be an appetite to take on environment upgrades (e.g. #336) so nice to fill out c++20 support more before 1.0 release.
I measured something around a 0.5% speed improvement for a replay over blocks 381452700 through 381632370 (sadly I didn't think to include #344 as part of that; though at least we know #344 wouldn't have been resolved just by updating to clang18).
The upgrade may also unlock another useful feature: `_LIBCPP_HARDENING_MODE` was added in 18 and is similar to `_GLIBCXX_ASSERTIONS` in enabling stdlib hardening checks intended to be …
=> update pinned build to clang 18.1.8

plugins/producer_plugin/producer_plugin.cpp
```
info  2024-07-25T13:50:19.133 nodeos    producer_plugin.cpp:649       log_missing_votes    ] Block d7ad1e79d8f20c06... #145 @ 2024-07-25T13:49:43.500 produced by defproducerb, latency: 35633ms has no votes from finalizers: finalizer #4
```
Resolves #226
=> Add producer, timestamp, and latency to missing vote log output

tools/reproducible.Dockerfile
clang18 introduced `LIBCXX_HARDENING_MODE`. This is similar to `GLIBCXX_ASSERTIONS`: hardening checks in the c++ stdlib that are intended for production use. Many, maybe most, distros build their packages with `GLIBCXX_ASSERTIONS`: it is widely considered a good security practice and something like gcc's new `-fhardened` also enables it by default.
For more on `LIBCXX_HARDENING_MODE` see,
https://libcxx.llvm.org/Hardening.html
We already harden our reproducible builds with `-D_FORTIFY_SOURCE=2 -fstack-protector-strong` so let's add `LIBCXX_HARDENING_MODE=fast`. I am not seeing any performance degradation on a replay (within ~0.25%)
A nice feature of libc++'s implementation is that we can set a default at the build time of libc++ and that's always used by default even for user compiled …
=> add `LIBCXX_HARDENING_MODE=fast` to pinned reproducible builds

libraries/chain/controller.cpp, libraries/chain/finality/finalizer.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/finality/finalizer.hpp, libraries/testing/include/eosio/testing/tester.hpp, libraries/testing/tester.cpp, unittests/savanna_cluster.hpp, unittests/state_history_tests.cpp
Simplify vote restriction by only looking at block timestamp vs wall clock instead of flipping an `enable_voting` flag.
The `testing_allow_voting` change was needed because the tester creates blocks starting with `2020-01-01`.
Resolves #418
=> Only vote on recent blocks

unittests/snapshot_tests.cpp
```
unittests/snapshot_tests.cpp:64:7:   required from here
libraries/boost/libs/test/include/boost/test/tools/old/impl.hpp:185:21:    warning: comparison of integer expressions of different signedness: ‘const long unsigned int’ and  ‘const int’ [-Wsign-compare]
185 |         return left > right;
```
=> Fix a sign-compare warning in snapshot_tests.cpp

tests/disaster_recovery_2.py
Since all nodes are stopped and restarted, the first node to start has no peers to connect to. Provide time for the connection monitor to kick in and establish a connection.
Resolves #390
=> [1.0-beta4] Test: Provide more time for connections to be established

tests/trx_finality_status_test.py
The existing `leeway` was passed to the timeout of waiting on the block, but not on how many blocks were needed. The test was setup to wait for the exact number of blocks before the transaction would be purged from the status multi-index. It needs one more block after that to trigger the remove. Appears the node was queried just before the removal. 
Resolves #415
=> [1.0-beta4] Test: Increase leeway for trx_finality_status_test

tests/TestHarness/Cluster.py
Many of the integration tests start multiple nodes at the same time. Since a node can't connect until its peer is up in running this causes a situation where the first attempt to connect fails. The node then waits the default 30 seconds to attempt to reconnect. For the integration tests, reduce this from 30 seconds to 15 seconds. This should reduce the number of flakey failures due to a test running too slow.
Resolves #424
=> [1.0-beta4] Test: Reduce connection retry interval 

tests/trx_finality_status_test.py
The existing `leeway` was passed to the timeout of waiting on the block, but not on how many blocks were needed. The test was setup to wait for the exact number of blocks before the transaction would be purged from the status multi-index. It needs one more block after that to trigger the remove. Appears the node was queried just before the removal. 
Merges `release/1.0-beta4` into `main` including #429 
Resolves #415
=> [1.0-beta4 -> main] Test: Increase leeway for trx_finality_status_test

tests/nodeos_irreversible_mode_test.py
In speculative or head mode the fork db head can be ahead of the chain head. Update test expected conditions now that blocks are put into the fork db as soon as header evaluation is complete.
Resolves #427
=> [1.0-beta4] Test: forkdb can be ahead of chain head in speculative/head mode

tests/nodeos_irreversible_mode_test.py
In speculative or head mode the fork db head can be ahead of the chain head. Update test expected conditions now that blocks are put into the fork db as soon as header evaluation is complete.
Merges `release/1.0-beta4` into `main` including #433 
Resolves #427
=> [1.0-beta4 -> main] Test: forkdb can be ahead of chain head in speculative/head mode

libraries/chain/fork_database.cpp
Remove `last_final_block_timestamp` from fork choice rule which can prevent a switch to a fork with a locked block to extend via safety.
=> [1.0-beta4] Remove last_final_block_timestamp from fork choice rule

libraries/chain/fork_database.cpp
Remove last_final_block_timestamp from fork choice rule which can prevent a switch to a fork with a locked block to extend via safety.
Merges `release/1.0-beta4` into `main` including #441
=> [1.0-beta4 -> main] Remove last_final_block_timestamp from fork choice rule

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, plugins/producer_plugin/producer_plugin.cpp
Helpful to distinguish between only missing one vote or no votes making into a block.
Add log of all recevied blocks with qc claim, previous, and timestamp.
=> [1.0-beta4] Log when block has no QCs

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, plugins/producer_plugin/producer_plugin.cpp
Helpful to distinguish between only missing one vote or no votes making into a block.
Add log of all recevied blocks with qc claim, previous, and timestamp.
Merges `release/1.0-beta4` into `main` including #434
=> [1.0-beta4 -> main] Log when block has no QCs

libraries/chain/controller.cpp, libraries/chain/finality/finalizer.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/finality/finalizer.hpp, libraries/testing/tester.cpp, plugins/producer_plugin/producer_plugin.cpp, unittests/finalizer_tests.cpp
- Add missing mutex to `fork_database_t::has_root()`.
- When a block fails to produce, do not attempt to produce until the next block time stamp. This prevents a tight spin on failures. We had an issue somewhere for this, but can't find it. I found the problem when testing a possible alternative to #448.
- Refactors terminate-at-block handling into a function.
- Additional `std::move`  in assemble block.
- Logging improvements
- Do not log expired transaction count during replay.
- Do not log expired transaction count if there are none.
- Remove confusing "maybe switch forks" log statement.
- Log block timestamp instead of wall clock time (which is always logged anyway) during start block.
I could separate some/all of these into different PRs if desired.
=> [1.0-beta4] Some misc improvements

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/controller.hpp, plugins/producer_plugin/producer_plugin.cpp
Terminate nodeos when HEAD is greater than LIB + 1000. Puts a limit on how many reversible blocks on a best HEAD can be created before nodeos gives up on LIB moving and exits.
- Adds missing mutex lock in fork database.
- Refactors terminate-at-block handling into one function that checks both conditions for terminate.
Resolves #447
=> [1.0-beta4] Terminate on large reversible size

libraries/chain/controller.cpp, libraries/chain/finality/finalizer.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/finality/finalizer.hpp, libraries/testing/tester.cpp, plugins/producer_plugin/producer_plugin.cpp, unittests/finalizer_tests.cpp
- Add missing mutex to `fork_database_t::has_root()`.
- When a block fails to produce, do not attempt to produce until the next block time stamp. This prevents a tight spin on failures. We had an issue somewhere for this, but can't find it. I found the problem when testing a possible alternative to #448.
- Refactors terminate-at-block handling into a function.
- Additional `std::move`  in assemble block.
- Logging improvements
- Do not log expired transaction count during replay.
- Do not log expired transaction count if there are none.
- Remove confusing "maybe switch forks" log statement.
- Log block timestamp instead of wall clock time (which is always logged anyway) during start block.
Merges `release/1.0-beta4` into `main` including #451
=> [1.0-beta4 -> main] Some misc improvements

libraries/chain/authorization_manager.cpp, libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/authorization_manager.hpp, libraries/chain/include/eosio/chain/pending_snapshot.hpp, libraries/chain/include/eosio/chain/resource_limits.hpp, libraries/chain/include/eosio/chain/snapshot.hpp, libraries/chain/resource_limits.cpp, libraries/chain/snapshot_scheduler.cpp
Add status and progress logs during snapshot creation; can look something like
```
info  2024-08-01T16:18:01.831 nodeos    controller.cpp:3525           log_applied          ] Received block 84115323a9ceb11e... #386613117 @ 2024-08-01T16:18:02.000 signed by eoscannonchn [trxs: 20, lib: 386612788, net: 3016, cpu: 16896, elapsed: 2885, time: 6155, latency: -168 ms]
info  2024-08-01T16:18:01.976 nodeos    snapshot_scheduler.cpp:219    create_snapshot      ] Starting snapshot creation at block 386613117
info  2024-08-01T16:18:06.024 nodeos    snapshot.hpp:431              progress             ] Snapshot creation 10% complete
info  2024-08-01T16:18:11.008 nodeos    snapshot.hpp:431              progress             ] Snapshot creation 16% complete
info  2024-08-01T16:18:16.021 nodeos …
```
=> progress logging during snapshot creation

libraries/chain/controller.cpp, libraries/chain/finality/qc.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/finality/qc.hpp, plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/CMakeLists.txt, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, plugins/chain_plugin/include/eosio/chain_plugin/tracked_votes.hpp, plugins/chain_plugin/tracked_votes.cpp, plugins/producer_plugin/producer_plugin.cpp, tests/CMakeLists.txt, tests/chain_plugin_tests.cpp, tests/get_producers_tests.cpp, tests/get_table_seckey_tests.cpp, tests/get_table_tests.cpp, tests/plugin_http_api_test.py, tests/plugin_http_api_test_savanna.py, tests/test_chain_plugin.cpp
Provide a `chain_api` RPC endpoint `get_finalizer_info` that reports
* active finalizer policy,
* pending finalizer policy if different from the active finalizer policy
* last tracked vote associated with each finalizer in the active (an pending if exist) policy, including the timestamp, block ID, block number of that block it last voted on, whether that vote was strong or weak, and the generation number of the policy it voted as part of.
Resolves https://github.com/AntelopeIO/spring/issues/419
A sample output of the endpoint from a test run:
```
{
"code": 200,
"payload": {
"active_finalizer_policy": {
"generation": 1,
"threshold": 3,
"finalizers": [
{
"description": "finalizer #1",
"weight": 1,
"public_key": "PUB_BLS_GzRFeCxWX8vtIEW9ll-tU9lDOo8c5YK-rUJcihzyGDDT9Qr_WXnnZrh4J0vdZjwViyZTXT6x …
```
=> Add endpoint to chain_api that reports active (and pending if different) finalizer policies and each finalizers last tracked vote

libraries/chain/finality/finalizer.cpp, plugins/producer_plugin/producer_plugin.cpp
- Use `vote` logger for logging of decide vote conditions
- Use `info` level instead of `debug` for liveness check failure
- Use `warn` level instead of `debug` for safety check failure
- Add some static asserts on size of safety.dat file types
Better logging for issue: #456
=> [1.0-beta4] Log liveness/safety check failures info/warn log level

libraries/chain/finality/finalizer.cpp, plugins/producer_plugin/producer_plugin.cpp
- Use `vote` logger for logging of decide vote conditions
- Use `info` level instead of `debug` for liveness check failure
- Use `warn` level instead of `debug` for safety check failure
- Add some static asserts on size of safety.dat file types
Better logging for issue: #456 
Merges `release/1.0-beta4` into `main` including #458
=> [1.0-beta4 -> main] Log liveness/safety check failures info/warn log level

plugins/net_plugin/net_plugin.cpp
If running without a block log or with a truncated block log, it is possible that trying to retrieve a block by number will fail because the block is not available in the block log. Modify on-fork check on first handshake to allow for the block not to be found. Also allow for block not to be found on sync check in case LIB moves during sync check.
Resolves #456
=> [1.0-beta4] P2P: Fix fork check on connection

plugins/net_plugin/net_plugin.cpp
If running without a block log or with a truncated block log, it is possible that trying to retrieve a block by number will fail because the block is not available in the block log. Modify on-fork check on first handshake to allow for the block not to be found. Also allow for block not to be found on sync check in case LIB moves during sync check.
Merges `release/1.0-beta4` into `main` including #466 
Resolves #456
=> [1.0-beta4 -> main] P2P: Fix fork check on connection

programs/cleos/httpc.hpp, programs/cleos/main.cpp
Resolves https://github.com/AntelopeIO/spring/issues/464
`cleos get` command output now looks like
```
./cleos get -h
Retrieve various items and information from the blockchain
Usage: bin/cleos get [OPTIONS] SUBCOMMAND
Options:
-h,--help              Print this help message and exit
--help-all             Show all help
Subcommands:
info                   Get current blockchain information
finalizer_info         Get current finalizer information
transaction-status     Get transaction status information
consensus_parameters   Get current blockchain consensus parameters
block                  Retrieve a full block from the blockchain
...
```
Sample command output in Legacy:
```
./cleos get finalizer_info
{
"active_finalizer_policy": null,
"pending_finalizer_policy": null, …
```
=> Add CLEOS support for get_finalizer_info RPC endpoint

plugins/chain_api_plugin/chain.swagger.yaml
Adds description for return type of new `get_finalizers_info` endpoint in `chain_api` plugin
=> Update API docs for new get_finalizers_info_rpc

plugins/net_plugin/net_plugin.cpp, tests/p2p_sync_throttle_test.py
When all blocks of a requested range were received before any of them had been applied, the `sync_next_expected_num` would not make progress. This caused the node to not ever request the next range of blocks.
- Sync timer was always being canceled in `recv_block` making it effectively useless if any block at all was received
- Existing `p2p_sync_throttle_test.py` is a good test for the sync timer as it does not sync fast enough and the timer fires.
- Increased timeout in test because sync timer now works correctly and causes the test to close connection and reconnect.
- Fixes for reset on failure in `request_next_chuck()`
- Was not clearing out all sync variables
- This also fixes #462
- Fix for calling sync manager for block received before LIB
- Allows sync manager to properly account …
=> [1.0-beta4] P2P: Fix sync stopping making progress

plugins/net_plugin/net_plugin.cpp, tests/p2p_sync_throttle_test.py
When all blocks of a requested range were received before any of them had been applied, the `sync_next_expected_num` would not make progress. This caused the node to not ever request the next range of blocks.
- Sync timer was always being canceled in `recv_block` making it effectively useless if any block at all was received
- Existing `p2p_sync_throttle_test.py` is a good test for the sync timer as it does not sync fast enough and the timer fires.
- Increased timeout in test because sync timer now works correctly and causes the test to close connection and reconnect.
- Fixes for reset on failure in `request_next_chuck()`
- Was not clearing out all sync variables
- This also fixes #462
- Fix for calling sync manager for block received before LIB
- Allows sync manager to properly account …
=> [1.0-beta4 -> main] P2P: Fix sync stopping making progress

plugins/producer_plugin/producer_plugin.cpp
Failing watermark validation would cause node to go into tight spin:
```
error 2024-08-01T19:05:54.914 nodeos    producer_plugin.cpp:1893      start_block          ] Not producing block because "defproducerd" signed a block at the next block time or later (2024-08-01T19:05:55.000) than the pending block time (2024-08-01T19:05:55.000)
debug 2024-08-01T19:05:54.914 nodeos    producer_plugin.cpp:2554      schedule_production_ ] Waiting till another block is received and scheduling Speculative/Production Change
debug 2024-08-01T19:05:54.914 nodeos    producer_plugin.cpp:2628      schedule_delayed_pro ] Scheduling Speculative/Production Change at 2024-08-01T19:05:54.887
... [snip over 2000 entries]
error 2024-08-01T19:05:54.999 nodeos    producer_plugin.cpp:1893      start_block          ] Not …
```
=> [1.0-beta4] Watermark violation should create speculative block

plugins/producer_plugin/producer_plugin.cpp
Failing watermark validation would cause node to go into tight spin:
```
error 2024-08-01T19:05:54.914 nodeos    producer_plugin.cpp:1893      start_block          ] Not producing block because "defproducerd" signed a block at the next block time or later (2024-08-01T19:05:55.000) than the pending block time (2024-08-01T19:05:55.000)
debug 2024-08-01T19:05:54.914 nodeos    producer_plugin.cpp:2554      schedule_production_ ] Waiting till another block is received and scheduling Speculative/Production Change
debug 2024-08-01T19:05:54.914 nodeos    producer_plugin.cpp:2628      schedule_delayed_pro ] Scheduling Speculative/Production Change at 2024-08-01T19:05:54.887
... [snip over 2000 entries]
error 2024-08-01T19:05:54.999 nodeos    producer_plugin.cpp:1893      start_block          ] Not …
```
=> [1.0-beta4 -> main] Watermark violation should create speculative block

plugins/chain_plugin/chain_plugin.cpp
`/v1/chain/compute_transaction` API endpoint should return a failure trace. 
This was accidently changed to false when refactoring send_transaction in 5.0.
See 4.0 impl: https://github.com/AntelopeIO/leap/blob/01dab51ac00aed6730700b82943c30ccfd854fce/plugins/chain_plugin/chain_plugin.cpp#L2562-L2562
Merges `release/5.0` into `main` including https://github.com/AntelopeIO/leap/pull/2400
Resolves [#2281](https://github.com/AntelopeIO/leap/issues/2281)
=> [5.0 -> main] compute_transaction should return failure trace

libraries/chain/include/eosio/chain/finality/qc.hpp, libraries/chain/include/eosio/chain/thread_utils.hpp, plugins/net_plugin/net_plugin.cpp
Avoid GCC warning:
```
libraries/chain/include/eosio/chain/thread_utils.hpp:28:15: warning: use of ‘std::hardware_destructive_interference_size’ [-Winterference-size]
28 |       alignas(hardware_destructive_interference_size)
|               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libraries/chain/include/eosio/chain/thread_utils.hpp:28:15: note: its value can vary between compiler versions or with different ‘-mtune’ or ‘-mcpu’ flags
libraries/chain/include/eosio/chain/thread_utils.hpp:28:15: note: if this use is part of a public ABI, change it to instead use a constant variable you define
libraries/chain/include/eosio/chain/thread_utils.hpp:28:15: note: the default value for the current CPU tuning is 64 bytes
libraries/chain/include/eosio/chain/thread_utils.hpp:28:15: note: you can …
```
=> [1.0-beta4] Use our own hardware_destructive_interference_sz to avoid GCC warning

libraries/chain/include/eosio/chain/finality/qc.hpp, libraries/chain/include/eosio/chain/thread_utils.hpp, plugins/net_plugin/net_plugin.cpp
Avoid GCC warning:
```
libraries/chain/include/eosio/chain/thread_utils.hpp:28:15: warning: use of ‘std::hardware_destructive_interference_size’ [-Winterference-size]
28 |       alignas(hardware_destructive_interference_size)
|               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libraries/chain/include/eosio/chain/thread_utils.hpp:28:15: note: its value can vary between compiler versions or with different ‘-mtune’ or ‘-mcpu’ flags
libraries/chain/include/eosio/chain/thread_utils.hpp:28:15: note: if this use is part of a public ABI, change it to instead use a constant variable you define
libraries/chain/include/eosio/chain/thread_utils.hpp:28:15: note: the default value for the current CPU tuning is 64 bytes
libraries/chain/include/eosio/chain/thread_utils.hpp:28:15: note: you can …
```
=> [1.0-beta4 -> main] Use our own hardware_destructive_interference_sz to avoid GCC warning

libraries/libfc/secp256k1/CMakeLists.txt
Bump libsecp256k1 to v0.5.1.
v0.5.1 changes the default pre computed table size used for signing. The default was changed to match what Bitcoin Core is using (the highest configuration; i.e. largest table). So, change our configuration to match the new default. It seems entirely reasonable to use the same configuration Bitcoin Core does.
On a i7-12700K this improves signing time from about 17.4µs to 16.8µs on a gcc14 build. A 3% improvement at the cost of the secp256k1 context growing by 64KB (inconsequential growth).
=> update to libsecp256k1 0.5.1 for small signing performance improvement

libraries/chain/finality/qc.cpp
- Include index in `add_vote` log
- Log duplicate vote as `trace` level log to avoid huge spam at `debug` level
=> [1.0-beta4] Improve vote logging

plugins/net_plugin/net_plugin.cpp
In 5.0, P2P added new protocol version to include start/end range in `notice_message`. See https://github.com/AntelopeIO/leap/pull/1215
When that was added, `sync_recv_notice` was not updated to use the correct id for `verify_catchup`. This causes additional handshakes and syncing to resolve syncing up to head. 
This caused `disaster_recovery_2` to not reach syned up state in time for the test to not fail.
Resolves #390
=> [1.0-beta4] P2P: Fix handling of known pending block

plugins/net_plugin/net_plugin.cpp
In 5.0, P2P added new protocol version to include start/end range in `notice_message`. See https://github.com/AntelopeIO/leap/pull/1215
When that was added, `sync_recv_notice` was not updated to use the correct id for `verify_catchup`. This causes additional handshakes and syncing to resolve syncing up to head. 
This caused `disaster_recovery_2` to not reach syned up state in time for the test to not fail.
Merges `release/1.0-beta4` into `main` including #484 
Resolves #390
=> [1.0-beta4 -> main] P2P: Fix handling of known pending block

libraries/libfc/include/fc/io/random_access_file.hpp, libraries/state_history/include/eosio/state_history/log.hpp
I encountered an unfortunate design deficiency in `random_access_file`'s `write_datastream`. Upon destruction `write_datastream` will flush its buffer via `do_write()` but that call can throw. When this occurs obviously it's Game Over.
This tweaks the interface to `write_datastream`: exceptions during dtor are swallowed (with a log warning); if a user of the class wants errors to be reported they must call a new `flush()` which still throws if writing the buffer fails.
I don't really like that and I'm open to other potential tweaks, but this pattern does have some precedent in `ofstream` (with `basic_filebuf`).
=> guard against throwing in `random_access_file`'s `write_datastream` dtor

plugins/signature_provider_plugin/include/eosio/signature_provider_plugin/signature_provider_plugin.hpp, plugins/signature_provider_plugin/signature_provider_plugin.cpp, programs/nodeos/main.cpp
On startup and shutdown when logging the `signature-provider`, log the public key but mask out the private key. Before the public and private key were both masked out.
Example output:
`signature-provider = EOS7GQpG7KWgw7FaFDnkua1LadP71nF1kVqAXZ5uD8apE3gUoCxX4=KEY:***`
```
info  2024-08-08T18:46:44.214 nodeos    main.cpp:69                   log_non_default_opti ] Non-default options: data-dir = spring-testnet4-validator-data, config-dir = spring-testnet4, genesis-json = spring-testnet4-validator/genesis.json, plugin = eosio::chain_api_plugin, plugin = eosio::net_api_plugin, http-server-address = 127.0.0.1:7799, p2p-listen-endpoint = 0.0.0.0:9799, chain-state-db-size-mb = 32000, database-map-mode = mapped_private, http-server-address = 127.0.0.1:8899, p2p-listen-endpoint = 0.0.0.0:9899:0, …
```
=> Mask out only the private key when logging signature-provider

plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp, plugins/net_plugin/net_plugin.cpp
Add `last_vote_received` timestamp to connection status
```
{
"peer": "p2p.spring-beta4.jungletestnet.io:9898",
"remote_ip": "136.243.79.230",
"remote_port": "9898",
"connecting": false,
"syncing": false,
"is_bp_peer": false,
"is_socket_open": true,
"is_blocks_only": false,
"is_transactions_only": false,
"last_vote_received": "2024-08-08T16:58:08.714",
"last_handshake": {
"network_version": 1214,
"chain_id": "3eade55e76244083238a944a905517e8827c0da033304f6461108d69c1045e90",
"node_id": "5c2c510673f56fdc44d3ed0bbbe4baaa8ce8e91ab86e91e57f0b128f0993beb1",
"key": "EOS1111111111111111111111111111111114T1Anm",
"time": "1723136044079711000",
"token": "0000000000000000000000000000000000000000000000000000000000000000",
"sig": "SIG_K1_11111111111111111111111111111111111111111111111111111111111111111 …
```
=> P2P: Add last_vote_received to connection status

libraries/state_history/include/eosio/state_history/log.hpp, tests/ship_log.cpp
Prior to leap 3.2, when writing a state history log entry with a block number less than the log's head block number, the log would be truncated to the new lower block number (truncated as in the file's contents are removed entirely).
This behavior allowed an accidental erasure of the entire state history log (see AntelopeIO/leap#659), so in leap 3.2 (AntelopeIO/leap#737) the behavior was modified: writing the genesis block in to a non empty state history log was immediately assert failure, and writing any other blocks in to the log would only truncate the log if the blockid is different; otherwise the logs were left unaltered.
But that change has a side effect that makes it impossible to replay a chain from genesis while keeping the state history logs intact (see #413). So instead, modify …
=> treat rewriting identical genesis block as no-op in state history log

plugins/chain_plugin/tracked_votes.cpp
Follow on to #500. Only track / log votes for recent blocks to avoid overhead during syncing and replaying.
See #479
=> Only track/log votes on recent blocks

plugins/net_plugin/net_plugin.cpp
PR #472 Added additional unneeded check for `!sync_source` in `start_sync` to know if a sync was not already in progress. However, if the last request had received all the blocks from the previous request then `sync_source` would already be reset. This sets up a race condition such that many `start_sync` calls can kick off a new sync instead of continuing the current one.
Also with #472 there is no need to reset `sync_next_expected_num` back to received block when receiving a block already received. This just causes additional requests for blocks already received.
Resolves #499
=> P2P: Fix net_plugin requesting same range repeatedly

tests/separate_prod_fin_test.py
Test for finalizers voting strictly required votes from all finalizers on the inspected block. It is possible to not always get all votes in time. Modify the test to look at a few blocks for the finalizers before indicating failure.
Resolves #511
=> Test: Update test to try a few times for a full set of voting finalizers

libraries/chain/abi_serializer.cpp, libraries/chain/apply_context.cpp, libraries/chain/block_header.cpp, libraries/chain/block_header_state.cpp, libraries/chain/block_header_state_legacy.cpp, libraries/chain/block_state.cpp, libraries/chain/block_state_legacy.cpp, libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/abi_serializer.hpp, libraries/chain/include/eosio/chain/block_header_state_utils.hpp, unittests/finality_proof.hpp
We typically use the map `lower_bound()` api to retrieve an iterator to an extension we are interested in. However this api returns the first entry in the map that is *not less* than the key we are looking for. If the key we are looking for is not present, it could return a different, greater key.
Foe example, see:
https://github.com/AntelopeIO/spring/blob/b58cbbcdc532f430e87a430ed1209bc9c9fce3e2/libraries/chain/block_state.cpp#L197-L201
This doesn't cause an issue right now because `finality_extension` is the last of the header extensions, and `quorum_certificate_extension` is the last of the block extensions (so they have the highest ids), but it is quite fragile.
A common pattern is to do a `count()` to check if the extension is present, followed by a `lower_bound()` to retrieve an …
=> Fix some incorrect extension lookups using `lower_bound` 

CMakeLists.txt, unittests/savanna_cluster.hpp
Disable `NEON` on arm in boost `unordered` because of conflicting declaration for `float16_t` in softfloat library.
Resolves #517.
=> Disable `NEON` on arm in boost `unordered`.

docs/01_nodeos/03_plugins/db_size_api_plugin/index.md, plugins/db_size_api_plugin/db_size_api_plugin.cpp, plugins/db_size_api_plugin/include/eosio/db_size_api_plugin/db_size_api_plugin.hpp
As of Leap 3.1, chainbase has not just the boost interprocess allocator (`segment_manager`) but also `chainbase_node_allocator` was is layered on top of the `segment_manager`. Both of these allocators maintain their own free list. But since `chainbase_node_allocator` sits on top of `segment_manager`, the memory tied up in `chainbase_node_allocator`'s free list is considered used memory from the perspective of `segment_manager`.
The `chainbase_node_allocator` isn't used for everything, for example it's not used for the CoW strings. So various bits of code interface with the top layer but then other bits of code the bottom layer.
And the `db_size_api` is looking at free memory in the bottom layer. That is, when `db_size_api` reports the free bytes it's reporting from the perspective of the …
=> expose chainbase's new "reclaimable" memory in `db_size_api`

libraries/chain/include/eosio/chain/apply_context.hpp
I've noticed for some time that,
https://github.com/AntelopeIO/spring/blob/d361a93bb548c8d79996b37e447569e95f9b1159/libraries/chain/include/eosio/chain/apply_context.hpp#L80-L89
shows up as taking 1.5%+ of main thread time on EOS. This function isn't doing much, and the iterator cache doesn't get large in practice. I'm not sure what is going on, but the overhead seems limited to libc++ builds (our pinned reproducible builds).
Switch the `_object_to_iterator` map to `boost::unordered_flat_map`. There is no ordering requirement for this map (either in consensus or as part of the implementation). For a replay over blocks 381452700 through 381632370, the pinned build improves by a consistent ~2%. There is no performance difference for a stdlibc++ build.
fwiw I tried a `boost::container::map` …
=> use `boost::unordered_flat_map` for iterator cache's `_object_to_iterator`

CMakeModules/EosioTester.cmake.in, CMakeModules/EosioTesterBuild.cmake.in
Follow up to #519. I think we probably need to do this or run the risk of ODR violations (on ARM) if something else uses `boost::unordered` as part of the external test compilation. It's also possible it's already a ODR violation as-is since `apply_context.hpp` -- exposed as public libtester interface -- does a `#include <boost/unordered/unordered_flat_map.hpp>`. (I admit to not looking at `unordered`'s impl yet to know if this ODR violation theory is possible or not, but seems like this is right thing to do -- it's possible original reporter in #517 will need it anyways to compile their external tests)
=> also add `BOOST_UNORDERED_DISABLE_NEON` for users of libtester

plugins/net_plugin/net_plugin.cpp
When rejecting a block we were resetting the `sync_source`. However, we should only reset the `sync_source` if that is the peer we are actually syncing from. `close()` already does the correct check and handles the reset if needed; so just need to remove the reset in `rejected_block`.
Resolves #530
=> P2P: Fix sync stuck in already syncing

plugins/chain_plugin/tracked_votes.cpp
No need to track votes for legacy blocks.
Resolves #539
=> Do not log "no votes" for non-savanna blocks

libraries/chain/block_header_state.cpp, libraries/chain/block_state.cpp, libraries/chain/finality/qc.cpp, libraries/chain/include/eosio/chain/finality/qc.hpp
* Log detailed information when verify_sig fails, including block ID, vote strong or weak.
* Add debug logging when  proposer policy becoming active
```
debug 2024-08-15T12:53:57.365 unit_test block_header_state.cpp:349    finish_next          ] Proposer  policy version change: 0 -> 2
debug 2024-08-15T12:53:57.365 unit_test block_header_state.cpp:351    finish_next          ] New       proposer policy becoming active in block 37:                                                           0000002553a993a7e5895478dd02d8b67716476ca7df7cd78cf221752787f233: {"proposal_time":"2020-  01-01T00:00:11.500","proposer_schedule":{"version":2,"producers":[{"producer_name":"bob",  "authority":[0,         {"threshold":1,"keys":[{"key": …
```
=> [1.0] Better logging for aggregate_vote failure and add logging for proposer policy becoming active

libraries/chain/finality/finalizer.cpp
As described in issue https://github.com/AntelopeIO/spring/issues/534 (3rd `small things` at the end), we have a small test that cannot possibly be true, so this PR removes that dead code.
=> [1.0 -> main] Remove unnecessary code that cannot be executed.Gh 534 2 main

libraries/chain/CMakeLists.txt, plugins/net_plugin/include/eosio/net_plugin/net_utils.hpp, programs/cleos/CMakeLists.txt, tests/trx_generator/http_client_async.hpp
These changes should be fine to merge into `release/1.0` imo, but I'm happy to rebase if needed.
=> [1.0] Add changes required for updating to boost 1.86 - but without the boost upgrade

libraries/chain/CMakeLists.txt, plugins/net_plugin/include/eosio/net_plugin/net_utils.hpp, programs/cleos/CMakeLists.txt, tests/trx_generator/http_client_async.hpp
Merge changes from `release/1.0` which allow to use newer boost versions.
=> [1.0 -> main] Add changes required for updating to boost 1.86 - but without the boost upgrade

libraries/chain/snapshot_scheduler.cpp, plugins/producer_plugin/producer_plugin.cpp, tests/test_snapshot_scheduler.cpp
Merges AntelopeIO/leap#2402 in to 1.0, which resolved AntelopeIO/leap#2261
=> [5.0 -> 1.0] treat a `end_block_num=0` as "forever" in snapshot scheduler for compatibility with leap 4.0 behavior

unittests/savanna_cluster.cpp, unittests/savanna_cluster.hpp, unittests/savanna_cluster_tests.cpp, unittests/savanna_disaster_recovery_tests.cpp, unittests/savanna_finalizer_policy_tests.cpp, unittests/savanna_transition_tests.cpp
Resolves #380.
This PR implements the last three Savanna unittests modeled after the fast testnet wave tests (the finalizer transition tests). Merging this PR will finally close issue #380.
It also updates the `savanna_cluster` test class to automatically get new blocks from connected peers on node startup, which alleviates the need to call `push_block_to()` in tests after restarting a node.
=> Implement last three  Savanna unittests modeled after the fast testnet wave tests. 

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, plugins/net_plugin/net_plugin.cpp
Example output:
```
warn  2024-08-16T12:56:55.440 net-7     net_plugin.cpp:2021           active_sync_fetch_sp ] sync-fetch-span 5000 restricted to 3270 by max-reversible-blocks 3600, fork_db_size 329
info  2024-08-16T12:56:55.440 net-7     net_plugin.cpp:2179           operator()           ] ["jungle4.cryptolions.io:9870 - 34355da" - 2 95.216.44.76:9870] requesting range 1480342 to 1483611, fhead 1480341, lib 1480012
```
Merges `release/1.0` into `main` including #545 
Resolves #528
=> [1.0 -> main] Limit sync-fetch-span by max-reversible-blocks if needed

plugins/chain_plugin/chain_plugin.cpp
Spring verifies that `shared_memory.bin` does not exist when loading a snapshot. Also verify `chain_head.dat` does not exist when loading a snapshot.
```
warn  2024-08-19T11:32:37.908 nodeos    chain_plugin.cpp:1111         plugin_initialize    ] 3110006 plugin_config_exception: Incorrect plugin configuration
Snapshot can only be used to initialize an empty database, remove directory: /home/heifner/ext/leap/cmake-build-debug/bin/spring-testnet4-data/state
{"d":"/home/heifner/ext/leap/cmake-build-debug/bin/spring-testnet4-data/state"}
nodeos  chain_plugin.cpp:797 plugin_initialize
appbase: exception thrown during plugin "eosio::chain_plugin" initialization.
Incorrect plugin configuration
info  2024-08-19T11:32:37.909 nodeos    main.cpp:165                  operator()           ] nodeos …
```
=> [1.0] Verify chain_head.dat does not exist on snapshot load

plugins/chain_plugin/chain_plugin.cpp
Spring verifies that `shared_memory.bin` does not exist when loading a snapshot. Also verify `chain_head.dat` does not exist when loading a snapshot.
```
warn  2024-08-19T11:32:37.908 nodeos    chain_plugin.cpp:1111         plugin_initialize    ] 3110006 plugin_config_exception: Incorrect plugin configuration
Snapshot can only be used to initialize an empty database, remove directory: /home/heifner/ext/leap/cmake-build-debug/bin/spring-testnet4-data/state
{"d":"/home/heifner/ext/leap/cmake-build-debug/bin/spring-testnet4-data/state"}
nodeos  chain_plugin.cpp:797 plugin_initialize
appbase: exception thrown during plugin "eosio::chain_plugin" initialization.
Incorrect plugin configuration
info  2024-08-19T11:32:37.909 nodeos    main.cpp:165                  operator()           ] nodeos …
```
=> [1.0 -> main] Verify chain_head.dat does not exist on snapshot load

libraries/chain/controller.cpp
The new pending producer schedule was being logged before it was set.
```
info  2024-08-19T11:07:18.890 nodeos    controller.cpp:3201           operator()           ] promoting proposed schedule (set in block 69) to pending; current block: 70 lib: 69 schedule: {"version":1,"producers":[{"producer_name":"defproducera","authority":[0,{"threshold":1,"keys":[{"key":"EOS58B33q9S7oNkgeFfcoW3VJYu4obfDiqn5RHGE2ige6jVjUhymR","weight":1}]}]},{"producer_name":"defproducerb","authority":[0,{"threshold":1,"keys":[{"key":"EOS5CbcTDgbks2ptTxvyCbT9HFbzX7PDHUY2wN4DDnVBhhQr2ZNDE","weight":1}]}]},{"producer_name":"defproducerc","authority":[0,{"threshold":1,"keys":[{"key":"EOS6Tkpf8kcDfa32WA9B4nTcEJ64ZdDMSNioDcaL6rzdMwnpzaWJB","weight":1}]}]},{"producer_name":"defproducerd","authority":[0,{"threshold":1,"key …
```
=> [1.0] Fix logging of legacy proposer schedule

libraries/chain/controller.cpp
Update the `max-reversible-blocks` option to only be enforced for blocks after the Savanna transition.
Resolves #579
=> [1.0] Update max-reversible-blocks to only enforce savanna blocks

libraries/chain/controller.cpp
The new pending producer schedule was being logged before it was set.
```
info  2024-08-19T11:07:18.890 nodeos    controller.cpp:3201           operator()           ] promoting proposed schedule (set in block 69) to pending; current block: 70 lib: 69 schedule: {"version":1,"producers":[{"producer_name":"defproducera","authority":[0,{"threshold":1,"keys":[{"key":"EOS58B33q9S7oNkgeFfcoW3VJYu4obfDiqn5RHGE2ige6jVjUhymR","weight":1}]}]},{"producer_name":"defproducerb","authority":[0,{"threshold":1,"keys":[{"key":"EOS5CbcTDgbks2ptTxvyCbT9HFbzX7PDHUY2wN4DDnVBhhQr2ZNDE","weight":1}]}]},{"producer_name":"defproducerc","authority":[0,{"threshold":1,"keys":[{"key":"EOS6Tkpf8kcDfa32WA9B4nTcEJ64ZdDMSNioDcaL6rzdMwnpzaWJB","weight":1}]}]},{"producer_name":"defproducerd","authority":[0,{"threshold":1,"key …
```
=> [1.0 -> main] Fix logging of legacy proposer schedule

libraries/chain/controller.cpp, plugins/chain_plugin/chain_plugin.cpp
Update the `max-reversible-blocks` option to only be enforced for blocks after the Savanna transition.
Merges `release/1.0` into `main` including #587 
Resolves #579
=> [1.0 -> main] Update max-reversible-blocks to only enforce savanna blocks

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, plugins/chain_plugin/chain_plugin.cpp, plugins/net_plugin/net_plugin.cpp, tests/TestHarness/Node.py, tests/nodeos_read_terminate_at_block_test.py
In Spring 1.0.0, unlike Leap, we process blocks into the fork database immediately. This can cause the fork database to grow very large when syncing and shutdown due to hitting the new `max-reversible-blocks` limit (before #545). When a node is shutdown, in Leap, it was assumed that when restarting a node if that node did not receive any blocks from the network it would be at the same height as when it was shutdown. The existing `tests/nodeos_read_terminate_at_block_test.py` integration test verifies this behavior.
However, if the node shutdown because of `max-reversible-blocks` you would like on restart for the node to process blocks out of the fork database potentially allowing LIB to progress and reversible blocks to be consumed and shrink in size. This is at odds with the expected …
=> [1.0] Normally process blocks from the forkdb on startup

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, plugins/chain_plugin/chain_plugin.cpp, plugins/net_plugin/net_plugin.cpp, tests/TestHarness/Node.py, tests/nodeos_read_terminate_at_block_test.py
In Spring 1.0.0, unlike Leap, we process blocks into the fork database immediately. This can cause the fork database to grow very large when syncing and shutdown due to hitting the new `max-reversible-blocks` limit (before #545). When a node is shutdown, in Leap, it was assumed that when restarting a node if that node did not receive any blocks from the network it would be at the same height as when it was shutdown. The existing `tests/nodeos_read_terminate_at_block_test.py` integration test verifies this behavior.
However, if the node shutdown because of `max-reversible-blocks` you would like on restart for the node to process blocks out of the fork database potentially allowing LIB to progress and reversible blocks to be consumed and shrink in size. This is at odds with the expected …
=> [1.0 -> main] Normally process blocks from the forkdb on startup

plugins/net_plugin/net_plugin.cpp
Track when syncing starts as a backup determination on when to allow a new sync to begin. This continues to prevent multiple syncs to be kicked off from different connections at the same time. It works around a race condition on a connection syncing but with no active sync timer running.
Resolves #583
=> [1.0] P2P: Track sync time to know when to allow a new start sync

plugins/net_plugin/net_plugin.cpp
Track when syncing starts as a backup determination on when to allow a new sync to begin. This continues to prevent multiple syncs to be kicked off from different connections at the same time. It works around a race condition on a connection syncing but with no active sync timer running.
Merges `release/1.0` into `main` including #590
Resolves #583
=> [1.0 -> main] P2P: Track sync time to know when to allow a new start sync

libraries/chain/block_log.cpp, libraries/chain/controller.cpp, unittests/blocks_log_replay_tests.cpp, unittests/partitioned_block_log_tests.cpp, unittests/snapshot_tester.hpp, unittests/snapshot_tests.cpp
PR fixes two issues:
- Replaying from a snapshot with no block log, but blocks in the retained directory, issue #586
- Before this PR, block log head would be nullptr and no blocks would be replayed from the retained directory.
- Interrupting replay of block log (from blocks or retained directory) via ctrl-c, restarting replay when no fork database.
- Before this PR, would fail by throwing an error that no fork database exists.
Resolves #586
=> [1.0] Replay from retained directory with no block log

libraries/chain/block_log.cpp, libraries/chain/controller.cpp, unittests/blocks_log_replay_tests.cpp, unittests/partitioned_block_log_tests.cpp, unittests/snapshot_tester.hpp, unittests/snapshot_tests.cpp
PR fixes two issues:
- Replaying from a snapshot with no block log, but blocks in the retained directory, issue #586
- Before this PR, block log head would be nullptr and no blocks would be replayed from the retained directory.
- Interrupting replay of block log (from blocks or retained directory) via ctrl-c, restarting replay when no fork database.
- Before this PR, would fail by throwing an error that no fork database exists.
Merges `release/1.0` into `main` including #565 and #595 (forward backport back to `main`)
Resolves #586
=> [1.0 -> main] Replay from retained directory with no block log

libraries/chain/include/eosio/chain/contract_table_objects.hpp
1.0 merge of AntelopeIO/leap#2403
> Default parameters for the lower bound of a `uint128[2]` ("`checksum256`") index used for the `get_table` RPC call were uninitialized and might cause unexpected results to be returned. Initialize this to zero.
=> [5.0 -> 1.0] fix `true_lowest()` for `uint128[2]` index; possibly resolving some secondary table row RPC queries

libraries/chain/include/eosio/chain/contract_table_objects.hpp
main merge of #600 and AntelopeIO/leap#2403
> Default parameters for the lower bound of a `uint128[2]` ("`checksum256`") index used for the `get_table` RPC call were uninitialized and might cause unexpected results to be returned. Initialize this to zero.
=> [1.0 -> main] fix `true_lowest()` for `uint128[2]` index; possibly resolving some secondary table row RPC queries

libraries/chain/abi_serializer.cpp
Resolves https://github.com/AntelopeIO/leap/issues/2330.
=> [1.0 -> main] limit the vector size that can be reserved 

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/fork_database.hpp, plugins/chain_plugin/chain_plugin.cpp, plugins/net_plugin/net_plugin.cpp, tests/nodeos_startup_catchup.py
Instead of `net_plugin` calculating how many reversible blocks are allowed to limit `sync-fetch-span`, call a method on `controller`. Now logic about which fork database to check is encapsulated to the controller.
Resolves #608
=> [1.0] Add max_reversible_blocks_allowed(), use in net_plugin to limit sync-fetch-span

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/fork_database.hpp, plugins/chain_plugin/chain_plugin.cpp, plugins/net_plugin/net_plugin.cpp, tests/nodeos_startup_catchup.py
Instead of `net_plugin` calculating how many reversible blocks are allowed to limit `sync-fetch-span`, call a method on `controller`. Now logic about which fork database to check is encapsulated to the controller.
Merges `release/1.0` into `main` including #609 
Resolves #608
=> [1.0 -> main] Add max_reversible_blocks_allowed(), use in net_plugin to limit sync-fetch-span

unittests/savanna_cluster.hpp, unittests/savanna_proposer_policy_tests.cpp
Resolves #553.
Also added tests verifying that:
1. when finality advances, proposer policy transitions happens on the expected block.
2. if a proposer policy is already pending, it will become active even if finality stalls.
=> [1.0 -> main] Add unittest verifying that proposer policy does not become active when finality has stalled (and a couple other)

CMakeModules/EosioTester.cmake.in, CMakeModules/EosioTesterBuild.cmake.in
EOS VM within libtester needs to handle `SIGSEGV`. It's fine if other code using libtester chains their own SEGV handlers as well, but boost test by default completely takes over `SIGSEGV` and this prevents proper operation of EOS VM within libtester.
Previously inside of leap/spring we added `--catch_system_errors=no` to all `ctest` invocations of a boost unit test. This works but is a bit annoying because when running the test manually you need to also remember to manually pass `--catch_system_errors=no` or can experience problems. So instead AntelopeIO/leap#1849 does this globally by setting `BOOST_TEST_DEFAULTS_TO_CORE_DUMP`
But that doesn't change behavior for users of libtester and their native contract unit tests. They still would need to know to pass `--catch_system_errors=no` to …
=> [1.0] add `BOOST_TEST_DEFAULTS_TO_CORE_DUMP` to libtester users

plugins/net_plugin/net_plugin.cpp, tests/test_snapshot_scheduler.cpp, unittests/savanna_proposer_policy_tests.cpp
grabbag of different signedness warning fixes I noticed. I'm fine sending these to main instead, but most/all of these were introduced at the 11th hour before cutting 1.0.0 rc
Needs AntelopeIO/chainbase#53
=> [1.0] various different signedness warning fixes

tests/disaster_recovery_2.py
Simplify integration tests and verify expected LIB is reached.
=> [1.0] Test: Simplify disaster_recovery_2 test and verify correct LIB

libraries/libfc/include/fc/scoped_exit.hpp, unittests/savanna_cluster.cpp, unittests/savanna_cluster.hpp, unittests/savanna_misc_tests.cpp
Resolves #544.
Branch `gh_544_check`  created off commit 7beaa202 prior to PR #537 (implementing the FSI changes to avoid the issue) has the new test failing.
=> [1.0] Add test case to demonstrate the weak masking issue

plugins/producer_plugin/producer_plugin.cpp, tests/TestHarness/testUtils.py, tests/TestHarness/transactions.py
- In integration tests when `cleos set contract` fails, log the failure.
- Add `elapsed Xus` to `COULD NOT FIT` log.
```
debug 2024-08-24T19:34:53.979 nodeos    producer_plugin.cpp:2396      handle_push_result   ] [TRX_TRACE] Speculative execution COULD NOT FIT, elapsed 25165us, tx: 58e89df409f96e330c62caa2742e54f17c597918997eba7546647cb92941acc4 RETRYING
debug 2024-08-24T19:35:14.304 nodeos    producer_plugin.cpp:2392      handle_push_result   ] [TRX_TRACE] Block 85 for producer defproducern COULD NOT FIT, elapsed 80049us, tx: caab341eeed1d5f27cb41d566d7a58a0d7ca52e1c56a9035e98453acf9ba95a9 RETRYING
```
Related to #632
=> [1.0] Additional debug output

libraries/chain/controller.cpp, libraries/chain/finality/finalizer.cpp, libraries/chain/include/eosio/chain/finality/finalizer.hpp, libraries/libfc/include/fc/io/datastream_crc.hpp, unittests/finalizer_tests.cpp, unittests/finalizer_vote_tests.cpp
Use `other_branch_latest_time` block timestamp instead of a boolean `votes_forked_since_latest_strong_vote` for tracking votes on other fork branches. See #621 for complete details.
Fixes currently failing test on #619.
Resolves #621 (Tests coming in separate PR)
=> [1.0] Use other_branch_latest_time for liveness

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, tests/ship_streamer_test.py
Fix SHiP replay.
- Add support for replaying SHiP with `--finality-data-history` over Savanna transition blocks.
- Modify `controller::chain_block_id_for_num` and other fork database branch queries to work during replay when there is no fork database root set.
Test failure before fix: https://github.com/AntelopeIO/spring/actions/runs/10582364896
Resolves #649
=> [1.0] SHiP: Fix replay over savanna transition blocks

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, tests/ship_streamer_test.py
Fix SHiP replay.
- Add support for replaying SHiP with `--finality-data-history` over Savanna transition blocks.
- Modify `controller::chain_block_id_for_num` and other fork database branch queries to work during replay when there is no fork database root set.
Test failure before fix: https://github.com/AntelopeIO/spring/actions/runs/10582364896
Merges `release/1.0` into `main` including #655 
Resolves #649
=> [1.0 -> main] SHiP: Fix replay over savanna transition blocks

libraries/chain/webassembly/compiler_builtins.cpp, unittests/api_tests.cpp, unittests/contracts/test_wasts.hpp
Division (or modulo) of INT_MIN by `-1` is ultimately UB due to integer overflow. But not only that, it can cause a fault. For example, the following will fail with `SIGFPE` on x86_64 (build with `-O0` for this trivial case),
```c++
int64_t doit(int64_t in, int64_t x) {
return in / x;
}
int main() {
int64_t x = std::numeric_limits<int64_t>::min();
int64_t y = doit(x, -1);
return 0;
}
```
So what's interesting  to consider is,
https://github.com/AntelopeIO/spring/blob/abc65cef7117f83e769641f4a47d171689b41a08/libraries/chain/webassembly/compiler_builtins.cpp#L36-L51
Thus, it is possible for a contract to pass `std::numeric_limits<__int128>::min()` and `-1` resulting in a division performed via inputs to a library (libgcc/compiler-rt) that has undefined results.
Fortunately, the `int128` …
=> explicitly handle inputs in `__divti3` and `__modti3` that result in UB overflow

tests/liveness_test.py
- Disable production pause on missing votes since the test stops finality as part of the test.
- Enable stale production on restart of production node as it is a producer and it might be its time to produce.
Resolves #653 
Resolves #620
=> [1.0] Test: Fix liveness_test.py integration test flakiness

libraries/chain/finality/finalizer.cpp, libraries/chain/include/eosio/chain/finality/finalizer.hpp
- Modify `save_finalizer_safety_info()` to never throw, but instead to log and return `false`.
- Do not send out or incorporate vote if unable to save the safety file.
- When loading finalizer safety file on producer_plugin startup fail and shutdown nodeos if unable to open the safety.dat file. See example exception message below. 
- `bls_signature` can throw on invalid signature. Not exactly sure if that is possible in `maybe_vote`, but seems like if the private key is invalid somehow it might be possible. Added a try-catch-log-and-drop so an exception there does not kill the thread pool.
- Add missing mutex. Not really needed as `set_default_safety_information()` is only called at startup or during initial transition to savanna when no votes should be flowing. But doesn't hurt and …
=> [1.0 -> main] Improve finalizer safety file exception handling

libraries/chain/finality/finalizer.cpp, plugins/chain_plugin/tracked_votes.cpp, plugins/producer_plugin/producer_plugin.cpp, tests/liveness_test.py
Misc logging improvements:
- Change `liveness check failed` log message to `debug` level to match logging of other finality checks in `decide_vote`.
- Add block timestamp to all `Not producing because` log messages in `producer_plugin`.
- Indicate why producer is implicitly paused in the `Not producing because` log message.
- Add `info` level decide_vote summary log statement, for example:
```
info  2024-08-28T23:54:05.066 chain-0   finalizer.cpp:111             decide_vote          ] block=241 000000f1bd378c3eba4e81bd3e09677f30e7019c41e1c69da066818b2ff95a46, liveness=false, safety=false, can vote=false, voting=no_vote, 2024-08-28T23:52:23.500 <= 2024-08-28T23:52:24.500, locked=145 00000091cee2536578652ccc49fdf32eaac70fe9851e615e1f9834372541af91, latest_qc_claim: …
```
=> [1.0] Logging improvements

libraries/chain/finality/finalizer.cpp, plugins/chain_plugin/tracked_votes.cpp, plugins/producer_plugin/producer_plugin.cpp, tests/liveness_test.py
Misc logging improvements:
- Change `liveness check failed` log message to `debug` level to match logging of other finality checks in `decide_vote`.
- Add block timestamp to all `Not producing because` log messages in `producer_plugin`.
- Indicate why producer is implicitly paused in the `Not producing because` log message.
- Add `info` level decide_vote summary log statement, for example:
```
info  2024-08-28T23:54:05.066 chain-0   finalizer.cpp:111             decide_vote          ] block=241 000000f1bd378c3eba4e81bd3e09677f30e7019c41e1c69da066818b2ff95a46, liveness=false, safety=false, can vote=false, voting=no_vote, 2024-08-28T23:52:23.500 <= 2024-08-28T23:52:24.500, locked=145 00000091cee2536578652ccc49fdf32eaac70fe9851e615e1f9834372541af91, latest_qc_claim: …
```
=> [1.0 -> main] Logging improvements

tests/CMakeLists.txt, tests/TestHarness/Cluster.py, tests/nodeos_snapshot_forked_test.py, tests/production_pause_vote_timeout.py, tests/production_pause_vote_timeout_test_shape.json
Forwards https://github.com/AntelopeIO/spring/pull/667 (RC3 version bump) and https://github.com/AntelopeIO/spring/pull/662 (production-pause-vote-timeout)
Resolves  https://github.com/AntelopeIO/spring/issues/542:
Setup:
Use five nodes in an hourglass topology. The center node is a relay node that initially has vote-threads enabled. The other 4 peripheral nodes are:
* node0: Enables block production for producera and has the finalizer key with description of producera. Has vote-threads enabled. Connect to the center node.
* node1: Enables block production for producerb and has the finalizer key with description of producerb. Has vote-threads enabled. Connect to the center node and Node1.
* producercNode: Enables block production for producerc.
* finalizercNode: Has the finalizer key with …
=> [1.0 -> main] Add integration tests for production-pause-vote-timeout and Release 1.0.0 rc3 version bump

tests/production_restart.py
The test requires pending policy to be in place. It waits on LIB. But a proposed policy is promoted to pending only after the block where it was proposed becomes final; that LIB is not necessarily the LIB where the policy was proposed.
In the test failure reported by https://github.com/AntelopeIO/spring/issues/672, it was LIB on the block before setfinalizer because the setfinalizer was sent to the node that was not producing at the time. On the producer the setfinalizer is in the next block.
The solution is wait until the block where a finalizer policy was proposed becomes final before checking pending policy.
Resolves https://github.com/AntelopeIO/spring/issues/672
=> [1.0] Fix production_restart test flakiness

tests/production_restart.py
The test requires pending policy to be in place. It waits on LIB. But a proposed policy is promoted to pending only after the block where it was proposed becomes final; that LIB is not necessarily the LIB where the policy was proposed.
In the test failure reported by https://github.com/AntelopeIO/spring/issues/672, it was LIB on the block before setfinalizer because the setfinalizer was sent to the node that was not producing at the time. On the producer the setfinalizer is in the next block.
The solution is wait until the block where a finalizer policy was proposed becomes final before checking pending policy.
Forwards https://github.com/AntelopeIO/spring/pull/674
Resolves https://github.com/AntelopeIO/spring/issues/672
=> [1.0 -> main] Fix production_restart test flakiness

libraries/testing/CMakeLists.txt
removed in https://github.com/AntelopeIO/spring/commit/dd66bfc075c5880776bc8c35011c1761d5f9723f
Without this PR  we have compilation issues such as:
```
cFAILED: libraries/testing/CMakeFiles/eosio_testing.dir/contracts.cpp.o 
/usr/bin/clang++-18 -DBN256_HAS_EXTINT 
...
olor=always -Wno-register -MD -MT libraries/testing/CMakeFiles/eosio_testing.dir/contracts.cpp.o -MF libraries/testing/CMakeFiles/eosio_testing.dir/contracts.cpp.o.d -o libraries/testing/CMakeFiles/eosio_testing.dir/contracts.cpp.o -c /home/greg/github/enf/spring/build_clang18_debug/libraries/testing/contracts.cpp
<inline asm>:6:9: error: Could not find incbin file '/home/greg/github/enf/spring/build_clang18_debug/libraries/testing/contracts/eosio.bios/eosio.bios.wasm'
6 | .incbin …
```
=> [1.0] restore cmake dependency needed for test contract compilation

libraries/testing/include/eosio/testing/tester.hpp, libraries/testing/tester.cpp
Add verification to libtester that `controller` signals `accept_block_header`, `accept_block`, `irreversible_block` happen in order and do not repeat.
Working on #619 and wanted a test to verify signals continue to work the same as before.
=> [1.0] Test accept_block_header, accept_block, and irreversible_block signals

libraries/testing/include/eosio/testing/tester.hpp, libraries/testing/tester.cpp
Add verification to libtester that `controller` signals `accept_block_header`, `accept_block`, `irreversible_block` happen in order and do not repeat.
Working on #619 and wanted a test to verify signals continue to work the same as before.
Merges `release/1.0` into `main` including #681
=> [1.0 -> main] Test accept_block_header, accept_block, and irreversible_block signals

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/block_header.hpp
Currently verify_qc_claim is only called on Savanna blocks. On Legacy and Transitions blocks, we need to verify finality and QC extensions too.
Resolves https://github.com/AntelopeIO/spring/issues/691
=> [1.0] Verify finality and QC extensions in Legacy and Transition blocks

libraries/chain/include/eosio/chain/finality/finalizer_policy.hpp, libraries/chain/include/eosio/chain/finality/proposer_policy.hpp, libraries/libfc/include/fc/container/ordered_diff.hpp, libraries/libfc/test/test_ordered_diff.cpp
`ordered_diff` is used to process the finalizer and proposer policy diffs from block header extension `finality_extension`. Since the `finality_extension`, is provided to a node to validate, validate the diff during `apply_diff`.
Related to #691
=> [1.0] Harden ordered_diff

plugins/net_plugin/net_plugin.cpp
- Reset `peer_ping_time_ns` on closing a connection. This peer ping time is used to determine which peers to sync from.
- Update `sync_active_time` on `accepted_block` signal
- It is possible for a sync to timeout a connection because it had not recently received a block. However, with a large `sync-fetch-span` and/or a slow node and/or large blocks to process, the connection can timeout because it had not received a block recently due to the main thread being busy applying blocks. Reset the `sync_active_time` on each applied block so that the `net_plugin` knows the blocks are still being processed and there is no reason to give up on the connection.
Note: `should_sync_from` already took into account the `no_retry` `go_away_reason`.
Resolves #682
=> [1.0.1] P2P: Sync timeout

unittests/savanna_cluster.hpp, unittests/savanna_disaster_recovery_tests.cpp, unittests/savanna_misc_tests.cpp
Partially resolves #694
Implements the two tests described in issue #694.
Also add a test reproducing issue #709.
These tests are disabled for now, so thart ci/cd test pass.
=> [1.0 -> main] Implement the two tests required to validate issue #694 

libraries/chain/block_state.cpp, libraries/chain/include/eosio/chain/block_state.hpp
When creating a `block_state`, verify the block signature before ingesting anything from the block.
Merges `release/1.0` into `main` including #700
=> [1.0.1 -> main] Verify block signature first when creating block_state

libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/block_header_state.hpp, libraries/chain/include/eosio/chain/block_header_state_legacy.hpp, unittests/finalizer_vote_tests.cpp, unittests/savanna_disaster_recovery_tests.cpp
Spring expects all `block_header_state` to have the `header_exts` cache available. The fork database was not loading it for `root` like it does for all other blocks in the fork database. Also block_handle was also not loading it. Added reflector_init so that it is always populated.
To fail requires the first block received from the network to build on the fork database `root`.
Note: Greg added a repeatable test for this issue. See #711 which is enabled by this PR.
Resolves #709
=> [1.0.1] Load header_exts of root in forkdb

tests/TestHarness/Node.py, tests/gelf_test.py, tests/p2p_sync_throttle_test.py, tests/p2p_sync_throttle_test_shape.json
Existing implementation was flaky and depended on prometheus endpoint of nodeos. It required catching a transient state reported by the prometheus endpoint.  This was not reliable.
Now the test sets up two different syncing nodes. One that is heavily throttled and one that is not and verifies the throttled one syncs much slower.
Resolves #541
=> [1.0.1] Test: Rewrite P2P sync throttle test

libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/block_header_state.hpp, libraries/chain/include/eosio/chain/block_header_state_legacy.hpp, unittests/finalizer_vote_tests.cpp, unittests/savanna_disaster_recovery_tests.cpp
Spring expects all `block_header_state` to have the `header_exts` cache available. The fork database was not loading it for `root` like it does for all other blocks in the fork database. Also block_handle was also not loading it. Added reflector_init so that it is always populated.
To fail requires the first block received from the network to build on the fork database `root`.
Note: Greg added a repeatable test for this issue. See #711 which is enabled by this PR.
Merges `release/1.0` into `main` including #710 
Resolves #709
=> [1.0.1 -> main] Load header_exts of root in forkdb

libraries/chain/controller.cpp
Currently QC block extension and finality header extension are not verified during replay.
This PR performs all the basic checks of Legacy, Transition, and Proper Savanna blocks during replay. If `--force-all-checks` is specified, a complete QC validation is performed.
Resolves https://github.com/AntelopeIO/spring/issues/693
=> [1.0.1] Handle block invariant checks during replay appropriately and in particular ensure --force-all-checks is respected

libraries/chain/controller.cpp
Currently QC block extension and finality header extension are not verified during replay.
This PR performs all the basic checks of Legacy, Transition, and Proper Savanna blocks during replay. If `--force-all-checks` is specified, a complete QC validation is performed.
Forwards https://github.com/AntelopeIO/spring/pull/715
Resolves https://github.com/AntelopeIO/spring/issues/693
=> [1.0.1 -> main] Handle block invariant checks during replay appropriately and in particular ensure --force-all-checks is respected 

libraries/chain/include/eosio/chain/webassembly/interface.hpp, libraries/chain/webassembly/compiler_builtins.cpp
This is a pedantic fix to something in consensus touching code. risk/reward should be judged accordingly. I am reasonably comfortable with this change.
Overflowing a `__int128` is considered undefined behavior just like any other integer type. It turns out that contracts are calling `__multi3` with parameters that overflow which causes UBSAN failures when a node is run live on chain (we don't have any test that exercises `__multi3` in this manner).
My impression that from the standpoint of the compiler generating a call to `__multi3`, the call is agnostic to whether the parameters are signed or not because as long as there is no sign extension (that is, you're doing something like a 32-bit multiply to store in a 32-bit result) and as long as we're two's complement (realistically true; …
=> swtich `__multi3` to `unsigned __int128` to avoid integer overflow UB

libraries/libfc/src/log/dmlog_appender.cpp
`fflush` each deep-mind log message.
Attempt to resolve #724, reported from issue's creator that this fixes the issue they were seeing.
=> [1.0.1] Flush deep-mind logger after each message

libraries/chain/controller.cpp
There are several improvements identified in https://github.com/AntelopeIO/spring/pull/715 before and after it was merged in:
* Be explicit about return type to get return value optimization
* Avoid `qc->to_qc_claim()` in normal execution path
* Proper uses of `invalid_qc_claim` exception type
Completely resolves https://github.com/AntelopeIO/spring/issues/693
=> [1.0.1] Small improvements left in PR 715 

libraries/libfc/src/log/dmlog_appender.cpp
`fflush` each deep-mind log message.
Merges `release/1.0` into `main` including #733 
Attempt to resolve #724, reported from issue's creator that this fixes the issue they were seeing.
=> [1.0.1 -> main] Flush deep-mind logger after each message

libraries/libfc/include/fc/container/ordered_diff.hpp, libraries/libfc/test/test_ordered_diff.cpp
`index` in `apply_diff` can be a signed int and can be negative. Currently index is only checked not greater than the size. 
This also results in warnings in numerous places as `apply_diff` is in a header file which is included by a number of files:
```
libraries/libfc/include/fc/container/ordered_diff.hpp:111:35: warning: comparison of integer expressions of different signedness: ‘std::ptrdiff_t’ {aka ‘long int’} and ‘std::vector<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
...
ibraries/libfc/include/fc/container/ordered_diff.hpp:119:26: warning: comparison of integer expressions of different signedness: ‘std::tuple_element<0, std::pair<int, char> >::type’ {aka ‘int’} and ‘std::vector<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
```
Resolves …
=> [1.0.1] Verify index >= 0 in apply_diff and fix warnings

libraries/libfc/include/fc/container/ordered_diff.hpp, libraries/libfc/test/test_ordered_diff.cpp
Forwards https://github.com/AntelopeIO/spring/pull/722
`index` in `apply_diff` can be a signed int and can be negative. Currently index is only checked not greater than the size. 
This also results in warnings in numerous places as `apply_diff` is in a header file which is included by a number of files:
```
libraries/libfc/include/fc/container/ordered_diff.hpp:111:35: warning: comparison of integer expressions of different signedness: ‘std::ptrdiff_t’ {aka ‘long int’} and ‘std::vector<char>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
...
ibraries/libfc/include/fc/container/ordered_diff.hpp:119:26: warning: comparison of integer expressions of different signedness: ‘std::tuple_element<0, std::pair<int, char> >::type’ {aka ‘int’} and ‘std::vector<char>::size_type’ {aka ‘long …
```
=> [1.0.1 -> main] Verify index >= 0 in apply_diff and fix warnings

libraries/chain/block_handle.cpp
When printed this looked like
```
error 2024-09-11T21:25:16.792 nodeos    main.cpp:224                  main                 ] 3000000 chain_exception: blockchain exception
Error reading `chain_head.dat` file. It is likely a Spring 1.0.0 version which is not supported by Spring 1.0.1 and aboveThe best course of action might be to restart from a snapshot
```
This just cleans up the two words that were mashed together.
=> [1.0.1] tweak text layout of 1.0.0 upgrade error message

libraries/chain/controller.cpp
Debug log the `received block` with qc claim for every proper savanna block even if they do not have a qc. Only log every 1000 blocks if syncing.
Example:
```
debug 2024-09-11T18:38:19.352 net-2     controller.cpp:3939           verify_basic_proper_ ] received block: #64 2024-09-11T18:38:19.500 eosio 0000004083746bd01620fcf67d3c2e79acf7e6a50285d738aca44060cdbfdb34, qc claim: {"block_num":62,"is_strong_qc":false}, qc not present, previous: 0000003f138e55a7fcffbfffa53e2ff60c430ab28033df903b3714fae7adc30e
debug 2024-09-11T18:38:19.815 net-2     controller.cpp:3939           verify_basic_proper_ ] received block: #65 2024-09-11T18:38:20.000 eosio 000000414c96210ff400fc724135380d4ea7e6017d240f89ee5d9d99bdef509d, qc claim: {"block_num":64,"is_strong_qc":true}, qc present, previous: …
```
=> [1.0.1 -> main] Log received block with qc_claim even if no qc

unittests/replay_block_invariants_tests.cpp
Forwards https://github.com/AntelopeIO/spring/pull/759
Adds tests for QC validation during replay of blocks (implemented by https://github.com/AntelopeIO/spring/issues/693).
Cases are tested:
+ Invalid QC claim (one that goes backward for example). Replay always fails.
+ Irrelevant QC (claims a block number other than the one claimed in the block header, or mismatching weak/strong claim). Replay always fails.
+ Bad QC (signature validation fails). Replay fails only if `--force-all-checks` is provided.
Resolves https://github.com/AntelopeIO/spring/issues/727
=> [1.0.1 -> main] Add unit tests to verify replay of blocks with bad QC data

unittests/main.cpp
Merges `release/1.0` into `main` including #772 
Resolves #771
=> [1.0.2 -> main] Enable debug logging of the vote logger for unittest --verbose

plugins/net_plugin/net_plugin.cpp
As noted on the addition of pausing during snapshot:
https://github.com/AntelopeIO/leap/pull/2029/files#r1440851488
Pausing does cause peers to disconnect. You have to wait on the connection timer to reconnect and continue syncing. 
Now that we no longer sync ahead: #635 
The issue https://github.com/AntelopeIO/leap/issues/2021 is not an issue anymore as we do not keep syncing ahead. The sync is limited by the `sync-fetch-span`. 
Tested with EOS Mainnet node syncing and with an EOS Mainnet node in-sync.
Resolves #592
=> [1.0.2] Remove explicit net_plugin pause during snapshot

plugins/net_plugin/net_plugin.cpp
As noted on the addition of pausing during snapshot:
https://github.com/AntelopeIO/leap/pull/2029/files#r1440851488
Pausing does cause peers to disconnect. You have to wait on the connection timer to reconnect and continue syncing. 
Now that we no longer sync ahead: #635 
The issue https://github.com/AntelopeIO/leap/issues/2021 is not an issue anymore as we do not keep syncing ahead. The sync is limited by the `sync-fetch-span`. 
Tested with EOS Mainnet node syncing and with an EOS Mainnet node in-sync.
Merges `release/1.0` into `main` including #768 
Resolves #592
=> [1.0.2 -> main] Remove explicit net_plugin pause during snapshot

libraries/libfc/include/fc/io/random_access_file.hpp
`random_access_file`, used for state_history in Spring, makes use of a kernel feature added in 4.16. I didn't really think much of that requirement because 4.16 was released well over 6 years (before EOS genesis!), and is well outside the scope of our officially supported platforms.
Yet we've now seen two reports of users stumbling on this:
* A user running Ubuntu 18.04[^1], which for non-desktop installs will use 4.15 by default. It's possible to opt in to the HWE kernel (default on desktop installs) that moves up to 5.4. This was seen on Telegram somewhere I can't find the link at the moment.
* A user running a Ubuntu 22.04 container on Amazon Linux 2. AL2[^2] actually has three supported kernels: 4.14, 5.10, and 5.15, with 5.10 being the default for new installs now. But the user had …
=> [1.0.2] non-atomic append fallback to `random_access_file` for old kernels

tests/p2p_sync_throttle_test.py
Give the `p2p_sync_throttle_test` plenty of time to sync as it is suppose to sync slowly. Double the timeout. If it synced before the timeout it will not waste any more time.
Resolves #786
=> [1.0.2] Test: p2p_sync_throttle_test. Increase sync timeout.

tests/p2p_sync_throttle_test.py
Give the `p2p_sync_throttle_test` plenty of time to sync as it is suppose to sync slowly. Double the timeout. If it synced before the timeout it will not waste any more time.
Merges `release/1.0` into `main` including #791 
Resolves #786
=> [1.0.2 -> main] Test: p2p_sync_throttle_test. Increase sync timeout.

libraries/testing/tester.cpp
clang18:
```
/home/spoon/f/leap/src/libraries/testing/tester.cpp:378:25: warning: unused variable '[block, id]' [-Wunused-variable]
378 |             const auto& [block, id] = t;
|                         ^
/home/spoon/f/leap/src/libraries/testing/tester.cpp:377:106: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
377 |       [[maybe_unused]] auto accepted_block_header_connection = control->accepted_block_header().connect([this](const block_signal_params& t) {
|                                                                                                          ^~~~
```
an alternative would be to wrap the 5 lines of this connection in a `#ifndef NDEBUG`
=> resolve two unused warnings in libtester that show up only in release builds

libraries/chain/controller.cpp
- Update `Produced block` and `Received block` logs to report `lib` as the last irreversible block according to the reported received or produced block instead of the fork database root. 
- Do not report `confirmed` for savanna blocks.
Example:
```
info  2024-09-18T15:59:04.595 nodeos    controller.cpp:3474           commit_block         ] Produced block 81f53d33889805ad... #63 @ 2024-09-18T15:59:05.000 signed by eosio [trxs: 0, lib: 62, confirmed: 0, net: 0, cpu: 100, elapsed: 139, time: 8174]
...
info  2024-09-18T15:59:41.052 nodeos    controller.cpp:3474           commit_block         ] Produced block 52609b49f8a12cdb... #136 @ 2024-09-18T15:59:41.500 signed by defproducera [trxs: 0, lib: 134, net: 0, cpu: 100, elapsed: 157, time: 2230]
info  2024-09-18T15:59:41.973 nodeos …
```
=> [1.0.2] Update Produced block and Received block logs

libraries/chain/controller.cpp
- Update `Produced block` and `Received block` logs to report `lib` as the last irreversible block according to the reported received or produced block instead of the fork database root. 
- Do not report `confirmed` for savanna blocks.
Example:
```
info  2024-09-18T15:59:04.595 nodeos    controller.cpp:3474           commit_block         ] Produced block 81f53d33889805ad... #63 @ 2024-09-18T15:59:05.000 signed by eosio [trxs: 0, lib: 62, confirmed: 0, net: 0, cpu: 100, elapsed: 139, time: 8174]
...
info  2024-09-18T15:59:41.052 nodeos    controller.cpp:3474           commit_block         ] Produced block 52609b49f8a12cdb... #136 @ 2024-09-18T15:59:41.500 signed by defproducera [trxs: 0, lib: 134, net: 0, cpu: 100, elapsed: 157, time: 2230]
info  2024-09-18T15:59:41.973 nodeos …
```
=> [1.0.2 -> main] Update Produced block and Received block logs

plugins/net_plugin/net_plugin.cpp
Remove handling of unused `request_message` `normal` mode.
Related to #612
=> P2P: Remove dead code

libraries/testing/tester.cpp, plugins/producer_plugin/test/test_block_timing_util.cpp, unittests/finalizer_tests.cpp
Resolves #764 
-  `finalizer_tests/finalizer_safety_file_versioning` validates loading older versions. Also validate current version: we should be able to load the reference file, save the fsi info, and end up with exactly the same bytes.
- also check that the current version of  safety.dat file committed to the repo can be loaded on nodeos startup.
- Fixes a few compilation warnings that I noticed when looking at a build failure.
=> Add new unittest to validate current finalizer safety file i/o

libraries/testing/tester.cpp
Resolves #764 
-  `finalizer_tests/finalizer_safety_file_versioning` validates loading older versions. Also validate current version: we should be able to load the reference file, save the fsi info, and end up with exactly the same bytes.
- also check that the current version of  safety.dat file committed to the repo can be loaded on nodeos startup.
- Fixes a few compilation warnings that I noticed when looking at a build failure.
=> [1.0.2 -> main] Add new unittest to validate current finalizer safety file i/o

unittests/block_log_get_block_tests.cpp
Add tests for read serialized block from
* single block log file
* spilt block log files
* error handling
Resolves https://github.com/AntelopeIO/spring/issues/808
=> Add tests for get_serialized_block_by_number

libraries/state_history/abi.cpp
This adds the block header extensions to the state history ABI making it easy for state history clients to parse these.
An example (crude) state history client easily accessing these,
```js
import WebSocket from 'ws';
import {ABI, Serializer} from '@wharfkit/antelope';
let abi = null;
const ws = new WebSocket('ws://127.0.0.1:8080/');
ws.on('message', msg => {
if(!abi) {
abi = new ABI(JSON.parse(msg));
const req = {
start_block_num: 2,
end_block_num: 9999999,
max_messages_in_flight: 9999999,
have_positions: [],
irreversible_only: false,
fetch_block: true,
fetch_traces: false,
fetch_deltas: false,
fetch_finality_data:false
};
ws.send(Serializer.encode({object: ['get_blocks_request_v1', req], abi, type:'request'}).array);
}
else {
let signed_block = …
```
=> [1.0.2] add block header extension types to state history ABI

libraries/state_history/abi.cpp
=> [1.0.2 -> main] add block header extension types to state history ABI

plugins/net_plugin/net_plugin.cpp, tests/TestHarness/Node.py, tests/nodeos_startup_catchup.py
Issue #789 was to create a test that verifies #777. The new test exposed an issue with the current implementation that would allow it to sync ahead too far when blocks have not made it to the fork database yet. Includes a fix that verifies fork database has the block being evaluated before considering syncing ahead.
Failing test before fix: https://github.com/AntelopeIO/spring/actions/runs/11002592099
Resolves #789
=> [1.0.2] Prevent sync ahead in irreversible mode

plugins/net_plugin/net_plugin.cpp, tests/TestHarness/Node.py, tests/nodeos_startup_catchup.py
Issue #789 was to create a test that verifies #777. The new test exposed an issue with the current implementation that would allow it to sync ahead too far when blocks have not made it to the fork database yet. Includes a fix that verifies fork database has the block being evaluated before considering syncing ahead.
Failing test before fix: https://github.com/AntelopeIO/spring/actions/runs/11002592099
Merges `release/1.0` into `main` including #811 
Resolves #789
=> [1.0.2 -> main] Prevent sync ahead in irreversible mode

plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp, plugins/state_history_plugin/state_history_plugin.cpp, tests/CMakeLists.txt, tests/ship_kill_client_test.py
`state_history_plugin` (SHiP) would sometimes hang on shutdown. The `nodeos` process would get stuck trying to lock a mutex of the main application `io_context` strand while destroying a `boost::beast::websocket::stream`. 
Created a test that reproduces the failure (thanks @taokayan for #813). The failure was not reliably repeatable, but it did fail on every CI/CD run for at least one of the platforms. See for example: https://github.com/AntelopeIO/spring/actions/runs/11017331583/job/30595880305
Modified SHiP `boost::beast::websocket` to use the SHiP thread instead of the main application thread executor strand.
Resolves #815
=> [1.0.2] SHiP: Fix hang on shutdown

plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp, plugins/state_history_plugin/state_history_plugin.cpp, tests/CMakeLists.txt, tests/ship_kill_client_test.py
`state_history_plugin` (SHiP) would sometimes hang on shutdown. The `nodeos` process would get stuck trying to lock a mutex of the main application `io_context` strand while destroying a `boost::beast::websocket::stream`. 
Created a test that reproduces the failure (thanks @taokayan for #813). The failure was not reliably repeatable, but it did fail on every CI/CD run for at least one of the platforms. See for example: https://github.com/AntelopeIO/spring/actions/runs/11017331583/job/30595880305
Modified SHiP `boost::beast::websocket` to use the SHiP thread instead of the main application thread executor strand.
Merges `release/1.0` into `main` including #816.
Resolves #815
=> [1.0.2 -> main] SHiP: Fix hang on shutdown

tests/TestHarness/Node.py
for example,
```
Node.py:674: SyntaxWarning: invalid escape sequence '\.'
match=re.match("stderr\..+\.txt", entry.name)
```
I don't claim this PR does an exhaustive fix, these are just some that I saw flagged recently
=> fix Python 3.12 `SyntaxWarning`s due to `invalid escape sequence`

libraries/chain/platform_timer_asio_fallback.cpp
`platform_timer_asio_fallback.cpp` isn't expected to be used for Linux, macOS, or even freeBSD builds. For some unknown reason (that I suspect is a bug upstream), building with certain sanitizer options causes sniffing of the posix timer to fail at run time
https://github.com/AntelopeIO/spring/blob/dbbf776c3eeb05563cafc9a7248b01801b2010e3/libraries/chain/CMakeLists.txt#L9-L19
Unaware I was using this asio fallback timer I hit a sanitizer failure due to destruction order here (destroying io_context before all users of it are destroyed). Might as well fix it.
=> fix dtor order for fallback asio deadline timer

plugins/net_plugin/net_plugin.cpp
Resolve address on reconnect.
Instead of:
````
info  2024-09-25T21:50:50.686 net-1     net_plugin.cpp:2797           operator()           ] connection failed to p2p.telos-bad.zenblocks.io:9876, Element not found
info  2024-09-25T21:50:50.686 net-1     net_plugin.cpp:1461           _close               ] ["p2p.telos-bad.zenblocks.io:9876" - 1 <unknown>:<unknown>] closing
````
Now you get:
```
warn  2024-09-25T21:42:48.642 net-0     net_plugin.cpp:4524           operator()           ] Unable to resolve p2p.telos-bad.zenblocks.io:9876 Host not found (authoritative)
```
Merges Leap `release/5.0` into Spring `release/1.0` including https://github.com/AntelopeIO/leap/pull/2408
Resolves #525
=> [5.0.3 -> 1.0.3] P2P: Resolve on reconnect

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, plugins/producer_plugin/producer_plugin.cpp
Ported  fix from `main` for incorrect reported total time of applying a received block or produced block.
Only minimum required changes were made, except adding time unit `us` for `elapsed` and `time` for better clarity because `latency` already had `ms` as postfix.
Before the change:
`info  2024-09-30T14:33:33.415 nodeos    controller.cpp:3633           log_applied          ]  Received block bcd746757a3db674... #366563000 @ 2024-08-04T19:14:51.500 signed by eosusacartel [trxs: 0, lib: 366562668, net: 0, cpu: 100, elapsed: 259, time: 869, latency: 4907921915 ms`
After the change:
`info  2024-09-30T14:35:11.723 nodeos    controller.cpp:3627           log_applied          ]  Received block bcd746757a3db674... #366563000 @ 2024-08-04T19:14:51.500 signed by eosusacartel [trxs: 0, lib: …
=> [1.0.2] Fix incorrect reported total time of applying a received block or produced block

plugins/net_plugin/net_plugin.cpp
Causing SEGFAULTs in CI/CD runs of the `p2p_sync_throttle_test`.
Reverts AntelopeIO/spring#825
=> Revert "[5.0.3 -> 1.0.2] P2P: Resolve on reconnect"

plugins/net_plugin/net_plugin.cpp
Causing SEGFAULTs in CI/CD runs of the `p2p_sync_throttle_test`.
Reverts AntelopeIO/spring#826
=> Revert "[1.0.2 -> main] P2P: Resolve on reconnect"

plugins/net_plugin/net_plugin.cpp
In almost all cases a node should wait for the connection monitor to reconnect. Change the `reconnect` default to `false` so that the connect is not retried until the next time the connection monitor runs.
Resolves #830
=> [1.0.2] P2P: Normally wait for connection monitor to reconnect

plugins/net_plugin/net_plugin.cpp
In almost all cases a node should wait for the connection monitor to reconnect. Change the `reconnect` default to `false` so that the connect is not retried until the next time the connection monitor runs.
Merges `release/1.0` into `main` including #838 
Resolves #830
=> [1.0.2 -> main] P2P: Normally wait for connection monitor to reconnect

plugins/net_plugin/net_plugin.cpp
A info level log statement for every handshake message makes it difficult to see actual useful information. Also people have been reporting these as if they indicate a problem.
Resolves #829
=> [1.0.2] P2P: Change handshake logs to debug instead of info

plugins/net_plugin/net_plugin.cpp
A info level log statement for every handshake message makes it difficult to see actual useful information. Also people have been reporting these as if they indicate a problem.
Merges `release/1.0` into `main` including #839 
Resolves #829
=> [1.0.2 -> main] P2P: Change handshake logs to debug instead of info

plugins/state_history_plugin/state_history_plugin.cpp
This is a temporary fix until issue #842 can be worked. Some alternatives were attempted, but no simple fix could be found that didn't require more work toward #842 then desired for 1.0.x. See https://github.com/AntelopeIO/appbase/pull/34
Test runs of a hacked up state_history_plugin with sleeps that caused it to hang on almost every CI/CD run.
Example failures: https://github.com/AntelopeIO/spring/actions/runs/11076070901
With this fix: https://github.com/AntelopeIO/spring/actions/runs/11124229769
Resolves #822
=> [1.0.2] SHiP: Fix hang on exit

plugins/state_history_plugin/state_history_plugin.cpp
This is a temporary fix until issue #842 can be worked. Some alternatives were attempted, but no simple fix could be found that didn't require more work toward #842 then desired for 1.0.x. See https://github.com/AntelopeIO/appbase/pull/34
Test runs of a hacked up state_history_plugin with sleeps that caused it to hang on almost every CI/CD run.
Example failures: https://github.com/AntelopeIO/spring/actions/runs/11076070901
With this fix: https://github.com/AntelopeIO/spring/actions/runs/11124229769
Merges `release/1.0` into `main` including #845 
Resolves #822
=> [1.0.2 -> main] SHiP: Fix hang on exit

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp
This PR
* fixes incorrect reported time for "Produced blocks"
* changes `time` for "Produced blocks" to `producing time`, and for "Received blocks" to `applying time`
* adds time unit `us` to reported CPU time
Before the changes
`info  2024-10-01T18:31:59.066 nodeos    controller.cpp:3462           commit_block         ] Produced block dd7794184632fdd2... #100 @ 2024-10-01T18:31:59.500 signed by eosio [trxs: 0, lib: 98, net: 0, cpu: 100, elapsed: 342 us, time: 1727797983669080 us]`
After
`info  2024-10-01T19:07:27.667 nodeos    controller.cpp:3461           commit_block         ] Produced block b29e040564b322f2... #100 @ 2024-10-01T19:07:28.000 signed by eosio [trxs: 0, lib: 98, net: 0, cpu: 100 us, elapsed: 291 us, producing time: 451393 us]`
Fix …
=> [1.0.2] Fix reported time for produced blocks and fix confusing reported time name

libraries/chain/controller.cpp
Forwards https://github.com/AntelopeIO/spring/pull/850
This PR
* fixes incorrect reported time for "Produced blocks"
* changes `time` for "Produced blocks" to `producing time`, and for "Received blocks" to `applying time`
* adds time unit `us` to reported CPU time
Before the changes
`info  2024-10-01T18:31:59.066 nodeos    controller.cpp:3462           commit_block         ] Produced block dd7794184632fdd2... #100 @ 2024-10-01T18:31:59.500 signed by eosio [trxs: 0, lib: 98, net: 0, cpu: 100, elapsed: 342 us, time: 1727797983669080 us]`
After
`info  2024-10-01T19:07:27.667 nodeos    controller.cpp:3461           commit_block         ] Produced block b29e040564b322f2... #100 @ 2024-10-01T19:07:28.000 signed by eosio [trxs: 0, lib: 98, net: 0, cpu: 100 us, elapsed: 291 us, producing time: …
=> [1.0.2 -> main ] Fix reported time for produced blocks and fix confusing reported time name

.github/workflows/llvm.yaml
Spring is expected to build with LLVM versions 7 through 11. As #578 is worked this range of versions will change to include newer versions. I'd like to have a way to demonstrate that newer versions do indeed compile and test successfully beyond "trust me bro".
So add a simple manually dispatched workflow that compiles with all supported LLVM major versions. This seems like a good enough tradeoff over doing something vastly more complex in CI, and I certainly do not want this to run on every PR. The main risk I see is that since this workflow is disparate to the primary per-PR build workflow it can potentially get out of date; such as the build dependencies or `cmake`/`ctest` arguments going stale. I feel like that's an acceptable risk at the moment.
A run of this workflow can be found …
=> add manually run workflow to exhaustively test all LLVM versions expected to work

plugins/producer_plugin/producer_plugin.cpp
Resolves #831.
Also did some cleanup, replacing one instance of `report` with `populate_speculative_block_metrics` (which does just that instead of calling the other `report`.)
=> [1.0.3 -> main] Fix issue with block report log time including the time for maybe_switch_forks

tests/nodeos_snapshot_diff_test.py
Forwards https://github.com/AntelopeIO/spring/pull/875.
Recently, `nodeos_snapshot_diff_test` fails in almost every CICD run.
This is due to a race condition that at the startup of head mode node, net thread and http thread can start to work in different order. If http thread processes `schedule_snapshot` request after net thread starts to sync with the irreversible mode node, schedule_snapshot request will miss the scheduled block number. If it is before net thread starts to sync with the irreversible mode node, `schedule_snapshot` request will catch the scheduled block number and the snapshot is taken.
This PR changes to start up the head mode node while the irreversible mode node is down so that net thread will not sync, make `schedule_snapshot` request, and finally restart …
=> [1.0.3 -> main] Fix flaky nodeos_snapshot_diff_test due to a race condition

libraries/chain/controller.cpp, unittests/savanna_cluster.hpp, unittests/savanna_misc_tests.cpp
Resolves #869 
I added a test attempting to reproduce the issue, but in order to activate the code in question, I would have to be able to update the blocks in `fork_db`  to have `validated = false`, so they are not applied during the `replay()` call. I don't think it is worth adding an API in controller allowing to do this for this test.
=> [1.0.3] Restart with ctrl-c during replay of forkdb spams log

plugins/net_plugin/net_plugin.cpp
Resolves #882.
While moving some code around (see [here](https://github.com/AntelopeIO/spring/pull/590/files)), a call to:
`void connection::close(bool reconnect, bool shutdown)`
became a call to:
`int close(int __fd)`
This restores the intended behavior (close the actual connection, instead of closing fd number 1)
=> [1.0] Test failure: p2p_sync_throttle_test

plugins/net_plugin/net_plugin.cpp
When a connection is throttled it will not attempt to enqueue another block unless `enqueue_sync_block` is called. This will happen on any message sent to the connection. However, that can be a long time if the node has to wait for a heart-beat timeout before some message is sent to the peer. 
Instead, schedule a try-again call to `enqueue_sync_block` in 100ms. 
This fixes the current issue with `p2p_sync_throttle_test` which could not make progress because it repeately received a sync wait timeout.
Partially resolves #882, See #897
=> [1.0.3] P2P: Schedule a retry of enqueue_sync_block when throttled

plugins/net_plugin/net_plugin.cpp
Resolves #882.
While moving some code around (see [here](https://github.com/AntelopeIO/spring/pull/590/files)), a call to:
`void connection::close(bool reconnect, bool shutdown)`
became a call to:
`int close(int __fd)`
This restores the intended behavior (close the actual connection, instead of closing fd number 1)
=> [1.0.3 -> main] Test failure: p2p_sync_throttle_test

.cicd/platforms/asan.Dockerfile, .cicd/platforms/ubsan.Dockerfile
Upgrade from clang18 to clang19. Just under the assumption that newer versions will be better.
=> bump sanitizer builds to clang19

.github/workflows/llvm.yaml, unittests/eosvmoc_limits_tests.cpp
Relax the pass/fail criteria for this test. Generated code size can vary based on LLVM version being used and this test is not intended to detect regressions or minute differences between those LLVM versions. (put another way, the generated code size is a subjective limit)
Reenable `eosvmoc_limits_unit_test_eos-vm-oc` in the exhaustive LLVM workflow now that the different versions the workflow uses will not get caught up on this test. Example passing run is at,
https://github.com/AntelopeIO/spring/actions/runs/11223260327
=> relax eosvmoc_limits_test's generated_code_size_limit pass/fail criteria; reenable test in exhaustive LLVM workflow

libraries/chain/webassembly/runtimes/eos-vm-oc/LLVMJIT.cpp
Spring claims that it builds with LLVM versions 7 through 11. Code says it,
https://github.com/AntelopeIO/spring/blob/1606adef60a34e52694fd75623f9615ca1bb78fb/CMakeLists.txt#L68-L70
README says it,
https://github.com/AntelopeIO/spring/blob/1606adef60a34e52694fd75623f9615ca1bb78fb/README.md?plain=1#L55
Unfortunately building with versions 7-9 was broken in leap 5.0. This change restores building with LLVM 7 through 11 by using an older interface that's common across all supported LLVM versions.
An example exhaustive workflow run with all versions 7-11 enabled:
https://github.com/AntelopeIO/spring/actions/runs/11223407160
(this is off a demonstration only branch that cherry-picks the workflow back to 1.0, as otherwise it only exists on main. plus also then adding #902 on top)
=> [1.0.3] fix building with LLVM 7, 8, and 9

.github/workflows/llvm.yaml
With LLVM 7/8/9 fixed now, add these versions to the exhaustive workflow. No example run; it's much the same as #903 example already
=> add LLVM 7, 8, and 9 to exhaustive LLVM workflow

tests/TestHarness/Node.py
Resolves #848.
This updates the `verifyStartingBlockMessages` check in `Node.py` to check that we have only one `Starting block` in the log for any block number *unless*:
1. the block was restarted because it was exhausted, 
2. or the second `Starting block` is for a different block time than the first.
I have checked the new regular expression with a small python script against the log and it appears to work fine.
script:
```
import re
def check_file_for_pattern(file_path, pattern):
regex = re.compile(pattern)
with open(file_path, 'r') as file:
for line_num, line in enumerate(file, start=1):
match = regex.match(line)
if match:
blockNumber, time = match.group(1), match.group(2)
print(f"{blockNumber} -> {time}")
if __name__ == "__main__":
file_path = "stderr.2024_10_01_13_21_16.txt" …
```
=> [1.0.3] Test failure: distributed-transactions-if-test

plugins/net_plugin/net_plugin.cpp
Resolve address on reconnect. (Take 3, See #825, #868)
Instead of:
````
info  2024-09-25T21:50:50.686 net-1     net_plugin.cpp:2797           operator()           ] connection failed to p2p.telos-bad.zenblocks.io:9876, Element not found
info  2024-09-25T21:50:50.686 net-1     net_plugin.cpp:1461           _close               ] ["p2p.telos-bad.zenblocks.io:9876" - 1 <unknown>:<unknown>] closing
````
Now you get:
```
warn  2024-09-25T21:42:48.642 net-0     net_plugin.cpp:4524           operator()           ] Unable to resolve p2p.telos-bad.zenblocks.io:9876 Host not found (authoritative)
```
This takes a different approach than #825. This approach is closer to Leap 4.0 approach to connection lifetime although it does keep the `connections_manager` added in Leap 5.0. 
The failure of #868 …
=> [1.0.3] P2P: Resolve on reconnect - Take 3

plugins/net_plugin/net_plugin.cpp
Note almost all the work of #643 was done as part of #529. This PR represents the remaining part of closing immediately if a block is invalid.
Resolves #643
=> P2P: Immediately close on bad block

plugins/net_plugin/net_plugin.cpp
Small optimization of handling of errors for vote messages. Shortcut out of loop when connection is found.
Improve error message for invalid vote message.
=> [1.0.3] Optimize handling of invalid vote message

unittests/eosvmoc_limits_tests.cpp
This is a replacement for AntelopeIO/leap#2392 which was not accepted prior to that release going in to another support phase.
Recall that the way `ctest` tests are populated for `unit_test` are by finding all the .cpp files in the `unittests` directory,
https://github.com/AntelopeIO/spring/blob/9a1d68b89d45a5273ed9b1eb786a0ea393ec4eff/unittests/CMakeLists.txt#L73
sending those through a `grep` to find the `TEST_SUITE()` for each,
https://github.com/AntelopeIO/spring/blob/9a1d68b89d45a5273ed9b1eb786a0ea393ec4eff/unittests/CMakeLists.txt#L94
and then adding a test on what it find, for each WASM runtime enabled,
https://github.com/AntelopeIO/spring/blob/9a1d68b89d45a5273ed9b1eb786a0ea393ec4eff/unittests/CMakeLists.txt#L100-L101
Notice how previously the entire `eosvmoc_limits_tests.cpp` is …
=> [1.0.3] fix eosvmoc_limits_tests on non-x86 and non-Linux (where OC is not supported)

libraries/chain/block_state.cpp, libraries/chain/finality/qc.cpp, libraries/chain/include/eosio/chain/block_header_state.hpp, libraries/chain/include/eosio/chain/finality/qc.hpp
Resolves #743.
This moves the `verify_qc` API from `aggregating_qc_t` to `qc_t`.
It also renames it to `verify`, because `qc.verify_qc(policies)` seems a bit redundant.
It also removes `verify_dual_finalizers_votes` and `votes_same_at` from the external API because these are internal implementation details.
=> Simplify qc verification and  avoid creating a new `aggregating_qc` class.

unittests/eosvmoc_limits_tests.cpp
=> [1.0.3 -> main] fix eosvmoc_limits_tests on non-x86 and non-Linux (where OC is not supported)

docs/01_nodeos/04_replays/how-to-replay-from-a-blocks.log.md, libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/config.hpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/fork_database.hpp, libraries/custom_appbase/include/eosio/chain/exec_pri_queue.hpp, libraries/testing/include/eosio/testing/tester.hpp, libraries/testing/tester.cpp, plugins/chain_interface/include/eosio/chain/plugin_interface.hpp, plugins/chain_plugin/account_query_db.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/net_plugin/include/eosio/net_plugin/protocol.hpp, plugins/net_plugin/net_plugin.cpp, plugins/producer_plugin/producer_plugin.cpp, plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp, programs/spring-util/actions/blocklog.cpp, unittests/blocks_log_replay_tests.cpp, unittests/finalizer_vote_tests.cpp, unittests/fork_db_tests.cpp, unittests/forked_tests.cpp, unittests/savanna_cluster.hpp, unittests/savanna_misc_tests.cpp, unittests/state_history_tests.cpp, unittests/vote_processor_tests.cpp
Most of the changes involve using `froot` instead of `lib`.
Did not change the interface of `tester` to avoid uses having to update their tests.
`get_info` was unchanged; it still reports `last_irreversible_block_num` and `last_irreversible_block_id` for `forkdb_root_block_num` and `forkdb_root_block_id`.
Resolves #806
=> Normalize usage of LIB

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, plugins/chain_interface/include/eosio/chain/plugin_interface.hpp, plugins/net_plugin/net_plugin.cpp, plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp, plugins/producer_plugin/producer_plugin.cpp
- Interrupt processing of blocks in tight apply block loop.
- Provides much quicker shutdown during syncing.
- Allows `v1/chain/get_info` calls to return quickly during syncing.
- Restores logging every 1000 blocks during replay.
Note this takes a different approach for `main` than #921 does for `release/1.0` because `main` has the optimization of not posting a `handler_id::process_incoming_block` if one already exists.
Resolves #284
=> Limit apply blocks

libraries/libfc/include/fc/container/ordered_diff.hpp, libraries/libfc/test/test_ordered_diff.cpp
Resolves #701.
This PR adds a `checker` class which has a `Print` function to output the diff result in a form that can be used as an initializer. This was useful to generate the `diff_result` initializers we want to compare with.
=> Update `ordered_diff` tests to check that the diff result is not changing (as it is part of consensus)

programs/cleos/main.cpp, programs/spring-util/main.cpp
Rename `LeapFormatter` to `SpringFormatter`.
Requires https://github.com/AntelopeIO/CLI11/pull/8
Minimum changes made to `AntelopeIO/CLI11` as it has been modified to add auto-completion and to add support for `SpringFromatter`. 
Note: `AntelopeIO/CLI11` is a fork of https://github.com/hailo-ai/CLI11 not https://github.com/CLIUtils/CLI11. Doesn't seem worth the effort at this point to do more. 
Resolves #569
=> Update CLI11 and rename LeapFormatter

libraries/chain/include/eosio/chain/chain_id_type.hpp, libraries/libfc/include/fc/crypto/hex.hpp, plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/CMakeLists.txt, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/get_info_db.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, plugins/chain_plugin/include/eosio/chain_plugin/get_info_db.hpp, plugins/prometheus_plugin/metrics.hpp, programs/cleos/main.cpp, tests/chain_plugin_tests.cpp, tests/get_producers_tests.cpp, tests/get_table_seckey_tests.cpp, tests/get_table_tests.cpp, tests/test_chain_plugin.cpp
`/v1/chain/get_info` is a top 1 or 2 used RPC endpoint (https://github.com/AntelopeIO/leap/issues/1212). It is currently processed on the `main` thread. Moving it off the main thread will reduce load on the `main` thread, and will shorten response time when the `main` thread is stuck (https://github.com/AntelopeIO/spring/issues/830).
This PR moves `get_info` off the `main` thread and runs it on `http` thread.  The data required by get_info is cached on `accept_block` signal  and is used to service `get_info` when needed.
Notably, the implementation is mutex free such that the `main` thread is never blocked by `get_info`.
Resolves https://github.com/AntelopeIO/spring/issues/527
=> Move get_info off main thread and run in http thread

package.cmake, scripts/postinst, scripts/prerm
Remove use of deprecated python `distutils`.
Resolves #781
=> Remove use of deprecated python distutils

plugins/chain_api_plugin/chain_api_plugin.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp, plugins/chain_plugin/include/eosio/chain_plugin/tracked_votes.hpp, plugins/chain_plugin/tracked_votes.cpp, plugins/http_plugin/http_plugin.cpp, plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp, tests/chain_plugin_tests.cpp, tests/get_producers_tests.cpp, tests/get_table_seckey_tests.cpp, tests/get_table_tests.cpp, tests/test_chain_plugin.cpp
The chain_api_plugin does extra processing to support `v1/chain/get_finalizer_info` http endpoint. If the http `chain_ro` category is not enabled then there is no need to do the extra processing.
Resolves https://github.com/AntelopeIO/spring/issues/515
=> Enable tracked_votes processing only if http chain_ro category is configured

plugins/chain_plugin/get_info_db.cpp
at least libstdc++ 14 complains about usage of these deprecated in c++20 (and removed in c++26) functions. Since this file is small enough, just silence deprecations in it for now until libc++ adds this in the future.
```
plugins/chain_plugin/get_info_db.cpp:144:15: warning: 'atomic_store<eosio::chain_apis::get_info_db::get_info_results>' is deprecated: use 'std::atomic<std::shared_ptr<T>>' instead [-Wdeprecated-declarations]
144 |          std::atomic_store(&info_cache, info);  // replace current cache safely
|               ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/shared_ptr_atomic.h:181:5: note: 'atomic_store<eosio::chain_apis::get_info_db::get_info_results>' has been explicitly marked deprecated here
181 | …
```
=> silence atomic_*<shared_ptr> warnings in recent libstdc++

tests/disaster_recovery_2.py
A couple of `assert`'s F-string error text miss the front `f`. This PR fixes them.
=> Fix the missing f in f-strings of assert text

libraries/chain/finality/finalizer.cpp, libraries/chain/include/eosio/chain/abi_serializer.hpp, libraries/chain/include/eosio/chain/finality/finalizer.hpp, libraries/libfc/include/fc/io/raw.hpp, libraries/libfc/include/fc/reflect/variant.hpp, libraries/libfc/test/io/test_raw.cpp, libraries/testing/tester.cpp, tests/test_chain_plugin.cpp, unittests/eosio_system_tester.hpp, unittests/finalizer_vote_tests.cpp
Resolves #796.
Some types are only set in the constructor and never modified. So they are logically const and could be accessed from multiple threads safely.
Using this would allow us to remove some friend declarations (we use private as a way to prevent unchecked access to non thread-safe members).
Ideally we would make the member type const.
The serialization is what trips us up. I feel that the unpack functions in raw.hpp should accept to unpack const members of structs (logically deserializing to recreate a value which is never modified after creation). Right now we cannot mark non-funadamental types that needs to be serialized const.
Also added a test.
=> Update `raw.hpp` so that we can serialize and deserialize `const` types

plugins/chain_plugin/get_info_db.cpp
In `IRREVERSIBLE` read mode, it is expected `get_info` to return the same `head_block_num` and `last_irreversible_block_num`.  But a `get_info` request can come between `accepted_block` signal and `irreversible_block` signal, which results in inconsistencies.
A solution is not storing `get_info` results on `accepted_block` signal, but storing only on `irreversible_block` signal.
Resolves https://github.com/AntelopeIO/spring/issues/935
=> Do not store get_info results on accepted_block signal when read_mode is IRREVERSIBLE

.gitmodules, CMakeLists.txt, CMakeModules/EosioTesterBuild.cmake.in, libraries/libfc/libraries/boringssl/CMakeLists.txt
When we added boringssl the only way to integrate it without requiring golang was to commit generated files in to the repository. This is quite the horror to me because it makes it difficult for anyone (including ourselves) to check that the generated files haven't been tampered with by whoever committed them. To try and mitigate that, the repo we store the generated files in (https://github.com/AntelopeIO/boringssl-build) contains a workflow to double check the committed files by generating them itself using golang etc. Still very undesirable though.
A handful of months ago boringssl modified their build structure so that golang was no longer required to use the cmake files. And, astonishingly, it Just Works even in our use case.
This is a big deal. It makes it trivial for anyone …
=> use boringssl's upstream directly; removes need for our fork and committed generated files

plugins/net_plugin/net_plugin.cpp
For large `sync-fetch-span`, shutdown can be slow as there can be many queued up blocks to process on the dispatcher strand. Check for `app().is_quitting()` for faster shutdown. This provides a noticable improvement in response to ctrl-c shutdown request.
Related to #922
=> P2P: Check for is_quitting() for faster shutdown

libraries/chain/controller.cpp
When there are many blocks in the fork database, it is nice to know how many are going to be applied so the user knows what is happening.
=> Logging: On startup log number of blocks to be applied from the fork db

plugins/http_plugin/http_plugin.cpp, plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp, plugins/http_plugin/tests/unit_tests.cpp
Update flakey http plugin unit test. Backport of #943.
Didn't realize the test had failed in CI/CD, thought it was only failing on my machine.
Resolves #683
=> [1.0.3] Test: Update flakey http plugin unit test

plugins/trace_api_plugin/store_provider.cpp, plugins/trace_api_plugin/test/test_trace_file.cpp
I was concerned about the performance of `block_has_trx`.
Review comments for #966
=> Review: Alternative implementation of handling forking

tests/TestHarness/Node.py, tests/production_pause_max_rev_blks_test.py
Add a better method for waiting for LIB to stop advancing.
Resolves #955
=> [1.0.3] Test: Fix flakey production_pause_max_rev_blks_test

plugins/trace_api_plugin/store_provider.cpp, plugins/trace_api_plugin/test/test_trace_file.cpp
Trace_API's `get_transaction_trace` is supposed to return the transaction trace of a transaction. But the current implementation only finds any block whose block number matches the first block proposing the transaction; this block might not contains the transaction due to forking.
This PR
* adds a test reproducing the problem and a test for normal case.
* fixes the problem by not updating `trx_block_num` in `get_trx_block_number` if the block does not include the transaction.
Resolves https://github.com/AntelopeIO/spring/issues/942
=> [1.0.3] Trace_API: Fix get_transaction_trace endpoint fails to return transaction trace if the initial block including the transaction forks out

tests/TestHarness/Node.py, tests/production_pause_max_rev_blks_test.py
Add a better method for waiting for LIB to stop advancing.
Merges `release/1.0` into `main` including #960 
Resolves #955
=> [1.0.3 -> main] Test: Fix flakey production_pause_max_rev_blks_test

libraries/chain/webassembly/runtimes/eos-vm-oc/executor.cpp, libraries/chain/webassembly/runtimes/eos-vm.cpp
When stepping through eos-vm code, I noticed some incorrect `static_cast` and `std::move` usages, which don't seem to hide bugs because these functions are called with references which are afterwards unused. Still this seems worthwhile fixing imo.
I linked this PR to issue #958, since these changes came to mind when investigating that issue, but this PR doesn't resolve the issue (that would be PR #965 )
=> Replace `static_cast` of forwarding references with `std::forward`

.clang-format
This PR adds to the repo the `.clang_format` that Kevin and I have been using to format small pieces of new or updated code. Use as you see fit.
=> Add `.clang_format` file.

plugins/prometheus_plugin/metrics.hpp
Update the speculative block metrics for produced blocks.
Resolves #956
=> [1.0.3] Prometheus: Update speculative block metrics for produced blocks

plugins/prometheus_plugin/metrics.hpp
Update the speculative block metrics for produced blocks.
Merges `release/1.0` into `main` including #957
Resolves #956
=> [1.0.3 -> main] Prometheus: Update speculative block metrics for produced blocks

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/vote_processor.hpp, plugins/test_control_api_plugin/test_control_api_plugin.cpp, plugins/test_control_plugin/include/eosio/test_control_plugin/test_control_plugin.hpp, plugins/test_control_plugin/test_control_plugin.cpp, tests/CMakeLists.txt, tests/TestHarness/Node.py, tests/nodeos_signal_throw_test.py, unittests/vote_processor_tests.cpp
Adds new integration test that thows in all controller signals. It verifies that non-`controller_emit_signal_exception` exceptions are caught and dropped and that `controller_emit_signal_exception` shuts down the node in a state where it can be restarted. `test_control_plugin` updated with `/v1/test_control/throw_on` endpoint for allowing external triggers of exceptions on signals.
Includes a fix for reverting `chain_head` if `accepted_block` throws. This caused nodeos not to be able to restart as the `chain_head` did not match the chainbase state.
Includes a fix for `applied_transaction` throwing and shutting down nodeos.
Includes a fix for `vote_signal` throwing and shutting down nodeos.
Looking for opinions on if this PR should be backported to `release/1.0`
Resolves #946
=> Handle exceptions in controller signals

tests/plugin_http_api_test.py
I target this PR to `release/1.0` as it corrects 2 issues in `plugin_http_api_test` but does not touch non-tests code.
`plugin_http_api_test` gets stuck sometimes. This is caused by producer API related tests, where after `pause` and `resume` tests, `update_runtime_options` test modifies `max_irreversible_block_age` to 1 second which causes producer plugin to be stuck in speculative mode.
The PR
* restores options modified by `update_runtime_options` test to default values afterwards
* in addition to fixing the stuck problem, removes `max_scheduled_transaction_time_per_block_ms` and `incoming_defer_ratio` from `update_runtime_options` test  as those options were already removed in Leap 5.0.
Resolves https://github.com/AntelopeIO/spring/issues/992
Detailed log showing the problem:
```
info …
```
=> [1.0.4] Fix stuck plugin_http_api_test

tests/plugin_http_api_test.py
Forwards https://github.com/AntelopeIO/spring/pull/1007
`plugin_http_api_test` gets stuck sometimes. This is caused by producer API related tests, where after `pause` and `resume` tests, `update_runtime_options` test modifies `max_irreversible_block_age` to 1 second which causes producer plugin to be stuck in speculative mode.
The PR
* restores options modified by `update_runtime_options` test to default values afterwards
* in addition to fixing the stuck problem, removes `max_scheduled_transaction_time_per_block_ms` and `incoming_defer_ratio` from `update_runtime_options` test  as those options were already removed in Leap 5.0.
Resolves https://github.com/AntelopeIO/spring/issues/992
Detailed log showing the problem:
```
info  2024-10-30T14:16:59.920 nodeos    producer_plugin.cpp:1650 …
```
=> [1.0.4 -> main] Fix stuck plugin_http_api_test

libraries/chain/controller.cpp, unittests/fork_db_tests.cpp
When syncing under Savanna it is common for pending LIB to be greater than head. `log_irreversible` updates the block log and fork db root by the range of blocks from root->LIB when head is in root->LIB. Since LIB can be greater than head this would result in `forkdb.fetch_branch` returning an empty branch since searching back from head would not find the LIB causing large delays in the advancement of root.
Update `log_irreversible` to fetch branch from root->head when LIB is greater than head and head is in root->head.
Merges `release/1.0` into `main` including #1009 
Resolves #1003
=> [1.0.4 -> main] Advance fork db root when pending lib greater than head

libraries/chain/webassembly/runtimes/eos-vm.cpp
Add details to `wasm_execution_error` message.
Should provide additional insight into what is causing #425
=> Add details to wasm_execution_error

.github/workflows/build.yaml
EOS VM interpreter is slow. Sanitizer builds are slow. The two combined is _really_ slow and we've fought CI test timeouts on and off with that combo.
EOS VM interpreter isn't useful for production usage so maybe just go ahead and disable the `unit_test` and `wasm_spec_test` runs with EOS VM interpreter for ASAN & UBSAN builds in CI.
Will resolve #958.
=> [1.0.4] skip EOS VM interpreter parallel unit_tests and spec_tests on sanitizer builds

libraries/chain/controller.cpp
Before the change:
```
info  2024-11-07T23:18:21.438 nodeos    controller.cpp:1725           replay_block_log     ] 500 of 4983
info  2024-11-07T23:18:21.552 nodeos    controller.cpp:3566           log_applied          ] Received block 733efdcdfaeda3e0... #1000 @ 2024-  11-07T22:42:35.500 signed by eosio [trxs: 0, lib: 999, net: 0, cpu: 100 us, elapsed: 74 us, applying time: 188 us, latency: 2146052 ms]
info  2024-11-07T23:18:21.552 nodeos    controller.cpp:1725           replay_block_log     ] 1000 of 4983
info  2024-11-07T23:18:21.667 nodeos    controller.cpp:1725           replay_block_log     ] 1500 of 4983
info  2024-11-07T23:18:21.781 nodeos    controller.cpp:3566           log_applied          ] Received block d9216020d5998767... #2000 @ 2024-  11-07T22:50:55.500 signed by eosio …
```
=> Remove redundant log output and prometheus metrics update during replay

libraries/chain/controller.cpp, tests/interrupt_trx_test.py
Noticed the following warning.
```
^Cinfo  2024-11-08T13:04:40.741 nodeos    main.cpp:193                  operator()           ] appbase quit called
info  2024-11-08T13:04:40.741 nodeos    controller.cpp:4536           interrupt_transactio ] Interrupting apply block
info  2024-11-08T13:04:40.742 nodeos    controller.cpp:3820           apply_block          ] Interrupt of trx id: e6175b672d97e3f0110d70466c6c65d27f8cd2a5fc344d7efbe5a3e7c59090f5
info  2024-11-08T13:04:40.742 nodeos    controller.cpp:4464           operator()           ] interrupt while applying block 398678346 : 17c3594aee3d06f3d51e01c5afbe6c18d3216298d870cdfb9c79264cdcb6049d
warn  2024-11-08T13:04:40.754 nodeos    controller.cpp:4385           apply_blocks         ] 3030000 block_validate_exception: Block exception
attempt …
```
=> Do not unwind validated blocks on interrupt

unittests/contracts/jumborow/CMakeLists.txt, unittests/contracts/jumborow/jumborow.wast
When `EOSIO_COMPILE_TEST_CONTRACTS` is set, regenerate the wasm from the wast using cdt tooling.
=> regenerate jumborow.wasm when `EOSIO_COMPILE_TEST_CONTRACTS` enabled

libraries/chain/controller.cpp, plugins/producer_plugin/producer_plugin.cpp
`start_block` was returned `failed` instead of `waiting_for_block` when `apply_block` returned `incomplete` processing of blocks. This resulted in a `warn` log message and a reschedule of block production instead of just waiting for processing to complete.
Also fixed `apply_block` to not return `incomplete` for a block that takes more than 500ms to validate.
Resolves #1002
=> Fix start_block to return correct return code for incomplete apply_block

libraries/chain/include/eosio/chain/exceptions.hpp, libraries/chain/snapshot_scheduler.cpp, libraries/libfc/include/fc/exception/exception.hpp, libraries/libfc/src/exception.cpp, libraries/testing/tester.cpp, plugins/http_plugin/include/eosio/http_plugin/macros.hpp, plugins/producer_api_plugin/producer_api_plugin.cpp, tests/chain_test_utils.hpp
Remove `fc::exception::dynamic_rethrow_exception`. To work correctly `dynamic_rethrow_exception` requires registration via `FC_REGISTER_EXCEPTIONS` which was never done for any of the `eosio::chain` defined exceptions.
Since this feature never has worked as expected for `eosio::chain` defined exceptions, remove it to avoid confusion.
Resolves #980
=> Remove fc dynamic_rethrow_exception

libraries/chain/include/eosio/chain/controller.hpp, plugins/net_plugin/net_plugin.cpp, plugins/producer_plugin/producer_plugin.cpp
On speculative, non-block-producer, nodes do not reject blocks from the future. This allows a speculative node to have a clock skew without it interfering with maintaining synchronization. Before, this change a clock skew of 7 seconds would cause a speculative node to reject a block. 
Note block producers still need to keep their clocks synchronized so they produce on time. Block producers will continue to reject blocks with timestamps >= 7 seconds in the future.
Resolves #239
=> Do not reject future blocks on speculative nodes

plugins/net_plugin/net_plugin.cpp
Only include peer connections that are currently connected in `peer connections` count in connection monitor log.
Before
`p2p client connections: 0/25, peer connections: 17/17, block producer peers: 0`
After
`p2p client connections: 0/25, peer connections: 11/17, block producer peers: 0`
Merges `release/1.0` into `main` including #1032
Resolves #1006
=> [1.0.4 -> main] P2P: Fix peer connections log output

plugins/net_plugin/net_plugin.cpp
Update `chain_info` on `accepted_block` signal since `chain_head` has changed. The sync logic needs up to date info of the state of the node. This normally doesn't cause an issue because under normal conditions the node would soon receive a `accepted_block_header` or `irreversible_block` signal which would update the `net_plugin` state.
Resolves #998
=> [1.0.4] P2P: Fix sync stuck corner case

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/net_plugin/net_plugin.cpp, plugins/producer_plugin/producer_plugin.cpp, tests/CMakeLists.txt, tests/distributed-transactions-test.py
With Savanna instant finality, there is now no longer a good reason to prevent speculative trx execution on irreversible nodes; so remove the restriction.
Changed the distributed transaction test to always run with speculative, head, and irreversible mode nodes.
Note to disable speculative trx execution on irreversible nodes (or any node), it now must be specified via `api-accept-transactions = false` and `p2p-accept-transactions = false`.
Modify syncing heuristic in `producer_plugin` to 5 minutes to match what is used in controller.
Resolves #1030
=> Support speculative trx execution in irreversible mode

tests/separate_prod_fin_test.py
It is possible for a block to not contain a `qc_extension` if the qc claim is the same as the previous block.
Resolves #1023
=> [1.0.4] Test fix: Allow for block to not have qc_extension

tests/separate_prod_fin_test.py
It is possible for a block to not contain a `qc_extension` if the qc claim is the same as the previous block.
Merges `release/1.0` into `main` including #1044 
Resolves #1023
=> [1.0.4 -> main] Test fix: Allow for block to not have qc_extension

.cicd/defaults.json
The latest `main` artifact has expired. We could go regenerate that, but nominally this should really be set to a released version.
=> [1.0.4] set cdt version used in CI to 4.1.x

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/fork_database.hpp, libraries/testing/include/eosio/testing/tester.hpp, libraries/testing/tester.cpp, plugins/chain_plugin/chain_plugin.cpp, plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp, plugins/net_plugin/net_plugin.cpp, plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp, plugins/producer_plugin/producer_plugin.cpp, plugins/test_control_plugin/CMakeLists.txt, plugins/test_control_plugin/include/eosio/test_control_plugin/test_control_plugin.hpp, plugins/test_control_plugin/test_control_plugin.cpp, programs/nodeos/main.cpp, tests/interrupt_trx_test.py, tests/trx_finality_status_forked_test.py, unittests/blocks_log_replay_tests.cpp, unittests/checktime_tests.cpp, unittests/fork_db_tests.cpp, unittests/restart_chain_tests.cpp, unittests/savanna_cluster.hpp
Provide a mechanism to auto recover from "poison" blocks. Poison blocks are blocks with transactions which take an unexpectedly long time to execute. Poison block validation will automatically be interrupted when a better block is received from the network. 
If a BP node, always produce when scheduled to do so. Interrupting any block validation in progress. This restores the old behavior of "drop late blocks". When a producer is scheduled to produce it will interrupt any validation in progress and produce on top of the previous block.
- For BP nodes, interrupt block validation when scheduled to produce
- Moved `producer_plugin` timer off the main thread executor and onto its own thread.
- Interrupt block validation when a new best head* is received from the network.
- Do not apply blocks …
=> Interrupt block validation on new best head

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/exceptions.hpp, plugins/net_plugin/net_plugin.cpp, plugins/producer_api_plugin/producer_api_plugin.cpp, plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp, plugins/producer_plugin/producer_plugin.cpp
Proposing to merge this to `main` now as it includes some nice refactors.
Add functionality for `/v1/producer/pause_at_block` without enabling it. Since it is an interface change, it will not be added until Spring 2.0.0. See PR #1057.
See #570
=> Refactor for pause_at_block functionality

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, plugins/producer_plugin/producer_plugin.cpp, unittests/database_tests.cpp
The startup of `producer_plugin` uses `fetch_block_by_number` to prime `on_irreversible_block` with LIB.
https://github.com/AntelopeIO/spring/blob/838e885908aaa1f19aff9aaf4433a6f7904e86cb/plugins/producer_plugin/producer_plugin.cpp#L1612-L1613
When running without a block log, `fetch_block_by_number` always returned `nullptr` for LIB.
Update `fetch_block_by_number` and `fetch_block_by_id` to find LIB in fork database.
Merges `release/1.0` into `main` including #1059. Adds commit 5c8ea40c65c12e1b4ff5466fc1d6710b5e4f3e56.
Resolves #1052
=> [1.0.4 -> main] Fix fetch block with no block log

libraries/chain/controller.cpp
Faster shutdown in response to ctrl-c/SIGINT/SIGTERM/SIGPIPE especially when syncing in irreversible mode.
Resolves #1053
=> [1.0.4] Fast shutdown in irreversible mode

tests/interrupt_trx_test.py
On shutdown the `interrupt_trx_test.py` sends a SIGTERM to all processes. The test timed out #1058 because the node was stuck trying to validate a block with an infinite transaction in it. The SIGTERM interrupted the block apply but there was a queued up process block which caused it to attempt the `apply_block` again. The fix for this is actually in #1064 which added a `check_shutdown()` to `should_terminate()`. With the `check_shutdown()` in `should_terminate()`, the node will check the `app().is_quitting()` before attempting to apply a block. This prevents it from attempting to apply a block that was interrupted via SIGTERM which sets the `app().is_quitting()` flag.
Also added to the test a verification that head is advancing before verifying that LIB is advancing as a clearer …
=> On interrupt do not attempt to apply blocks

tests/TestHarness/Node.py, tests/disaster_recovery_2.py, tests/disaster_recovery_3.py, tests/nodeos_forked_chain_test.py
Modify python integration test `Node.waitForBlock` to wait on `blockNum` instead of `blockNum+1`.
Resolves #1055
=> Test: Update waitForBlock

libraries/chain/controller.cpp
before,
```
Produced block 6523a6c556abae06... #2026 @ 2024-12-18T16:48:47.000 signed by eosio [trxs: 5, lib: 2025, confirmed: , confirmed: 0, net: 800, cpu: 760 us, elapsed: 679 us, producing time: 462528 us]
```
after,
```
Produced block 2c0550043bdc520e... #3080 @ 2024-12-18T16:58:38.500 signed by eosio [trxs: 6, lib: 3079, confirmed: 0, net: 960, cpu: 804 us, elapsed: 604 us, producing time: 462454 us]
```
=> fix 'Produced block' log pre-Savanna

tests/TestHarness/Cluster.py, tests/distributed-transactions-test.py
Since `distributed-transactions-test.py` running with `--activate-if` has an `irreversible` node, wait for finalization of distributed funds before validation.
Test instability seems to have been caused by the combination of #1068 and #1036.
#1068 - Changed `waitForBlock` to not wait on an extra block.
#1036 - Changed `distibuted-transactions-test.py` to have an `irreversible` node when `--activate-if`.
Resolves #1078
=> Test: Wait for finalization to verify fund transfers

tests/plugin_http_api_test.py
Fix `plugin_http_api_test.py` to keep logs when the test fails.
Note: `unittest.TestResult().wasSuccessful()` always returns `True` even when a test fails.
This doesn't really resolve #1079 but without this fix there are no logs to determine what went wrong. We can create a new issue if/when it fails again.
Resolves #1079
=> Test: plugin_http_api_test correctly handle keeping logs when a test fails

libraries/chain/controller.cpp
- Return `apply_blocks` result in irreversible mode so incomplete apply is handled correctly.
- Handle interrupt in irreversible mode without logging an error.
Test failed because irreversible mode nodeos would not transition to Savanna. It would not transition because the `log_irreversible` was incomplete but nothing called `apply_blocks` again to continue the process.
Resolves #1082
=> Irreversible mode improvements

plugins/net_plugin/net_plugin.cpp
- Send all messages including blocks and votes over transactions. This prevents large trxs or large number of trxs from delaying block or vote propagation. 
- Includes a fix for `buffer_queue.out_callback()` called before `clear_out_queue()`. Long standing bug where the callbacks were never called because they were cleared before being called.
- Do not post `async_write` to connection strand as the call is already on the connection strand.
- Move serialization of votes off the main thread.
Resolves #1071
=> P2P: Prioritize blocks, votes, and all messages over trxs

unittests/checktime_tests.cpp
On a fast Zen5 CPU, I see spurious failures on this line about 5% of the time (the action completes faster than 8ms resulting in the exception not firing). Reducing the limit to 6ms resolves the problem. But this is rather fragile and has been tweaked a number of times in the past. Since the purpose of this first action is to just get the contract cached, why not run a simple action that is guaranteed to pass to prime the cache?
=> relax `checktime_hashing_fail` contract caching timing to eliminate spurious test failures

libraries/libfc/include/fc/io/raw.hpp, libraries/libfc/test/io/test_raw.cpp
This PR fixes a number of `unpacking()` issues:
1. `std::optional`: the target is not reset if the source does not have a value. This will causes mismatch of source and target if the target already has a value, as that value is kept.
2. `std::shared_ptr`: the target is not reset if the source is null_ptr.
3. `std::set`: the target is not set to empty if the source is empty, and the target is not clear if the source is not empty ending up with elements from both source and target.
4. `std::list`: the target is not set to empty if the source is empty, and the target is not clear if the source is not empty ending up with elements from both source and target.
The PR adds comprehensive tests for packing/unpacking `std::optional`, `std::shared_ptr`, `std::set`, and `std::list`.
Resolves …
=> Fix upacking() issues for std::optional, std::shared_ptr, std::set, and std::list

plugins/net_plugin/net_plugin.cpp
The duplication logic for P2P connections was overly complicated. The `node_id` should be more than sufficient to distinguish between two connections.
Resolves #1092
=> P2P: Fix duplication connection logic

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/platform_timer.hpp, libraries/chain/include/eosio/chain/transaction_context.hpp, libraries/chain/include/eosio/chain/wasm_interface_private.hpp, libraries/chain/platform_timer_accuracy.cpp, libraries/chain/platform_timer_asio_fallback.cpp, libraries/chain/platform_timer_kqueue.cpp, libraries/chain/platform_timer_posix.cpp, libraries/chain/transaction_context.cpp, libraries/chain/webassembly/runtimes/eos-vm.cpp, plugins/producer_plugin/producer_plugin.cpp, tests/nodeos_high_transaction_test.py, tests/nodeos_retry_transaction_test.py
The support for interrupting transaction on new best head, #1047, has a race condition such that an interrupt could interrupt a speculative transaction instead of a transaction in apply block. This would cause the transaction to fail and not be re-tried on the node. 
This PR refactors the `platform_timer` to keep track if it was trigger by an explicit interrupt or by the timer timing out. This allows for `transaction_context::checktime` to directly tell if a transaction was interrupted and raise an appropriate interrupt exception. If a transaction is interrupted it can then be retried similar to how a transaction is retried if it hits a block boundary.
Resolves #1095
=> Fix interrupt transaction race condition

libraries/chain/controller.cpp, programs/cleos/main.cpp
- Report `cpu_usage_us` and `net_usage_words` as `0` in read-only transaction trace receipt.
- Rational: read-only transactions are only executed locally on an API node. They have no on-chain billable CPU or billable NET. Could argue that there should be no `receipt` for read-only transactions. However, it is likely that existing tooling is expecting `receipt` for transactions that do not fail.
- Modify `cleos` to report `elapsed` instead of `cpu` and `net` for read-only transactions.
- Remove `cleos` `warning: transaction executed locally, but may not be confirmed by the network yet` for read-only and dry-run transactions.
- Note this PR does keep the `net_usage` in the receipt for read-only transactions. Since this is not in the receipt, I thought it might be useful for a user to know …
=> Read-only transaction reporting

libraries/chain/include/eosio/chain/wasm_interface_private.hpp
This pause & restart of the billing timer occurs for _every_ action executed by OC. It's a substantial amount of overhead (calling in to the kernel twice and doing whatever overhead needed to manage the timer) to be burdened with for every single action. I think this was added because in 1.1 `consume_compile_thread_queue()` is a wee bit heavier than prior releases (because it needs to take a lock a couple of times; for every action :disappointed: ). But since the number of outstanding compiles is limited to OC compile threads, the time spent in there is still very low. It wouldn't surprise me if this pause/resume is alone consuming more unaccounted for time than the nominal execution of `consume_compile_thread_queue()`.
Noticed during work of #1119
=> don't pause billing timer when fetching EOS VM OC's `code_descriptor`

tests/trx_generator/main.cpp
The transaction generator, used in performance testing, default transaction expiration was set to 60 minutes. 60 minutes is the also the default maximum transaction expiration limit. Since the comparison is `<= pending_block_time` this can fail.
Changed the default to 30 minutes which is more than enough. Seems, any performance test that takes 30 minutes to get a transaction to execute should be considered a failure.
https://github.com/AntelopeIO/spring/blob/8cc52d9ad51e2f03f144d8de9afbcfb1476b4563/libraries/chain/controller.cpp#L5840-L5840
Resolves #1093
=> PH: Change default transaction generator trx expiration

.github/workflows/build.yaml, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/gs_seg_helpers.h, libraries/chain/webassembly/runtimes/eos-vm-oc/executor.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/gs_seg_helpers.c, tools/CMakeLists.txt, tools/fsgsbase-enabled.c, unittests/CMakeLists.txt
EOS VM OC uses the GS segment register for the base of its WASM memory. Prior to Linux 5.9 the only way to adjust the base address is via a syscall. For 5.9+, combined with modern CPUs (Intel Ivy Bridge+, 2012; AMD Bulldozer+, 2011), it's possible to instead use the `fsgsbase` instructions from userspace without needing to make a syscall. Switching to these instructions eliminates _at least_ one syscall per action, and oftentimes more for something like EVM. 
I ran a replay test over blocks 96328736-96627942 on an i7-12700K (Alder Lake, 2021). I saw a surprising ~3.5% improvement. This far exceeds my expectations (should have done this years ago). I was anticipating that only older CPUs subject to Meltdown would incur such heavy overhead on this seemingly simplistic syscall. What might …
=> enable `fsgsbase` instructions on Linux 5.9+ for EOS VM OC

libraries/chain/include/eosio/chain/wasm_interface_private.hpp
When I start from snapshot I can sometimes see this log once or twice. imo this ends up being deceptive because it looks like OC only tiered up 1 or 2 contracts (at least based on the current wording of the message). We already have another ilog a few lines down that logs when an interruption actually occurs. So, I don't really think we need this one.
=> remove a log message when OC compilation completes for running contract

libraries/chain/CMakeLists.txt, libraries/chain/wasm_interface.cpp, plugins/chain_plugin/chain_plugin.cpp, tests/read_only_trx_test.py
Synchronous EOS VM OC mode is only for development & testing use, but gating it behind a compile time option means automated testing systems (like chicken dance) can't simply just pull a built binary from CI and use this mode. Now allow synchronous EOS VM OC via `wasm-runtime=eos-vm-oc-forced` (will also need to set `eos-vm-oc-enable=off`). This `eos-vm-oc-forced` choice isn't documented anywhere and it's unlikely any normal user would stumble on it. Closes #1114
=> allow the dev&test synchronous EOS VM OC mode without adjusting a compile time option

libraries/chain/include/eosio/chain/platform_timer.hpp, libraries/chain/platform_timer_asio_fallback.cpp, libraries/chain/platform_timer_kqueue.cpp, libraries/chain/platform_timer_posix.cpp, libraries/chain/transaction_context.cpp
When passing `fc::time_point::max()` to `platform_timer::start()`, `platform_timer` recognizes that,
https://github.com/AntelopeIO/spring/blob/909603c103e81744c6898e18f48cbcd1a08e542f/libraries/chain/platform_timer_posix.cpp#L57-L62
and pretends the timer is running without actually starting the timer. Then when `stop()` is called it would still make a request to the kernel to stop the never started timer. There is nothing logically wrong with that, it's just a wasteful syscall that isn't needed that can end up happening thousands of times a second.
My memory was that historically when applying a block, `transaction_context::init()` would effectively `platform_timer::start(fc::time_point::max())`. That would result in the condition above and it's why I wrote #1119 worded the way it is. …
=> don't start kernel level platform timer when applying blocks

tests/TestHarness/Node.py
When `nodeos` is quickly relaunched in the integration tests, it is possible that a `nodeos` log file is overwritten because it has the same launch time and file name. This happens, for example, in `nodeos_read_terminate_at_block_test.py`. Make sure a unique log file name is created for each run of `nodeos`.
=> Test: Create unique log files for nodeos

libraries/chain/controller.cpp
During replay, under default conditions, no chainbase db sessions are active; therefore, do not allow interrupt of apply block. Also there is no use-case for interrupting an individual block during replay. With this PR, ctrl-c will interrupt replay between block applies.  
There is no use case for interrupting an individual apply from the block log. Any "infinite" or invalid block in the block log needs to be pruned manually since there would be no way to append on to the blocklog to bypass a block. Also we do not want to auto-truncate the blocklog when ctrl-c interrupts replay. Instead the expected use-case is to continue replay on restart.
Issue introduced by: https://github.com/AntelopeIO/spring/pull/993
Resolves #1125
=> Do not interrupt apply_block during replay

plugins/chain_plugin/chain_plugin.cpp
All other whitelist options are multi-token.  This PR changes `eos-vm-oc-whitelist` to also be multi-token.
Multi-token allows for multiple values to be specified for `--eos-vm-oc-whitelist`; e.g. `--eos-vm-oc-whitelist xsat other another`.
Note: if any `eos-vm-oc-whitelist` option is specified then `xsat` needs to be explicitly added. The default is overridden if any value is specified. For example, to add `other`, use `--eos-vm-oc-whitelist xsat other`.
The default value of `eos-vm-oc-whitelist` is `xsat`. If `xsat` is not desired, then an alternative must be specified. If there is a desire to not whitelist any accounts, then use `eosio.null` or any other account without a contract.
Also adds a logging of `eos-vm-oc-whiltelist` accounts on startup.
=> Make eos-vm-oc-whitelist option multitoken

plugins/net_plugin/net_plugin.cpp
When a connection is closed, any queued up sends to that connection are aborted. Logging these as `error` is confusing to users. 
Resolves #1138
=> P2P: Do not log expected conditions in send callback

benchmark/bls.cpp, libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/transaction_context.hpp, libraries/chain/include/eosio/chain/wasm_interface_private.hpp, libraries/chain/transaction_context.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/executor.cpp
Currently with #1027 a long running trx is interrupted when the oc compile completes. This causes an issue with deferred trx processing in old blocks where deferred trxs exist. Disable interrupt of transaction when oc compile completes for implicit transactions. Implicit transactions include deferred `onerror` and `onblock`. Not interrupting `onblock` seems like an ok thing here as `onblock` is part of the main system contract.
Also stop() timer on oc interrupt so start() is always called on a stopped timer.
Also call `checktime()` after setup of cleanup in eos-vm-oc so that `set_expiration_callback(nullptr, nullptr);` is called on `checktime` exception.
chicken-dance mismatch still on this branch which is being tracked by https://github.com/AntelopeIO/spring/issues/1152
Resolves #1145
=> [1.1.0] Fix deferred trx processing

benchmark/bls.cpp, libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/transaction_context.hpp, libraries/chain/include/eosio/chain/wasm_interface_private.hpp, libraries/chain/transaction_context.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/executor.cpp
Currently with #1027 a long running trx is interrupted when the oc compile completes. This causes an issue with deferred trx processing in old blocks where deferred trxs exist. Disable interrupt of transaction when oc compile completes for implicit transactions. Implicit transactions include deferred `onerror` and `onblock`. Not interrupting `onblock` seems like an ok thing here as `onblock` is part of the main system contract.
Also stop() timer on oc interrupt so start() is always called on a stopped timer.
Also call `checktime()` after setup of cleanup in eos-vm-oc so that `set_expiration_callback(nullptr, nullptr);` is called on `checktime` exception.
chicken-dance mismatch still on this branch which is being tracked by https://github.com/AntelopeIO/spring/issues/1152
Merges …
=> [1.1.0 -> main] Fix deferred trx processing

libraries/chain/block_log.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/block_log.hpp, plugins/chain_plugin/chain_plugin.cpp
Do not allow `--replay-blockchain` option without `--snapshot` option unless a full block log is available as it will fail and leave the blockchain in a non-recoverable state.
While attempting to reproduce #1152, I kicked off a `--replay-blockchain` but forgot to add the `--snapshot` option. I didn't have a full block log. This resulted in the following:
```
info  2025-02-08T13:32:56.675 nodeos    chain_plugin.cpp:778          plugin_initialize    ] Replay requested: deleting state database
info  2025-02-08T13:32:57.062 nodeos    chain_plugin.cpp:933          plugin_initialize    ] Starting fresh blockchain state using default genesis state.
...
info  2025-02-08T13:32:57.915 nodeos    listener.hpp:150              log_listening        ] start listening on 127.0.0.1:7777 resolved from …
```
=> [1.1.0] Do not allow replay-blockchain without snapshot

libraries/chain/block_log.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/block_log.hpp, plugins/chain_plugin/chain_plugin.cpp
Do not allow `--replay-blockchain` option without `--snapshot` option unless a full block log is available as it will fail and leave the blockchain in a non-recoverable state.
While attempting to reproduce #1152, I kicked off a `--replay-blockchain` but forgot to add the `--snapshot` option. I didn't have a full block log. This resulted in the following:
```
info  2025-02-08T13:32:56.675 nodeos    chain_plugin.cpp:778          plugin_initialize    ] Replay requested: deleting state database
info  2025-02-08T13:32:57.062 nodeos    chain_plugin.cpp:933          plugin_initialize    ] Starting fresh blockchain state using default genesis state.
...
info  2025-02-08T13:32:57.915 nodeos    listener.hpp:150              log_listening        ] start listening on 127.0.0.1:7777 resolved from …
```
=> [1.1.0 -> main] Do not allow replay-blockchain without snapshot

libraries/chain/transaction_context.cpp
Do not clear `bill_to_accounts` in `transaction_context::reset()` as `bill_to_accounts` is only modified during `transaction_context::init()`. This `clear()` was causing accounts to not be billed for CPU/NET when the transaction was interrupted by oc compile. This difference in recorded resource usage caused a difference in the integrity hash between a node that was interrupted vs one that was not.
Clean chicken-dance run with this PR.
Resolves #1152
=> [1.1.0] Fix account billing on eos-vm-oc interrupt

libraries/chain/transaction_context.cpp
Do not clear `bill_to_accounts` in `transaction_context::reset()` as `bill_to_accounts` is only modified during `transaction_context::init()`. This `clear()` was causing accounts to not be billed for CPU/NET when the transaction was interrupted by oc compile. This difference in recorded resource usage caused a difference in the integrity hash between a node that was interrupted vs one that was not.
Clean chicken-dance run with this PR.
Merges `release/1.1` into `main` including #1160 
Resolves #1152
=> [1.1.0 -> main] Fix account billing on eos-vm-oc interrupt

libraries/libfc/libraries/boringssl/CMakeLists.txt
boringssl's upstream cmake file always adds `-ggdb` to the compile which damages our reproducibility due to a path difference. We might want to rectify the path difference if possible and/or masquerade the difference via compiler options, but disabling the debug symbol generation is far easier by negating the `-ggdb` with `-g0`
=> [1.1.0] disable boringssl debug symbols on release builds; restore reproducible builds in CI

libraries/libfc/libraries/boringssl/CMakeLists.txt
=> [1.1.0 -> main] disable boringssl debug symbols on release builds; restore reproducible builds in CI

tests/TestHarness/launcher.py
The prior `max_transaction_cpu_usage` of 475ms allowed for very long running speculative transactions. These could cause delays which, in some cases, would be long enough for a test to timeout. See #1151 for details.
To avoid other possible differences in tests and real-world, set all genesis values of integration tests to the current EOS mainnet values.
https://eosauthority.com/account/eosio?network=eos&scope=eosio&table=global&limit=10&index_position=1&key_type=i64&reverse=0&mode=contract&sub=tables
| max\_block\_net\_usage | target\_block\_net\_usage\_pct | max\_transaction\_net\_usage | base\_per\_transaction\_net\_usage | net\_usage\_leeway | context\_free\_discount\_net\_usage\_num | context\_free\_discount\_net\_usage\_den | max\_block\_cpu\_usage | target\_block\_cpu\_usage\_pct | …
=> [1.1.0] Test: Use EOS mainnet chain values for integration tests

tests/TestHarness/launcher.py
The prior `max_transaction_cpu_usage` of 475ms allowed for very long running speculative transactions. These could cause delays which, in some cases, would be long enough for a test to timeout. See #1151 for details.
To avoid other possible differences in tests and real-world, set all genesis values of integration tests to the current EOS mainnet values.
https://eosauthority.com/account/eosio?network=eos&scope=eosio&table=global&limit=10&index_position=1&key_type=i64&reverse=0&mode=contract&sub=tables
| max\_block\_net\_usage | target\_block\_net\_usage\_pct | max\_transaction\_net\_usage | base\_per\_transaction\_net\_usage | net\_usage\_leeway | context\_free\_discount\_net\_usage\_num | context\_free\_discount\_net\_usage\_den | max\_block\_cpu\_usage | target\_block\_cpu\_usage\_pct | …
=> [1.1.0 -> main] Test: Use EOS mainnet chain values for integration tests

tests/TestHarness/Node.py, tests/lib_advance_test.py
`lib_advance_test` checks number of unlinkable blocks in `stderr.txt` to decide whethere the test fails or not. It scans `stderr.txt`, inserts any `unlinkable_block` it finds into a list, and uses the number of elements in the list as the number of unlinkable blocks. But the same unlinkable block can appear in `stderr.txt` multiple times due to multiple connections or repeated syncing:
```
debug 2025-02-10T18:01:07.023 net-3     net_plugin.cpp:3967           operator()           ] unlinkable_block 174 : 000000aedde07ade58031c2926de9c9ead20c35025d53ea973e50841c71504b0, previous 173 : 000000ad3ccc782661621ba4ea215907e103efaa8fe29b737a9c7910c118fed9
...
debug 2025-02-10T18:01:07.025 net-3     net_plugin.cpp:3967           operator()           ] unlinkable_block 174 : …
```
=> [1.1.x] Test: Determine the failure of lib_advance_test using the number of unique unlinkable blocks

tests/TestHarness/Node.py, tests/lib_advance_test.py
`lib_advance_test` checks number of unlinkable blocks in `stderr.txt` to decide whethere the test fails or not. It scans `stderr.txt`, inserts any `unlinkable_block` it finds into a list, and uses the number of elements in the list as the number of unlinkable blocks. But the same unlinkable block can appear in `stderr.txt` multiple times due to multiple connections or repeated syncing:
```
debug 2025-02-10T18:01:07.023 net-3     net_plugin.cpp:3967           operator()           ] unlinkable_block 174 : 000000aedde07ade58031c2926de9c9ead20c35025d53ea973e50841c71504b0, previous 173 : 000000ad3ccc782661621ba4ea215907e103efaa8fe29b737a9c7910c118fed9
...
debug 2025-02-10T18:01:07.025 net-3     net_plugin.cpp:3967           operator()           ] unlinkable_block 174 : …
```
=> [1.1.0 -> main] Test: Determine the failure of lib_advance_test using the number of unique unlinkable blocks

.cicd/defaults.json, .github/workflows/build.yaml
Resolves #1177.
Now that we are not updating the `reference-contracts` repo anymore, switch the libtester tests to using `eos-system-contracts`.
This reverts commit 3fdc35407f9eb3ee2b08e4982052629123a5ce6a.
=> Switch to using `eos-system-contracts` in libtester tests

plugins/net_plugin/net_plugin.cpp
Reverts #1108 
The simplified de-dup logic of #1108 allows for both sides to determine the other is duplicate if the connections happen at the same time. The previous more complicated logic does allow duplicate connections in about half the cases, but prevents the race-condition of both sides deciding the other is a duplicate.
I wonder with the new block-nack feature and future limit of connections if we should even attempt to remove duplicate connections. In one sense, it seems like if a user wants to configure both sides to connect to each other that we should just allow it. It is obviously an important connection. Also all the reconnects and determination of duplicate and disconnect is in itself wasteful.
Note the previous version support here is not really needed, but just kept this …
=> [1.1.1] Revert "P2P: Fix duplication connection logic #1108"

plugins/net_plugin/net_plugin.cpp
Reverts #1108 
The simplified de-dup logic of #1108 allows for both sides to determine the other is duplicate if the connections happen at the same time. The previous more complicated logic does allow duplicate connections in about half the cases, but prevents the race-condition of both sides deciding the other is a duplicate.
I wonder with the new block-nack feature and future limit of connections if we should even attempt to remove duplicate connections. In one sense, it seems like if a user wants to configure both sides to connect to each other that we should just allow it. It is obviously an important connection. Also all the reconnects and determination of duplicate and disconnect is in itself wasteful.
Note the previous version support here is not really needed, but just kept this …
=> [1.1.1 -> main] Revert "P2P: Fix duplication connection logic

tests/block_log.cpp
Fix
```
tests/block_log.cpp:655:26: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
655 |    for(unsigned i = 0; i < prune_blocks*3; ++i)
```
Resolves https://github.com/AntelopeIO/spring/issues/1191
=> [1.1.1] Fix a warning of comparison of integer expressions of different signedness in nonprune_to_prune_on_start test

libraries/chain/controller.cpp
- Include proposer name in `switching forks` log message.
- Log when a proposer double produced blocks which caused a local fork switch.
Merges `release/1.1` into `main` including #1187
=> [1.1.1 -> main] Log double produced blocks on fork switch

plugins/chain_api_plugin/chain_api_plugin.cpp, tests/plugin_http_api_test.py
`get_info` was mistakenly removed from `node` category (https://github.com/AntelopeIO/spring/pull/920) and caused it not available on non-chain API endpoints
This PR
* Moves it back to `node` category
* Fixes a bug of `plugin_http_api_test` that it does not exit with an exit value. That causes `plugin_http_api_test` to always appear successful even though it fails
* Add a test of `get_info` on non-chain API endpoint
Resolves https://github.com/AntelopeIO/spring/issues/1194
=> [1.1.1] Fix get_info available on non-chain API endpoints

plugins/chain_api_plugin/chain_api_plugin.cpp, tests/plugin_http_api_test.py
`get_info` was mistakenly removed from `node` category (https://github.com/AntelopeIO/spring/pull/920) and caused it not available on non-chain API endpoints
This PR
* Moves it back to `node` category
* Fixes a bug of `plugin_http_api_test` that it does not exit with an exit value. That causes `plugin_http_api_test` to always appear successful even though it fails
* Add a test of `get_info` on non-chain API endpoint
Merges release/1.1 into main including https://github.com/AntelopeIO/spring/pull/1195
Resolves https://github.com/AntelopeIO/spring/issues/1194
=> [1.1.1 -> main] Fix get_info not available on non-chain API endpoints

tests/trace_plugin_test.py
Fix the issue that `trace_plugin_test` fails to keep log file if the test fails.
Resolves https://github.com/AntelopeIO/spring/issues/1198
=> [1.1.1] Fix log file not kept by trace_plugin_test when the test fails

tests/trace_plugin_test.py
Fix the issue that `trace_plugin_test` fails to keep log file if the test fails.
Merges release/1.1 into main including https://github.com/AntelopeIO/spring/pull/1199
Resolves https://github.com/AntelopeIO/spring/issues/1198
=> [1.1.1 -> main] Fix log file not kept by trace_plugin_test when the test fails

plugins/net_plugin/net_plugin.cpp
`connection_start_time` accessed from connection strand and also from any net thread when Prometheus enabled.
=> [1.1.2] P2P, Prometheus: fix threading issue

plugins/net_plugin/net_plugin.cpp
`connection_start_time` accessed from connection strand and also from any net thread when Prometheus enabled. 
Merges `release/1.1` into `main` including #1204
=> [1.1.2 -> main] P2P, Prometheus: fix threading issue

plugins/net_plugin/net_plugin.cpp
- Add new options `_peer` and `_nver` to `peer-log-format`.
- `_peer` - The configured `p2p-peer-address` or reported address if incoming.
- `_nver` - The P2P network protocol version of the connection. e.g. 9 is `proto_savanna`, 10 is `proto_block_nack`.
- Changed the default to use `_peer` instead  of `_name` as `_peer` is easier to correlate with configured `p2p-peer-address`.
- Add log when not sending a block because connection is busy sending already.
=> P2P: Add new peer-log-format options

libraries/chain/controller.cpp, plugins/net_plugin/net_plugin.cpp
Optimize processing of incoming blocks by removing an unneeded thread hop on nominal case.
=> P2P: Avoid thread hop on incoming blocks

plugins/net_plugin/net_plugin.cpp
When responding to a block_notice for block nack feature, do not close the connection if the block is not available. Under normal circumstances the block should be available. However, if a fork switch makes the block(s) not available when sending, do not disconnect as this is "expected" during a fork switch.
Resolves #1224
=> [1.1.2] P2P: Do not close connection on block nack block_notice

plugins/net_plugin/net_plugin.cpp
When responding to a block_notice for block nack feature, do not close the connection if the block is not available. Under normal circumstances the block should be available. However, if a fork switch makes the block(s) not available when sending, do not disconnect as this is "expected" during a fork switch.
Merge `release/1.1` into `main` including #1226 
Resolves #1224
=> [1.1.2 -> main] P2P: Do not close connection on block nack block_notice

plugins/net_plugin/net_plugin.cpp
#688 introduced an incorrect handling of null connection when determining node catchup state.
Resolves #1239
=> [1.1.3] P2P: Fix node stuck in head catchup

.cicd/platforms/asan.Dockerfile, .cicd/platforms/ubsan.Dockerfile
It's that time again: update sanitizer builds to latest clang version. The premise is the latest version will have the best sanitizers.
There is a metric ton or two of compile warnings in boost on clang20; not much can do about that for now
=> bump sanitizers to clang20

programs/cleos/main.cpp, tests/compute_transaction_test.py
Apparently just an oversight this was only available on `push transaction` and not also `push action`
=> add `--dry-run` for `push action`

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/snapshot.hpp
Update the percentage log output of snapshot creation to report type of snapshot being created. Uses `integrity hash` for the integrity hash creation on startup and shutdown.
```
info  2025-03-24T18:04:19.004 nodeos    snapshot.hpp:457              progress             ] integrity hash creation 0% complete
info  2025-03-24T18:05:04.005 nodeos    snapshot.hpp:457              progress             ] integrity hash creation 7% complete
info  2025-03-24T18:05:20.612 nodeos    snapshot.hpp:457              progress             ] integrity hash creation 12% complete
info  2025-03-24T18:06:58.004 nodeos    snapshot.hpp:457              progress             ] integrity hash creation 26% complete
info  2025-03-24T18:07:15.242 nodeos    snapshot.hpp:457              progress             ] integrity …
```
=> Change log message when computing integrity hash

tests/TestHarness/Cluster.py, tests/TestHarness/transactions.py, tests/plugin_http_api_test.py
This is work on issue #1247.
I was not able to figure out why it seems that sometimes, we are missing one activated protocol feature.
This PR adds some debugging code to print out the missing feature when the issue occurs.
> note: Issue may have been present for a long time, but was hidden as a failure of the test to return an exit value caused it to always succeed (fixed in https://github.com/AntelopeIO/spring/pull/1195).
=> Fix incorrect names (`preActivate` instead of `activate`) and add debugging info

tests/nodeos_short_fork_take_over_test.py
During a fork-switch a block can be temporarily not available. Do not exit the test, but allow time for fork switch.
Resolves #1248
=> Test: Do not exit on error when evaluating fork

tests/production_pause_vote_timeout.py
The test failed because the `finacliercNode` was not synced up and voting on current blocks before the `node0` was killed. Modify the test to verify that `finalizercNode` is synced up and current before killing `node0`.
Resolves #1260
=> Test: Make sure finalizercNode is synced up before killing node0

libraries/chain/apply_context.cpp, libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/apply_context.hpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/platform_timer.hpp, libraries/chain/include/eosio/chain/sync_call.hpp, libraries/chain/include/eosio/chain/sync_call_context.hpp, libraries/chain/include/eosio/chain/transaction_context.hpp, libraries/chain/include/eosio/chain/wasm_interface.hpp, libraries/chain/include/eosio/chain/wasm_interface_private.hpp, libraries/chain/include/eosio/chain/webassembly/runtime_interface.hpp, libraries/chain/transaction_context.cpp, libraries/chain/wasm_interface.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc.cpp, libraries/chain/webassembly/runtimes/eos-vm.cpp, libraries/chain/webassembly/sync_call.cpp, tests/read_only_trx_test.py, unittests/protocol_feature_tests.cpp, unittests/sync_call_tests.cpp
This PR implements the core functionalities of sync calls, in particular the  `call` host function. The Unit tests show basic call flows are working:
* Sync calls whose receivers are the same as the senders
* Sync calls whose receivers are different from the senders
* Nested sync calls
* Recursive sync calls
* Sequential sync calls
Notes for reviewing:
* Please roughly follow the order of `libraries/chain/webassembly/sync_call.cpp`, `libraries/chain/apply_context.cpp` and `libraries/chain/webassembly/runtimes/eos-vm.cpp` to review
* `eosvm-oc` not working yet. https://github.com/AntelopeIO/spring/issues/1043  (sync call unit tests skip eosvm-oc)
* Please double check if `transaction_checktime_timer` related changes are correct
* Tests will be updated using return values and console output …
=> SC:  Implement the core functionalities of sync calls

tests/nodeos_short_fork_take_over_test.py
During a fork-switch a block can be temporarily not available. Do not exit the test, but allow time for fork switch.
Backports #1272 to `release/1.1` branch
Resolves #1248
=> [1.1.3] Test: Do not exit on error when evaluating fork

tests/production_pause_vote_timeout.py
The test failed because the `finacliercNode` was not synced up and voting on current blocks before the `node0` was killed. Modify the test to verify that `finalizercNode` is synced up and current before killing `node0`.
Backports #1274 to `release/1.1`
Resolves #1260
=> [1.1.3] Test: Make sure finalizercNode is synced up before killing node0

plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp, plugins/net_plugin/include/eosio/net_plugin/buffer_factory.hpp, plugins/net_plugin/net_plugin.cpp
- Use `send_buffer_type` consistently. 
- Avoid some `shared_ptr` copies.
=> Minor cleanup in `buffer_factory.hpp`

libraries/chain/apply_context.cpp, libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/apply_context.hpp, libraries/chain/include/eosio/chain/exceptions.hpp, libraries/chain/include/eosio/chain/sync_call_context.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/intrinsic_mapping.hpp, libraries/chain/include/eosio/chain/webassembly/interface.hpp, libraries/chain/webassembly/runtimes/eos-vm.cpp, libraries/chain/webassembly/sync_call.cpp, unittests/protocol_feature_tests.cpp, unittests/sync_call_tests.cpp
This PR implements the remaining sync call host functions. Basic sync call protocol level functionalities are in place. 
Unit test `basic_params_return_value_passing` shows a complete end to end sync call in WASM code using the host functions in the following steps
1. making a sync call, 
2. passing arguments, 
3. saving return value, 
4. retrieving return value
Resolves https://github.com/AntelopeIO/spring/issues/1215
=> SC: Implement `get_call_data`, `set_call_return_value` and `get_call_data` host functions

libraries/chain/controller.cpp
Interrupt of `onblock` transaction in apply block was not handled correctly. The `onblock` would fail, but would not abort the block. Validation would then fail causing a node to be stuck.
Resolves #1306
=> [1.1.3] Correctly handle onblock interrupt

libraries/chain/controller.cpp
Interrupt of `onblock` transaction in apply block was not handled correctly. The `onblock` would fail, but would not abort the block. Validation would then fail causing a node to be stuck.
Merges `release/1.1` into `main` including #1307 
Resolves #1306
=> [1.1.3 -> main] Correctly handle onblock interrupt

tests/nodeos_short_fork_take_over_test.py
The test tried to time killing the bridge node at the last block of the round. There is no need to be that exact. Kill near the end of `defproducerb` without trying to hit the last block of the round.
Resolves #1301
=> [1.1.3] Test fix: Kill node before end of defproducerb to allow more tolerance

tests/TestHarness/queries.py, tests/nodeos_short_fork_take_over_test.py
Improve handling of `exitOnError=False` when block not available.
Resolves #1304
=> [1.1.3] Test fix: Better handle case where block not available

tests/TestHarness/queries.py, tests/nodeos_short_fork_take_over_test.py
Improve handling of `exitOnError=False` when block not available.
Merges `release/1.1` into `main` including #1305
Resolves #1304
=> [1.1.3 -> main] Test fix: Better handle case where block not available

libraries/chain/CMakeLists.txt, libraries/chain/apply_context.cpp, libraries/chain/include/eosio/chain/apply_context.hpp, libraries/chain/include/eosio/chain/exceptions.hpp, libraries/chain/include/eosio/chain/sync_call_context.hpp, libraries/chain/include/eosio/chain/wasm_interface.hpp, libraries/chain/include/eosio/chain/wasm_interface_private.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm.hpp, libraries/chain/include/eosio/chain/webassembly/interface.hpp, libraries/chain/include/eosio/chain/webassembly/runtime_interface.hpp, libraries/chain/sync_call_context.cpp, libraries/chain/wasm_interface.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc.cpp, libraries/chain/webassembly/runtimes/eos-vm.cpp, libraries/chain/webassembly/sync_call.cpp, unittests/protocol_feature_tests.cpp, unittests/sync_call_tests.cpp
Implement this feature earlier to help prevent errors in WASM test contracts.
* Before a contract is inserted into `wasm_instantiation_cache`, check if `sync_call` entry point is  present in the contract; if present, validate the signature. Set `receiver_supports_sync_call` flag of the cache entry accordingly.
* When a sync call is made, check `receiver_supports_sync_call` of the receiver. If `false`, return `-1` and let the caller decide what to do about the failure.
* Tests are added for those validation.
Resolves  https://github.com/AntelopeIO/spring/issues/1219
=> SC: Validate sync call entry point

unittests/sync_call_tests.cpp
Three tests are added by the PR:
1. A sync call not passing any parameters --`get_call_data()` should return `0`
2. A sync call not returning a value (like a `void func()`) -- `get_call_return_value()` should return `0`
3. A sync call returning a 0-length value (like returning an empty string) -- `get_call_return_value()` should return `0`
Resolves https://github.com/AntelopeIO/spring/issues/1297
=> SC: Tests for sync calls without parameters, not returning a value, or returning a 0-length value

libraries/chain/transaction_context.cpp, tests/TestHarness/Cluster.py, tests/read_only_trx_test.py
See https://github.com/AntelopeIO/spring/issues/1151#issuecomment-2660193692 for a detailed discussion of the test failure scenario.
Looks like https://github.com/AntelopeIO/spring/pull/1172 didn't change all tests to use mainnet values. Some still run with 475ms trx time.
Ideally it would be nice to run ci/cd with EOS Mainnet values for `max_block_cpu_usage` and `max_transaction_cpu_usage`. However, this puts us in a situation where tests will be flakey because transactions hit the time limit. See for example: 
https://github.com/AntelopeIO/spring/actions/runs/14131407538/job/39593258845
https://github.com/AntelopeIO/spring/actions/runs/14131407538/job/39593259641
https://github.com/AntelopeIO/spring/actions/runs/14131694179/job/39594280368
This PR reduces the value to something …
=> [1.1.3] Test fix: Decrease max_block_cpu_usage and max_transaction_cpu_usage values

plugins/net_plugin/include/eosio/net_plugin/protocol.hpp, plugins/net_plugin/net_plugin.cpp, tests/auto_bp_peering_test.py
Fix for an issue where `net_plugin` would allow some duplicate connections to remain open.
Simplified to just checking both incoming and outgoing connections for duplicate.
Resolves #1255
=> Eliminate duplicate P2P connections

libraries/chain/transaction_context.cpp, tests/TestHarness/Cluster.py, tests/read_only_trx_test.py
See https://github.com/AntelopeIO/spring/issues/1151#issuecomment-2660193692 for a detailed discussion of the test failure scenario.
Looks like https://github.com/AntelopeIO/spring/pull/1172 didn't change all tests to use mainnet values. Some still run with 475ms trx time.
Ideally it would be nice to run ci/cd with EOS Mainnet values for `max_block_cpu_usage` and `max_transaction_cpu_usage`. However, this puts us in a situation where tests will be flakey because transactions hit the time limit. See for example: 
https://github.com/AntelopeIO/spring/actions/runs/14131407538/job/39593258845
https://github.com/AntelopeIO/spring/actions/runs/14131407538/job/39593259641
https://github.com/AntelopeIO/spring/actions/runs/14131694179/job/39594280368
This PR reduces the value to something …
=> [1.1.3 -> main] Test fix: Decrease max_block_cpu_usage and max_transaction_cpu_usage values

libraries/chain/apply_context.cpp, libraries/chain/host_context.cpp, libraries/chain/include/eosio/chain/apply_context.hpp, libraries/chain/include/eosio/chain/exceptions.hpp, libraries/chain/include/eosio/chain/host_context.hpp, libraries/chain/include/eosio/chain/sync_call_context.hpp, libraries/chain/sync_call_context.cpp, unittests/sync_call_tests.cpp
Enforce on chain configuration parameter `max_sync_call_depth` for nested and recursive sync calls. Once the depth is reached, the call is aborted.
Notable things about the two new two tests for the PR:
1. One test has one function making sync calls to itself recursively, another has two functions on different accounts calling each other recursively. Both tests show sync calls work correctly when max depth is not reached, and calls are aborted when max depth is reached.
2. The test WASM contracts utilize `sender` and `receiver` arguments from `sync_call` entry point, which demonstrates those two arguments are set correctly.
Resolves https://github.com/AntelopeIO/spring/issues/1268
=> SC: enforce `max_sync_call_depth` for nested and recursive sync calls

tests/TestHarness/Cluster.py
`setfinalizer` can fail because it took longer than the allowed max transaction time. This is made worse by #1287. Add a retry on failure similar to what we do for set contract: https://github.com/AntelopeIO/spring/blob/8ec275d8b4fc5b047d012e1412a77c143c1042c7/tests/TestHarness/transactions.py#L164-L164
Resolves #1314
=> [1.1.3] Retry setfinalizer on failure

tests/TestHarness/Cluster.py
`setfinalizer` can fail because it took longer than the allowed max transaction time. This is made worse by #1287. Add a retry on failure similar to what we do for set contract: https://github.com/AntelopeIO/spring/blob/8ec275d8b4fc5b047d012e1412a77c143c1042c7/tests/TestHarness/transactions.py#L164-L164
Merges `release/1.1` into `main` including #1315 
Resolves #1314
=> [1.1.3 -> main] Retry setfinalizer on failure

plugins/producer_plugin/producer_plugin.cpp
For Spring 1.1 reduce the maximum allowed `read-only-read-window-time-us` to 200ms. This is done because Spring 1.1 does not support interrupting a read-only trx via ctrl-c. Therefore, only allow short run read-only trxs. Note the plan is the relax this restriction in Spring 1.2, see #1170. 
Resolves #1318
=> [1.1.3] Reduce max read-only-read-window-time-us

plugins/chain_plugin/chain_plugin.cpp, plugins/chain_plugin/test/plugin_config_test.cpp
Add `vaulta` to default list of `eos-vm-oc-whitelist` in anticipation of `core.vaulta` and others.
Resolves #1329
=> [1.1.3] Add vaulta to default eos vm oc whitelist

tests/TestHarness/transactions.py
Protocol activation happens in the next block start_block, wait an extra block so that activation can happen. The test was failing because even though the transaction with the activate was found, the protocol feature had not actually been activated yet. Activation happens in the next start_block. Wait another block so that the protocol feature is activated.
Merges `release/1.1` into `main` including #1341 
Resolves #1247
=> [1.1.4 -> main] Test fix: Wait an extra block for protocol activation

tests/TestHarness/Cluster.py
We have been seeing a number of tests fail because a trx could not execute in 250ms on ci/cd. Increase to 375ms to give more time on ci/cd.
Resolves #1321 
Resolves #1345
=> [1.1.4] Increase max-transaction-cpu-usage for slow/overwhelmed ci/cd

tests/p2p_no_blocks_test.py
Make sure node2 and node3 have trx reference block before killing bios node otherwise the trx will fail because the reference block is not available.
```
debug 2025-04-11T15:14:41.435 net-1     net_plugin.cpp:4204           operator()           ] signaled NACK, trx-id = f3b8e5c456fd9e94263640bf7453efaf9edc2c102e0174160b03c5f32a9e4936 : 3040007 invalid_ref_block_exception: Invalid Reference Block
Transaction's reference block 162 did not match 0000000000000000000000000000000000000000000000000000000000000000. Is this transaction from a different fork?
{"rb":162,"bs":"0000000000000000000000000000000000000000000000000000000000000000"}
nodeos  controller.cpp:5942 validate_tapos
{}
nodeos  controller.cpp:5943 validate_tapos
```
Resolves #1209
=> [1.1.4] Test fix: Make sure node2 and node3 have trx reference block

libraries/chain/include/eosio/chain/pending_snapshot.hpp, libraries/chain/include/eosio/chain/snapshot_scheduler.hpp, libraries/chain/snapshot_scheduler.cpp, plugins/producer_plugin/producer_plugin.cpp, tests/test_snapshot_information.cpp
Snapshot was verifying that a block was irreversible by `chain.fetch_block_by_id(block_id)`. However this was checked on the `irreversible_block` signal which is signaled before forks are pruned from the fork database. Therefore, it was possible to find a non-irreversible block for a block_id that was non-irreversible but that had a block_num <= LIB.
Not sure it is worth the complexity to support lib_num < block_num, but kept the existing functionality. Looks like this really only handles the rare cases of starting from a snapshot and creating a snapshot on HEAD. Or switching from IRREVERSIBLE to HEAD mode with a snapshot scheduled on an irreversible block that becomes irreversible. Even in those cases this could still potentially fail if running without a block log.
The snapshot …
=> [1.1.4] Correctly identify snapshot as forked out

libraries/chain/include/eosio/chain/pending_snapshot.hpp, libraries/chain/include/eosio/chain/snapshot_scheduler.hpp, libraries/chain/snapshot_scheduler.cpp, plugins/producer_plugin/producer_plugin.cpp, tests/test_snapshot_information.cpp
Snapshot was verifying that a block was irreversible by `chain.fetch_block_by_id(block_id)`. However this was checked on the `irreversible_block` signal which is signaled before forks are pruned from the fork database. Therefore, it was possible to find a non-irreversible block for a block_id that was non-irreversible but that had a block_num <= LIB.
Not sure it is worth the complexity to support lib_num < block_num, but kept the existing functionality. Looks like this really only handles the rare cases of starting from a snapshot and creating a snapshot on HEAD. Or switching from IRREVERSIBLE to HEAD mode with a snapshot scheduled on an irreversible block that becomes irreversible. Even in those cases this could still potentially fail if running without a block log.
The snapshot …
=> [1.1.4 -> main] Correctly identify snapshot as forked out

plugins/net_plugin/net_plugin.cpp
Call `process_blocks` after `received_blocks` to prevent `received_blocks` from interrupting `process_blocks` on fork switch.
Resolves #1343
=> [1.1.4] Avoid possible process block interruption on fork switch

tests/nodeos_under_min_avail_ram.py
Disable pause production since the test relies on production continuing after restart and the pause can kick in if the nodes take too long to stop/start.
Merges `release/1.1` into `main` including #1369 
Resolves #1344
=> [1.1.4 -> main] Test: Disable pause production in test

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, plugins/net_plugin/net_plugin.cpp, plugins/producer_plugin/producer_plugin.cpp, unittests/checktime_tests.cpp
Interrupt speculative transaction execution when a block is received or on ctrl-c.
Along with the existing interrupt of transactions in a block being validated, also interrupt speculative trxs so that processing of incoming block can start immediately.
Example:
```
debug 2025-04-08T14:39:46.595 net-3     net_plugin.cpp:4029           operator()           ] post process_incoming_block to app thread, block 441
debug 2025-04-08T14:39:46.595 net-3     controller.cpp:4563           interrupt_transactio ] Interrupting trx...
debug 2025-04-08T14:39:46.595 net-2     net_plugin.cpp:2855           operator()           ] ["localhost:9883 - f7f9514" - 4 127.0.0.1:60824] bcast block 441
debug 2025-04-08T14:39:46.596 nodeos    producer_plugin.cpp:2593      handle_push_result   ] [TRX_TRACE] Speculative …
```
=> Interrupt speculative transaction when block received

libraries/chain/CMakeLists.txt, libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/wasm_alloc_pool.hpp, libraries/chain/wasm_alloc_pool.cpp, libraries/chain/webassembly/privileged.cpp, libraries/chain/webassembly/runtimes/eos-vm.cpp, plugins/producer_plugin/producer_plugin.cpp, unittests/sync_call_tests.cpp
Dynamically creating wasm allocators is expensive; we don't want to create an allocator for each level of a call. Currently a thread_local queue with a fixed size (`max_sync_call_depth`) is pre-created on each thread.  But `max_sync_call_depth` can be changed by BPs, which requires dynamically resizing the queue on each thread. Solutions seem to be complicated if keeping using the thread locals.
This PR implements a new approach to managing Wasm allocators,  using a pool with an internal Boost lockfree stack.
The advantages are
1.  Lockfree for acquiring and releasing allocators.
2. When `max_sync_call_depth` changes, the pool changes right away. No need to check if `max_sync_call_depth` has changed every time.
3. Avoid the use of thread_locals.
4. Simpler to reason.
Thanks to …
=> SC: A new approach to managing Wasm allocators in controller

libraries/chain/include/eosio/chain/thread_utils.hpp
Needed for some future experiment; seems non-contentious and generic enough to PR ahead of time regardless of future experiment's uncertainty.
Allows using any executor for `post_async_task()`. Well, `io_context` is _not_ an executor, so really allows any executor or `io_context`. The alternative -- strictly accept executors -- would require adding calls to `ctx.get_executor()` any place that makes use of `post_async_task()` and passed an `io_context`. Oftentimes this is `post_async_task(thread_pool.get_executor())` but `get_executor()` on named_thread_pool is a misnomer since it returns an `io_context`.
=> allow any executor for `post_async_task()`

libraries/chain/include/eosio/chain/incremental_merkle.hpp, libraries/chain/include/eosio/chain/merkle.hpp
Cleanup in file I was touching anyways for future experiment; seems non-contentious enough to take regardless of future experiment's uncertainty.
=> remove C++20 ifdefs in merkle.hpp

plugins/producer_plugin/producer_plugin.cpp
Add a log of `Not producing block because stale production not enabled` which was the only cases that didn't already log when a node would produce but doesn't for some reason. Noticed this on a recent test failure when looking at the logs.
Also sets the flag that prevents the `producer_plugin` from going into an infinite wait for a block. Since you are a configured producer you should keep trying to produce.
=> Log if not producing because of stale production

libraries/chain/fork_database.cpp
Optimize opening/reading of the fork database by correctly setting the `pending_savanna_lib_id`. Also don't bother looking up qc claimed block if it can't result in a higher pending savanna LIB.
=> Optimize fork database open/read

libraries/chain/include/eosio/chain/merkle.hpp, libraries/chain/include/eosio/chain/thread_utils.hpp
Like #1398 but using this approach https://github.com/AntelopeIO/spring/pull/1398#issuecomment-2818894389
=> use a global merkle thread pool to avoid creation and destruction of threads every block

tests/ship_restart_test.py
Pause production before shutting down to avoid a race-condition of killing the producer right as it is producing. This should make sure the SHiP node has all the produced blocks.
Resolves #1409
=> [1.1.4] Test fix: Pause production before shutdown

tests/ship_restart_test.py
Pause production before shutting down to avoid a race-condition of killing the producer right as it is producing. This should make sure the SHiP node has all the produced blocks.
Merges `release/1.1` into `main` including #1413 
Resolves #1409
=> [1.1.4 -> main] Test fix: Pause production before shutdown

tests/spring_util_bls_test.py
Use a unique file name and open with truncate to avoid already exists error. Use `tempfile` to generate unique files.
Not convinced this is the actual problem of #1351, but seems like a reasonable guess.
Resolves #1351
=> [1.1.4] Test fix: Use unique file name

libraries/chain/apply_context.cpp, libraries/chain/include/eosio/chain/action.hpp
I was doing some research in this area and noticed that `generate_action_digest()` effectively copies an action's input and output (return) data. This is a refactor that avoids that. Discussion on removing checktime at https://github.com/AntelopeIO/spring/pull/1411#discussion_r2051923833. Not really expecting a notable perf improvement but a cleanup nonetheless.
=> avoid copying action when computing action digest

tests/spring_util_bls_test.py
Use a unique file name and open with truncate to avoid already exists error. Use `tempfile` to generate unique files.
Not convinced this is the actual problem of #1351, but seems like a reasonable guess.
Merges `release/1.1` into `main` including #1418 
Resolves #1351
=> [1.1.4 -> main] Test fix: Use unique file name

libraries/chain/host_context.cpp, libraries/chain/include/eosio/chain/sync_call_context.hpp, libraries/chain/sync_call_context.cpp, unittests/sync_call_tests.cpp
* Fix read_only flag in call traces such that `read_only` flag is `true` for all subsequent call traces after the first call whose `read_only` flag is `true`
* Rename `read_only` enum to `force_read_only` and introduce `read_only` to call_context to make code cleaner
* Add more comments explaining read_only request by the user and read_only state of the call_context
* Add tests to verify `read_only` flag values are correct in call traces
Resolves https://github.com/AntelopeIO/spring/issues/1408
=> SC: Fix read_only flag in call traces and make code cleaner in read only processing

libraries/chain/host_context.cpp, unittests/sync_call_tests.cpp
Make sure return value is retained if set_call_return_value() is called before eosio_exit().
Add a test to verify it works.
Resolves https://github.com/AntelopeIO/spring/issues/1372
=> SC: Make sure return value is retained if set_call_return_value() is called before eosio_exit()

plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp, plugins/state_history_plugin/state_history_plugin.cpp
A state_history session runs two corountines: one to read from the websocket and one to write to the websocket. A failure on either corountine will cause it to complete as well as indicate to the other countinue that it should complete as well. Completion of either corountine ends up here,
https://github.com/AntelopeIO/spring/blob/f7657a241de6dcb0c6314abb180800f345ac4ce3/plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp#L73-L81
Since the timing of those completions can be indeterminate, a simple counter is used to detect that both have completed. When that occurs `session` indicates externally that it is done and it's ready to be destroyed. "done" means the `session` is no longer using any of its members such as the `stream`, etc -- sounds safe to destroy right? …
=> [1.1.5] fix state history race on disconnect: drain session strand before destroying session

plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp, plugins/state_history_plugin/state_history_plugin.cpp
=> [1.1.5 -> 1.2.0-rc2] fix state history race on disconnect: drain session strand before destroying session

plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp, plugins/state_history_plugin/state_history_plugin.cpp
=> [1.2.0-rc2 -> main] fix state history race on disconnect: drain session strand before destroying session

plugins/state_history_plugin/CMakeLists.txt, plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp
With ubuntu22 having gcc11, don't need these any more :tada:
=> [2.0.0-dev] remove corountine workarounds required for gcc10

libraries/libfc/include/fc/io/raw.hpp, libraries/libfc/include/fc/io/raw_fwd.hpp
Add missing check for `MAX_NUM_ARRAY_ELEMENTS` in the `std::array` versions.
Also c++20 syntax update.
Resolves #1422.
=> add missing check for MAX_NUM_ARRAY_ELEMENTS in the std::array pack/unpack. Also c++20 syntax update.

libraries/chain/controller.cpp, libraries/chain/eosio_contract.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/wasm_interface.hpp, libraries/chain/include/eosio/chain/wasm_interface_private.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/code_cache.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/ipc_helpers.hpp, libraries/chain/wasm_interface.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/compile_monitor.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/compile_trampoline.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/ipc_helpers.cpp
Use an unbounded queue for `_result_queue` to avoid results getting dropped because the queue is full. 
Also call `free_code` when code is no longer used instead of waiting for LIB to reduce memory growth.
Resolves #1441
=> [1.1.5] Fix OC scheduling of compiles

libraries/chain/controller.cpp, libraries/chain/fork_database.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/fork_database.hpp, plugins/chain_plugin/chain_plugin.cpp, tests/nodeos_read_terminate_at_block_test.py, unittests/fork_db_tests.cpp
When syncing, a node can load up the fork database with many blocks ahead of the current head. The `terminate-at-block` option terminates when the head reaches the specified `terminate-at-block`. On restart of the node after `terminate-at-block` this can be confusing as the node can process the blocks out of the fork database on restart. To avoid having these extra blocks in the fork database on shutdown, `truncate-at-block` can now be specified along with `terminate-at-block`. On shutdown due to a `terminate-at-block`, if `truncate-at-block` is specified then the fork database will have all blocks beyond `truncate-at-block` removed.
```
--truncate-at-block arg (=0)          Stop hard replay / block log recovery
at this block number (if non-zero). Can
also be used with terminate-at-block …
```
=> Support truncate-at-block with terminate-at-block

libraries/chain/controller.cpp, libraries/chain/eosio_contract.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/wasm_interface.hpp, libraries/chain/include/eosio/chain/wasm_interface_private.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/code_cache.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/ipc_helpers.hpp, libraries/chain/wasm_interface.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/compile_monitor.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/compile_trampoline.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/ipc_helpers.cpp
Use an unbounded queue for `_result_queue` to avoid results getting dropped because the queue is full. 
Also call `free_code` when code is no longer used instead of waiting for LIB to reduce memory growth.
Merges `release/1.1` into `release/1.2` including #1447 
Resolves #1441
=> [1.1.5 -> 1.2.0-rc2] Fix OC scheduling of compiles

libraries/chain/controller.cpp, libraries/chain/eosio_contract.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/wasm_interface.hpp, libraries/chain/include/eosio/chain/wasm_interface_private.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/code_cache.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/ipc_helpers.hpp, libraries/chain/wasm_interface.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/compile_monitor.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/compile_trampoline.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/ipc_helpers.cpp
Use an unbounded queue for `_result_queue` to avoid results getting dropped because the queue is full. 
Also call `free_code` when code is no longer used instead of waiting for LIB to reduce memory growth.
Merges `release/1.2` into `main` including #1447 & #1458
Resolves #1441
=> [1.2.0-rc2 -> main] Fix OC scheduling of compiles

docs/01_nodeos/03_plugins/chain_plugin/index.md, docs/01_nodeos/03_plugins/http_plugin/index.md, docs/01_nodeos/03_plugins/net_plugin/index.md, docs/01_nodeos/03_plugins/producer_plugin/index.md, docs/01_nodeos/03_plugins/resource_monitor_plugin/index.md, docs/01_nodeos/03_plugins/state_history_plugin/index.md
Seems we have missed a number of updates.
Could look into "back-porting" these as needed to `1.2.0-rc2` if desired. Seems like these should be auto-generated instead of manually updating.
=> Updated docs with nodeos --help output

unittests/fork_db_tests.cpp
Fix
```
.../unittests/fork_db_tests.cpp:171:4:   required from here
.../libraries/boost/libs/test/include/boost/test/tools/assertion.hpp:72:13: warning:   comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’  [-Wsign-compare]
72 |     action( ==, EQ, !=, NE )
```
=> Fix comparison of different signedness warnings

docs/01_nodeos/03_plugins/chain_plugin/index.md
Effectively an empty diff because #1459 already in `main`.
Merges `release/1.2` into `main` including #1469.
=> [1.2.0-rc2 -> main] Updated docs with latest nodeos --help output

libraries/chain/include/eosio/chain/name.hpp
`<byteswap.h>` and `bswap_64()` are Linux specific which breaks builds on macos etc. This will work more broadly.
There is also Boost Endian but eh.. didn't really think that was worth it. The long term proper approach would be via c++23's `byteswap()`
=> [1.2.0-rc2] use more portable `__builtin_bswap64()`

unittests/api_tests.cpp
`eos-vm-oc.hpp` pulls in way too much stuff that won't work outside Linux, using just `intrinsic.hpp` gets `minimum_const_memcpy_intrinsic_to_optimize` & `maximum_const_memcpy_intrinsic_to_optimize` which is all we need here (and avoids `ifdef`ing stuff)
=> [1.2.0-rc2] fix build of `api_tests` on platforms without OC

libraries/chain/include/eosio/chain/name.hpp
=> [1.2.0-rc2 -> main] use more portable `__builtin_bswap64()`

.github/workflows/performance_harness_run.yaml
This PR updates the github actions for the PerformanceTestHarness. Upload and download artifacts where updated, and the upload artifact was migrated to a standard action. Any `upload-artifact` or `download-artifact` actions where migrated to `@v4`
See this github note on deprecation of `@v3` `upload-actions`
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
Resolve #1476
=> [1.2.0-rc2] Migrate Performance Test Harness Actions to @v4

.github/workflows/performance_harness_run.yaml
This PR updates the github actions for the PerformanceTestHarness. Upload and download artifacts where updated, and the upload artifact was migrated to a standard action. Any `upload-artifact` or `download-artifact` actions where migrated to `@v4`
See this github note on deprecation of `@v3` `upload-actions`
https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
Merges `release/1.2` into `main` including #1481 
Resolve #1476
=> [1.2.0-rc2 -> main] Migrate Performance Test Harness Actions to @v4

libraries/chain/controller.cpp
Currently truncating blocks from the fork database is not supported during Savanna transition. Check for Savanna transition and log a warning instead of removing blocks from the fork database.
See #1467, specifically: https://github.com/AntelopeIO/spring/issues/1467#issuecomment-2847646584 for more details.
Example output:
```
info  2025-05-02T16:44:48.903 nodeos    controller.cpp:1489           transition_to_savann ] Transitioning to savanna, IF Genesis Block 94, IF Critical Block 94
debug 2025-05-02T16:44:48.903 nodeos    block_state.cpp:203           create_transition_bl ] Create transition block 95
info  2025-05-02T16:44:48.903 nodeos    controller.cpp:1534           operator()           ] Transition to instant finality happening after block 95, First IF Proper Block 96
warn …
```
=> Do not allow truncate-at-block when in savanna transition

.github/workflows/performance_harness_run.yaml
Changes upload directory for `build.tar.zst`. Fixes test failing when workflow was unable to find tarred binaries `build.targ.zst`
Fixes #1476
=> [1.2.0-rc2] Performance Workflow Move Upload Out of Build Dir

.github/workflows/performance_harness_run.yaml
Changes upload directory for `build.tar.zst`. Fixes test failing when workflow was unable to find tarred binaries `build.targ.zst`
Fixes #1476 
Related PR in `release/1.2` branch https://github.com/AntelopeIO/spring/pull/1494
=> [1.2.0-rc2 -> main] Performance Workflow Move Upload Out of Build Dir

plugins/producer_plugin/producer_plugin.cpp
Fix the logging of failed trx to include the trx or id in the log output.
=> [1.2.0-rc2] Fix logging of failed trx

tests/TestHarness/testUtils.py
The side effect of doing it this way is that it loses the debug print. idk.. debug print doesn't seem so useful here. Should fix #1486
=> [1.2.0-rc2] fix race on creation of `TestLogs` directory in TestHarness Utils

.gitmodules, libraries/state_history/abi.cpp, libraries/state_history/include/eosio/state_history/abi.hpp, tests/CMakeLists.txt, tests/ship_client.cpp, tests/ship_streamer.cpp, unittests/CMakeLists.txt, unittests/state_history_tests.cpp
Removes abieos usage (and the submodule entirely); uses spring's abi_serializer instead.
=> remove abieos usage from state history tests

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/peer_keys_db.hpp, libraries/chain/peer_keys_db.cpp, plugins/net_api_plugin/net_api_plugin.cpp, plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp, plugins/net_plugin/include/eosio/net_plugin/buffer_factory.hpp, plugins/net_plugin/include/eosio/net_plugin/gossip_bps_index.hpp, plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp, plugins/net_plugin/include/eosio/net_plugin/net_utils.hpp, plugins/net_plugin/include/eosio/net_plugin/protocol.hpp, plugins/net_plugin/net_plugin.cpp, plugins/net_plugin/tests/auto_bp_peering_unittest.cpp, tests/auto_bp_gossip_peering_test.py
- Add new `p2p-bp-gossip-endpoint <producer account>,<advertised inbound connection endpoint>,<outbound connection IP address>`
- Where `<producer account>` is the previous `p2p-producer-peer`. The BP producer account used for producing and used for registering an on-chain producer peer key.
- Where `<advertised inbound connection endpoint>` is an externally reachable IP address or domain name with port.
- Where `<outbound connection IP address>` is the IP address this node will connection from. This is provided so that BPs using a firewall can add this entry to allow connection. Required and must be a valid IP address.
- Only communicated over bp gossip messages, not sent to non-bp-gossip peers.
- `p2p-bp-gossip-endpoint` can be specified more than once if multiple endpoints for a node …
=> [1.2.0-rc2] P2P: Gossip BP peer enhancements

plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp, plugins/net_plugin/include/eosio/net_plugin/gossip_bps_index.hpp, plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp, plugins/net_plugin/include/eosio/net_plugin/protocol.hpp, plugins/net_plugin/net_plugin.cpp, plugins/net_plugin/tests/auto_bp_peering_unittest.cpp
Use a versioned signed type for `gossip_bp_peers_message::signed_bp_peer`. This will allow for future additions to the `signed_bp_peer` while maintaining backward compatibility with future signed data.
See #1495 for more details.
Resolves #1495
=> [1.2.0-rc2] P2P: Versioned signed type for gossip_bp_peers_message::signed_bp_peer

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/controller.hpp, libraries/chain/include/eosio/chain/peer_keys_db.hpp, libraries/chain/peer_keys_db.cpp, plugins/net_api_plugin/net_api_plugin.cpp, plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp, plugins/net_plugin/include/eosio/net_plugin/buffer_factory.hpp, plugins/net_plugin/include/eosio/net_plugin/gossip_bps_index.hpp, plugins/net_plugin/include/eosio/net_plugin/net_plugin.hpp, plugins/net_plugin/include/eosio/net_plugin/protocol.hpp, plugins/net_plugin/net_plugin.cpp, plugins/net_plugin/tests/auto_bp_peering_unittest.cpp, tests/auto_bp_gossip_peering_test.py
Merges `release/1.2` into `main` including #1503  
- Add new `p2p-bp-gossip-endpoint <producer account>,<advertised inbound connection endpoint>,<outbound connection IP address>`
- Where `<producer account>` is the previous `p2p-producer-peer`. The BP producer account used for producing and used for registering an on-chain producer peer key.
- Where `<advertised inbound connection endpoint>` is an externally reachable IP address or domain name with port.
- Where `<outbound connection IP address>` is the IP address this node will connection from. This is provided so that BPs using a firewall can add this entry to allow connection. Required and must be a valid IP address.
- Only communicated over bp gossip messages, not sent to non-bp-gossip peers.
- `p2p-bp-gossip-endpoint` can be …
=> [1.2.0-rc2 -> main] P2P: Gossip BP peer enhancements

libraries/custom_appbase/tests/custom_appbase_tests.cpp
Do not require every thread to run a task in test. In practice sometimes a thread doesn't actually run a task. There is nothing that would guarantee every thread runs at least one task, so don't require it.
Resolves #1502
=> [1.2.0-rc3] Test: Relax hard thread test

tutorials/bios-boot-tutorial/README.md, tutorials/bios-boot-tutorial/bios-boot-tutorial.py, tutorials/bios-boot-tutorial/test/tests.py
Two changes
- update name of `system-contracts` github repro 
- Update help text for `bios-boot-tutorial.py` change from `EOSIO` to `Vaulta`
Resolved #1376
=> [1.2] Rebrand Updates Bios Boot Tutorial

tutorials/bios-boot-tutorial/README.md, tutorials/bios-boot-tutorial/bios-boot-tutorial.py, tutorials/bios-boot-tutorial/test/tests.py
Updated `bios-boot-tutorial` with Vaulta changes. Includes the following
- org changes to `VaultaFoundation`
- Inclusion of `A` token 
- Adding missing system account names
- Tests to validate fixes, and `A` token 
Test requires `pytest` and would be run as `pytest test/tests.py`. 
Related PR in `release/1.2` https://github.com/AntelopeIO/spring/pull/1536
=> [1.2 -> Main] Merge rebrand update bios boot tutorial

plugins/net_plugin/net_plugin.cpp
Change default `agent-name` to `Spring Agent".
Related to #1537
=> [1.2.0-rc3] P2P: agent-name

libraries/chain/controller.cpp, libraries/chain/include/eosio/chain/exceptions.hpp, libraries/libfc/include/fc/exception/exception.hpp, libraries/libfc/src/network/http/http_client.cpp, libraries/libfc/test/CMakeLists.txt, libraries/libfc/test/test_exception.cpp, libraries/testing/tester.cpp, plugins/http_plugin/include/eosio/http_plugin/macros.hpp, plugins/producer_api_plugin/producer_api_plugin.cpp, tests/chain_test_utils.hpp, unittests/api_tests.cpp, unittests/test_utils.hpp, unittests/wasm_tests.cpp
I ran into the issue again where fc exception type is lost. In the past that has led to comments like:
```cpp
// this always throws an fc::exception, since the original exception is copied into an fc::exception
throw *trace->except;
```
The comment is a bit misleading. The original exception was not copied into an `fc::exception` it was `dynamic_copy_exception` which does preserve the type into the `shared_ptr<exception>`. It is not until the actual throw that the object is copied/sliced into an fc::exception. 
The previous use would lead to confusion around catching `fc::exception`.
```
try {
// call something that does something like:  throw *trace->except;
// note that  throw *trace->except; slices the object
} catch (fc::assert_exception& e) {
// expect to catch an assert exception, …
```
=> [2.0.0-dev] Add a rethrow() to fc::exception to preserve exception type

libraries/chain/include/eosio/chain/pending_snapshot.hpp, libraries/chain/include/eosio/chain/snapshot_scheduler.hpp, libraries/chain/snapshot_scheduler.cpp, plugins/producer_plugin/producer_plugin.cpp, tests/nodeos_snapshot_forked_test.py, tests/test_snapshot_scheduler.cpp
Instead of generating an error on `/v1/producer/create_snapshot` when the block is forked out, generate a new snapshot and report that snapshot to the user.
Example from fork test:
```
debug 2025-05-22T15:56:19.502 http-1    beast_http_session.hpp:157    handle_request       ] Request:  localhost:8889 POST /v1/producer/create_snapshot HTTP/1.1  Accept-Encoding: identity  Content-Length: 0  Host: localhost:8889  User-Agent: Python-urllib/3.10  Connection: close    
debug 2025-05-22T15:56:19.502 nodeos    snapshot_scheduler.cpp:16     operator()           ] snapshot scheduler creating a snapshot from the request [start_block_num:189, end_block_num=4294967295, block_spacing=0], height=190
info  2025-05-22T15:56:19.503 nodeos    snapshot_scheduler.cpp:219    create_snapshot      ] Starting …
```
=> [2.0.0-dev] Generate new snapshot on fork

docs/01_nodeos/03_plugins/trace_api_plugin/index.md, plugins/trace_api_plugin/examples/abis/core.vaulta.abi, plugins/trace_api_plugin/examples/abis/eosio.abi, plugins/trace_api_plugin/examples/abis/eosio.msig.abi, plugins/trace_api_plugin/examples/abis/eosio.token.abi, plugins/trace_api_plugin/examples/abis/eosio.wrap.abi
Add `core.vaulta.abi` and update `eosio.*` abis in `trace_api_plugin` example abis.
Example output with:
```
--plugin eosio::trace_api_plugin --trace-rpc-abi eosio=../../../plugins/trace_api_plugin/examples/abis/eosio.abi --trace-rpc-abi eosio.token=../../../plugins/trace_api_plugin/examples/abis/eosio.token.abi --trace-rpc-abi core.vaulta=../../../plugins/trace_api_plugin/examples/abis/core.vaulta.abi
```
```
curl  http://127.0.0.1:8888/v1/trace_api/get_block -d '{"block_num": 439273660}' | jq  
...
{
"global_sequence": "363985764702",
"receiver": "eosiopowcoin",
"account": "eosio.token",
"action": "transfer",
"authorization": [
{
"account": "eosiopowcoin",
"permission": "active"
}
],
"data": "301d459c56ea3055502f459566aca461010000000000000004454f53000000000a526566756e6420454f53", …
```
=> [1.2.0-rc3] TraceAPI: Add core.vaulta.abi and update eosio.* abis

plugins/net_plugin/include/eosio/net_plugin/net_utils.hpp, plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
During the consolidation of address parsing in release 1.1, parsing of IPv6 addresses was broken.
Release 1.0 removed `[` & `]` from the host. See https://github.com/AntelopeIO/spring/blob/v1.0.5/plugins/net_plugin/net_plugin.cpp#L1211
This PR restores the removal of `[` & `]` which fixes IPv6 support in `net_plugin`.
Merges `release/1.1` into `release/1.2` including #1594 
Resolves #1588
=> [1.1.6 -> 1.2.0-rc3] P2P: Fix IPv6 support

plugins/net_plugin/include/eosio/net_plugin/net_utils.hpp, plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
During the consolidation of address parsing in release 1.1, parsing of IPv6 addresses was broken.
Release 1.0 removed `[` & `]` from the host. See https://github.com/AntelopeIO/spring/blob/v1.0.5/plugins/net_plugin/net_plugin.cpp#L1211
This PR restores the removal of `[` & `]` which fixes IPv6 support in `net_plugin`.
Merges `release/1.2` into `main` including #1594 & #1595
Resolves #1588
=> [1.2.0-rc3 -> main] P2P: Fix IPv6 support

plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp, plugins/net_plugin/include/eosio/net_plugin/net_utils.hpp, plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
Remove leading-trailing spaces from `p2p-bp-gossip-endpoint` values to avoid peers attempting to connect to a host with a leading or trailing space. Also trim all host names when using them to avoid attempting to use a host from a peer with a leading or trailing space.
Resolves #1585
=> [1.2.0-rc3] P2P: Trim addresses

plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp, plugins/net_plugin/include/eosio/net_plugin/net_utils.hpp, plugins/net_plugin/tests/rate_limit_parse_unittest.cpp
Remove leading-trailing spaces from `p2p-bp-gossip-endpoint` values to avoid peers attempting to connect to a host with a leading or trailing space. Also trim all host names when using them to avoid attempting to use a host from a peer with a leading or trailing space.
Merges `release/1.2` into `main` including #1597 
Resolves #1585
=> [1.2.0-rc3 -> main] P2P: Trim addresses

tests/CMakeLists.txt, tests/TestHarness/Cluster.py, tests/TestHarness/Node.py, tests/TestHarness/launcher.py, tests/bridge_consecutive_shape.json, tests/nodeos_forked_chain_test.py, tests/nodeos_short_fork_take_over_test.py, tests/nodeos_snapshot_forked_test.py, tests/prod_preactivation_test.py, tests/transition_to_if.py
By default, configure integration tests nodes to have non-consecutive block producers. Before if 4 producers were configured with 2 producer nodes the block producers would be configured as `node_00[defproducera,defproducerb]`, `node_01[defproducerc,defproducerd]`. Now they will be configured as `node_00[defproducera,defproducerc]`,  `node_01[defproducerb,defproducerd]`.
Related to #1492
=> Test: Setup tests to have non-consecutive block producers

programs/cleos/main.cpp
Switch cleos to opting in to UTF8 locale which makes everything just work when using `--url` with an IDN hostname. `LC_CTYPE, "C.UTF-8"` should be the most conservative opt in here (vs something like `LC_ALL, ""` which will use the system configured locale which might affect how dates are printed etc) but I'm still not 100% sure if there is any potential fall out.
=> switch cleos to using UTF8 locale; allows using IDN endpoints

libraries/chain/include/eosio/chain/platform_timer.hpp, libraries/chain/include/eosio/chain/thread_utils.hpp, libraries/chain/platform_timer_asio_fallback.cpp, libraries/chain/platform_timer_kqueue.cpp, libraries/chain/platform_timer_posix.cpp, unittests/platform_timer_tests.cpp
Ensure any inflight `platform_timer` callbacks are complete before exiting `platform_timer::stop()`. This makes sure the correct transaction is interrupted when the callback is called.
Merges `release/1.2` into `main` including #1606 & #1609
Resolves #1601
=> [1.2.0 -> main] Ensure callback complete before exiting platform_timer stop

libraries/libfc/include/fc/log/logger.hpp, libraries/libfc/src/log/logger.cpp, libraries/libfc/src/log/logger_config.cpp
Use a global default logger to avoid mutex, map lookup, and shared_ptr copy on use of default logger.
For example, `dlog` would acquire a mutex, do a map lookup, and then create a shared_ptr copy of the logger just to check the log level.
=> Optimize default logger

plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp, plugins/net_plugin/net_plugin.cpp, plugins/net_plugin/tests/auto_bp_peering_unittest.cpp, tests/TestHarness/queries.py, tests/auto_bp_gossip_peering_test.py
- Do not disconnect from BP gossip peers if they are manually configured.
- Disconnect from BP gossip peers when no longer in the active proposer schedule.
Resolves #1584
=> [1.2.0] P2P: BP gossip connections

tests/production_pause_vote_timeout.py
On slow ci/cd machines it can take a while for votes to catchup and LIB to move.
Resolves #1629
=> [1.2.0] Test: Increase timeout

tests/block_log_util_test.py
Update test to allow for a few blocks in the forkdb after SIGTERM. It is possible that after `get_info` but before the node shutsdown that a few blocks are produced.
See #1633 for details.
Resolves #1633
=> Test: block_log_util - Allow more blocks in forkdb

tests/pause_at_block_test.py
Wait on block before trying to verify that the node has not moved past it. Otherwise, it is possible that the node is not at the paused block yet when `getHeadBlockNum()` is called.
Merges `release/1.2` into `main` including #1638 & #1627 
Resolves #1637
=> [1.2.0 -> main] Test: Wait on block before verification of pause

tests/p2p_sync_throttle_test.py, tests/p2p_sync_throttle_test_shape.json
In an attempt to make the `p2p_sync_throttle_test` more stable and fair, sync both the throttled node and unthrottled node from the same peer.
Resolves #1643
=> [1.2.1] Test: Modify sync test to sync from the same node

plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp, plugins/net_plugin/include/eosio/net_plugin/buffer_factory.hpp, plugins/net_plugin/include/eosio/net_plugin/net_logger.hpp, plugins/net_plugin/net_plugin.cpp, programs/nodeos/logging.json
The P2P `net_plugin` logger `net_plugin_impl` incorporated a huge amount of logging. This PR splits the `net_plugin_impl` into 5 different loggers. It is backwards compatible with existing `logging.json`. The `net_plugin_impl` is now setup as the parent logger of the new `p2p_*` logs. See https://github.com/AntelopeIO/spring/pull/1589. 
- `p2p_log` - Generic P2P log messages
- `p2p_trx` - transaction received/sent logging
- `p2p_block` - block/block_header received/sent logging, block syncing info
- `p2p_message` - all p2p messages received/sent (except block/trx)
- `p2p_connection` - connections related logging, e.g. connect/disconnect
The example `logging.json` in `programs/nodeos` has been updated to include the new loggers.
Resolves #1500
=> P2P: Split net_plugin_impl logger

tests/p2p_sync_throttle_test.py, tests/p2p_sync_throttle_test_shape.json
In an attempt to make the `p2p_sync_throttle_test` more stable and fair, sync both the throttled node and unthrottled node from the same peer.
Merges `release/1.2` into `main` including #1647 
Resolves #1643
=> [1.2.1 -> main] Test: Modify sync test to sync from the same node

tests/auto_bp_gossip_peering_test.py
Ignore in-coming connection when evaluating the connected peers.
Resolves #1656
=> [1.2.1] Test: Do not error when there is an in-coming connection

tests/auto_bp_gossip_peering_test.py
Ignore in-coming connection when evaluating the connected peers.
Merges `release/1.2` into `main` including #1657 
Resolves #1656
=> [1.2.1 -> main] Test: Do not error when there is an in-coming connection

plugins/net_plugin/net_plugin.cpp
When syncing due to a head catchup the node determines the end sync block. Therefore, if any block is not available during a head catchup sync it must be due to a fork-switch. Treat a block not found during a head catchup sync the same as a block nack sync when not found; do not disconnect.
Resolves #1660
=> [1.2.1] P2P: Do not disconnect on catchup sync when block not available

programs/cleos/main.cpp, tests/nodeos_run_test.py
`cleos` commands like `transfer` and `buyram` that are provided an `A` asset use `core.vaulta` instead of `eosio.token` / `eosio` contract. Commands that use any other asset, including `EOS`, continue to default to `eosio.token` (for transfer) and `eosio` for all other commands.
Deprecated commands: `canceldelay`, `rentcpu`, `rentnet`, `fundnetloan`, `defundnetload`, `fundcpuloan`, `defundcpuload`.
Resolves #1612
=> Add core.vaulta support to cleos

libraries/chain/block_header_state.cpp, unittests/blocks_log_replay_tests.cpp
Switch from `assert` to `EOS_ASSERT` for better error reporting while validating blocks.
Resolves #1671
=> [1.2.1] Report error on invalid block

libraries/chain/abi_serializer.cpp, libraries/chain/include/eosio/chain/abi_def.hpp
Minor changes to `version_t`, mostly adding a default constructor for tests and using the internal `valid` flag rather than `std::optional<valid_t>`.
This is useful for writing tests.
=> [2.0.0-dev] Minor changes to `version_t`.

programs/cleos/httpc.cpp
Add the URI to `cleos` error message of endpoint misconfiguration.
```
07/7/25 10:34:47 ➜  bin git:(GH-990-ship-index-check) ✗ ./cleos get info
Error 3110001: Missing Chain API Plugin
Ensure that you have eosio::chain_api_plugin added to your node's configuration and enabled on the specified endpoint.
For example:
http-server-address   = http-category-address
http-category-address = chain_ro,127.0.0.1:8081
http-category-address = chain_rw,[::]:8083
Error Details:
Chain API plugin is not enabled on endpoint: http://127.0.0.1:8888
```
Resolves #1683
=> CLI: Add URI to cleos error message

libraries/testing/include/eosio/testing/tester.hpp, libraries/testing/tester.cpp, tests/chain_plugin_tests.cpp, unittests/api_tests.cpp, unittests/bls_primitives_tests.cpp, unittests/crypto_primitives_tests.cpp, unittests/currency_tests.cpp, unittests/get_block_num_tests.cpp, unittests/params_tests.cpp, unittests/protocol_feature_tests.cpp, unittests/savanna_cluster.cpp, unittests/savanna_cluster.hpp, unittests/wasm_config_tests.cpp, unittests/wasm_tests.cpp, unittests/whitelist_blacklist_tests.cpp
Instead of an `enum` for `setup_policy`, use a class containing:
1. a list of actions
2. a list of protocol features to activate.
Also rename some ill-named `preactivate*` to `activate*`.
=> Update tester to allow for a more flexible configuration of its state.

plugins/trace_api_plugin/include/eosio/trace_api/store_provider.hpp, plugins/trace_api_plugin/store_provider.cpp, plugins/trace_api_plugin/test/test_trace_file.cpp, plugins/trace_api_plugin/trace_api_plugin.cpp, tests/TestHarness/Node.py, tests/trace_plugin_test.py
When starting from a snapshot, not all stride files are present. Instead of attempting to find the first stride file and failing, loop through the trx id files on disk. Also now searches in reverse order assuming the trx searched for is more likely to be in a recent block.
Merges `release/1.2` into `main` including #1700
Resolves #1693
=> [1.2.1 -> main] TraceAPI: Fix for finding trx after starting from snapshot

tests/snapshot_in_svnn_transition_test.py
Test failed because it took just over 30 seconds to sync up.
Merges `release/1.2` into `main` including #1707 
Resolves #1705
=> [1.2.1 -> main] Test: Allow more time for node to startup and sync

CMakeLists.txt
Update top level CMakeLists.txt to check for and require gnu version 11 or better. Clear error message for someone with older build, for example Ubuntu 20, that may pick up earlier version of the compilers.
=> [2.0.0-dev] Enforce gxx version 11

tools/reproducible.Dockerfile
Allow extracting the pinned toolchain to use outside of the docker container it is built in. I have tried this on Arch & Ubuntu 24.04 and it seems to work well.
Resolves #1709. Also imo this is good enough to close out AntelopeIO/leap#1707 but will let @greg7mdp make that call.
=> extractable pinned toolchain

plugins/chain_api_plugin/chain.swagger.yaml
- `/get_account`: Added optional param expected_core_symbol_precision. This allows a client to validate the core symbol precision of the chain when fetching account details.
- `/get_table_rows`: The json parameter was missing. This allows the client to specify whether the table row data should be returned as structured JSON or as a hex string.
- `/get_code`: better description for `code_as_wasm` param
- `/get_raw_abi`: Added `abi_hash`
=> added missing properties on API calls

plugins/chain_api_plugin/chain.swagger.yaml
Updates to the `chain` API documentation adding `get_consensus_parameters`
https://staging.docs.eosnetwork.com/apis/spring/latest/chain.api#operation/get_consensus_parameters
=> [Main] Update Chain API Docs add get_consensus_params

package.cmake, scripts/postinst, scripts/prerm
reapply original changes from #931 on to 2.0 since 2.0 branch no longer supports ubuntu20
=> [2.0.0-dev] remove use of deprecated python distutils

plugins/net_plugin/net_plugin.cpp
Reverts #1676. A recent test failure #1716 demonstrates the need for the reset. The test failed because it timed out waiting for LIB to advance. The node did actually advance LIB but not in the expected 30 second timeout. The issue was that an unlinkable block at transition from LIB catchup to HEAD catchup didn't reset sync and therefore the node didn't know it needed to continue syncing. The handshake was not sufficient because the other node thought it had caught up. This was exasperated by the node syncing was in IRREVERSIBLE mode. It is possible that we could live with only resetting when running in IRREVERSIBLE mode. However, I think the safest and most direct approach is to go back to resetting the sync, but guard against resetting the sync when know we have already reset the sync. …
=> [1.2.2 -> main] P2P: Reset sync on rejected block

plugins/net_plugin/net_plugin.cpp
Add logging of send buffer size.
Example output:
```
debug 2025-07-15T16:57:21.671 net-0     net_plugin.cpp:1674           log_send_buffer_stat ] ["localhost:9877" - 2 127.0.0.1:9877] send buffer: 329 bytes, max send buffer: 425984 bytes, available: 425655 bytes
```
The cost of the calculation was surprising low. 
```
info  2025-07-15T16:57:21.671 net-3     stopwatch.hpp:66              report_msg           ] get send buffer stats calls: 500, total: 363us, avg: 0us, max: 23us
info  2025-07-15T16:57:39.207 net-0     stopwatch.hpp:66              report_msg           ] get send buffer stats calls: 500, total: 345us, avg: 0us, max: 26us
info  2025-07-15T16:57:44.036 net-1     stopwatch.hpp:66              report_msg           ] get send buffer stats calls: 500, total: 488us, avg: 0us, max: …
```
=> P2P: Add logging of send buffer size

tests/TestHarness/Node.py, tests/TestHarness/queries.py
Do not fail test when not able to find a block while waiting on a transaction. If a fork happens during the wait we don't want to exit on error. Instead we should keep looking until we timeout.
Resolves #1753
=> [1.2.2] Test: Do not fail on not finding a block

tests/disaster_recovery_3.py
Test failed because LIB advanced on resume before node0 and node1 could shutdown. Do not resume production until node0 and node1 are shutdown so that LIB does not advance unexpectedly.
Resolves #1778
=> [1.2.2] Test: Shutdown before resume

tests/disaster_recovery_3.py
Test failed because LIB advanced on resume before node0 and node1 could shutdown. Do not resume production until node0 and node1 are shutdown so that LIB does not advance unexpectedly.
Merges `release/1.2` into `main` including #1779 
Resolves #1778
=> [1.2.2 -> main] Test: Shutdown before resume

plugins/net_plugin/net_plugin.cpp
Track `last_block_num_received` across all connections and use that instead of chain head for determination if block nack reset should be sent. Also reset `consecutive_blocks_nacks` when block nacks are not consecutive.
Resolves #1784
=> [1.2.2] P2P: Block nack reset fix

plugins/net_plugin/net_plugin.cpp
Track `last_block_num_received` across all connections and use that instead of chain head for determination if block nack reset should be sent. Also reset `consecutive_blocks_nacks` when block nacks are not consecutive.
Merges `release/1.2` into `main` including #1786 
Resolves #1784
=> [1.2.2 -> main] P2P: Block nack reset fix

plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp
I missed this one in yesterday's https://github.com/AntelopeIO/spring/pull/1791
```
.../plugins/net_plugin/include/eosio/net_plugin/auto_bp_peering.hpp:436:50: warning: comparison of integer expressions of different signedness: ‘std::__iterator_traits<boost::multi_index::detail::bidir_node_iterator<boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::ordered_index_node<boost::multi_index::detail::null_augment_policy, boost::multi_index::detail::index_node_base<eosio::gossip_bp_peers_message::signed_bp_peer, std::allocator<eosio::gossip_bp_peers_message::signed_bp_peer> > > > > >, void>::difference_type’ {aka ‘long int’} and …
```
=> Fix a missed signed comparison waring

libraries/chain/include/eosio/chain/wasm_interface_private.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/code_cache.hpp, libraries/chain/include/eosio/chain/webassembly/eos-vm-oc/ipc_protocol.hpp, libraries/chain/webassembly/runtimes/eos-vm-oc.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp, libraries/chain/webassembly/runtimes/eos-vm-oc/compile_trampoline.cpp, libraries/libfc/include/fc/log/log_message.hpp
Adds some useful information about oc compiles. Example output:
```
info  2025-07-29T17:33:33.860 nodeos    compile_trampoline.cpp:145    run_compile          ] receiver token.pcash, wasm size: 126 KB, oc code size: 199 KB, compile memory usage: 42 MB, time: 972 ms, time since queued: 1735 ms
info  2025-07-29T17:33:33.905 nodeos    compile_trampoline.cpp:145    run_compile          ] receiver tokensbridge, wasm size: 169 KB, oc code size: 278 KB, compile memory usage: 49 MB, time: 1160 ms, time since queued: 1905 ms
info  2025-07-29T17:33:33.991 nodeos    compile_trampoline.cpp:145    run_compile          ] receiver eosio.fees, wasm size: 16 KB, oc code size: 28 KB, compile memory usage: 26 MB, time: 130 ms, time since queued: 641 ms
info  2025-07-29T17:33:34.085 nodeos …
```
=> Add some oc compile logging info

unittests/checktime_tests.cpp, unittests/test_utils.hpp
Add tests:
- Test that verifies that even when maximum is passed to max_trx_time of push_transaction that it is still restricted to on-chain trx maximum.
- Test that verifies speculative trx execution can be interrupted. 
Resolves #1799
=> Test: Add test for max_trx_time and speculative execution interrupt

plugins/producer_plugin/producer_plugin.cpp
Add exhausted count and time to block report.
Also fixes an issue with restarting a block not reporting trx time in the correct block report.
```
debug 2025-07-31T18:37:38.791 nodeos    producer_plugin.cpp:2672      handle_push_result   ] [TRX_TRACE] Speculative execution COULD NOT FIT, elapsed 281920us, tx: b4bf410cc1fe1ded53db38b2d45f2b069800f6607f38adeb3098f36e2dfa074e RETRYING
debug 2025-07-31T18:37:38.791 nodeos    producer_plugin.cpp:1000      restart_speculative_ ] Restarting exhausted speculative block #146
debug 2025-07-31T18:37:38.791 nodeos    producer_plugin.cpp:316       report               ] Block #146 eosio trx idle: 226480us out of 508606us, success: 0, 0us, exhausted: 1, 281692us, fail: 0, 0us, transient: 0, 0us, other: 434us
```
Resolves #1798
=> Add exhausted count and time to block report

unittests/savanna_cluster.cpp
I am encountering a bizarre problem locally with the savanna cluster. Bizarre in that I can't explain why we're not seeing it in CI etc
When a savanna cluster is created in reserves some space in `_nodes` and then `emplace_back()` the `node_t`s,
https://github.com/AntelopeIO/spring/blob/ecc902d5e54d25ceec8ebde9b2c45e7078421ffb/unittests/savanna_cluster.hpp#L376-L385
During the `node_t` ctor, toward the end it,
https://github.com/AntelopeIO/spring/blob/ecc902d5e54d25ceec8ebde9b2c45e7078421ffb/unittests/savanna_cluster.cpp#L49-L57
So notice it will `cluster.get_new_blocks_from_peers(node_idx)` before completing the ctor. And look what `get_new_blocks_from_peers()` does,
https://github.com/AntelopeIO/spring/blob/ecc902d5e54d25ceec8ebde9b2c45e7078421ffb/unittests/savanna_cluster.hpp#L626-L632 …
=> avoid accessing currently in progress `emplace()`ing `node_t`

libraries/libfc/include/fc/io/raw.hpp
Reported by "leo"; these aren't used anywhere in spring so the improper implementation went unnoticed.
=> fix pack & unpack for `fc::fwd` types

tools/reproducible.Dockerfile
Unfortunately it is no longer possible to build the 1.x pinned/reproducible package from scratch because it is based on Debian 10 which has had its packages removed from Debian's package repo around July 12 (it has been out of support for about a year now).
This moves the build to use Debian's package snapshot repo which contains all prior releases. This was previously plumbed through here (since pinning to exact packages would presumably be even more reproducible), though I had disabled it in the past since the package snapshot repo can be kind of slow.
Taking this approach will ensure no operational changes to any users who are using 1.2.x on an old distribution like Ubuntu 18. Though we didn't actually claim support for these old distributions, so it's not clear how aggressively we …
=> [1.2.3] use debian's package snapshot repo for old buster packages needed in reproducible build

tools/reproducible.Dockerfile
=> [1.2 -> main] use debian's package snapshot repo for old buster packages needed in reproducible build

libraries/chain/controller.cpp, tests/CMakeLists.txt, tests/read_only_trx_test.py, tests/sync_call_restart.py
Cherry pick https://github.com/AntelopeIO/spring/pull/1848
Currently resources for nested sync calls are allocated only at the time when `sync_call` protocol feature is activated. But when nodeos is restarted, `sync_call` might already have been . We should always allocated the resources.
The PR fixes the problem and adds a test case to show the problem has been fixed (before the fix, the test case failed).
Thanks @ericpassmore for reporting the problem and collecting the core dump.
Resolves https://github.com/AntelopeIO/spring/issues/1847
=> [2.0 -> 2.0.0-dev1] Allocate resources required by sync calls up front

libraries/libfc/include/fc/utility.hpp
Some simple UDL helpers for these computations. I didn't change any existing code but I could if we wanted to. Was using these inside of event related stuff; pulling them out of that branch for separate review.
=> UDLs for byte units (KiB, MiB, etc) and power-of-two
