- .cicd/defaults.json
`hotstuff_integration` branch of `instant_finality` was merged into CDT.
> Update CDT to main

- unittests/protocol_feature_tests.cpp
> Update protocol_feature_tests to run in both legacy and savanna

- unittests/read_only_trx_tests.cpp
> Update read_only_trx_tests to run in both Legacy and Savanna

- unittests/eosio.token_tests.cpp
- unittests/payloadless_tests.cpp
- unittests/special_accounts_tests.cpp
> Update token_tests, payloadless_tests, and special_accounts_tests to run in Legacy and Savanna

- libraries/testing/include/eosio/testing/tester.hpp
- unittests/currency_tests.cpp
- unittests/whitelist_blacklist_tests.cpp
> Update `currency_tests` and `whitelist_blacklist_tests` to run in both Legacy and Savanna

- libraries/testing/include/eosio/testing/tester.hpp
- unittests/CMakeLists.txt
- unittests/api_tests.cpp
- unittests/block_tests.cpp
- unittests/database_tests.cpp
- unittests/wasm_config_tests.cpp
* fix `savanna_validating_tester` not transition to Savanna
* update `block_tests` and `database_tests` for the correct `savanna_validating_tester`
> Fix `savanna_validating_tester` not transition to Savanna

- plugins/net_plugin/net_plugin.cpp
Since blocks are processed immediately into the fork database when received, there is no longer any reason to request ahead of the existing range. Under normal circumstances a node will receive blocks from its peer and process them into the fork database. While those blocks are being applied additional blocks can be requested from the network. Care is taken to make sure that the fork database does not out run the chain head by more than `sync-fetch-span`.
Merges `release/1.0-beta2` into `release/1.0-beta3` including #291
Resolves #281
> [1.0-beta2 -> 1,0-beta3] P2P: Fix multiple range requests while syncing

- tests/trx_finality_status_forked_test.py
The transaction finality status forked test allowed for a transaction to be forked out more than once, but not more than twice. The test failed as it was forked out four times.
Resolves #338
> Test: Finality Status: Transaction can be forked out multiple times

- libraries/chain/block_header_state.cpp
Also consistently log using the full block id, so that there is no mismatch between the `proposed` and `active` logs.
Sample output:
```
info  2024-07-17T17:14:56.437 unit_test block_header_state.cpp:275    finish_next          ] New finalizer policy becoming active in block 29:0000001da3de63ace8998af38d5bcffeaa668d03970be5bd1bcd3e91721ffb8a: {"generation":5,"threshold":15,"finalizers":[{"description":"finalizeraf description","weight":1,"public_key":"PUB_BLS_QtbIitBVbwbwrRy7NmRUgwbm_vihadowgALMMYaRC0sMbE9LDGmEZ4AQK7aD-hEK6TJLixgIkdpLq8FAZ-3YY4hkIf4T-5KijahGLyxJayv8LC30xPk5KrS9TwkjhkwSXL_-WQ"},{"description":"finalizerag description","weight":1,"public_key":"PUB_BLS_I5eaR4eTDbJ7WExklVftIg_2vhWkF6k9r7Hh7p2-vuSc2lzutD8veGy0NlJKLBoAWRfpuhECnocOBSF4L29wsqNrmNBoDGmOKsjoWCWqs86n3l8xeZGUJ2_pB7Jg2 …
```
> Use correct block id when logging new proposed finalizer policies.

- tests/disaster_recovery_2.py
Since all nodes are stopped and restarted, the first node to start has no peers to connect to. Provide time for the connection monitor to kick in and establish a connection.
Merges `release/1.0-beta4` into `main` including #426 
Resolves #390
> [1.0-beta4 -> main] Test: Provide more time for connections to be established

- unittests/forked_tests_savanna.cpp
fixes `warning: comparison of integer expressions of different signedness`
> fix mixed signedness warning

- libraries/chain/finality/qc.cpp
- Include index in `add_vote` log
- Log duplicate vote as `trace` level log to avoid huge spam at `debug` level
Merges `release/1.0-beta4` into `main` including #480
> [1.0-beta4 -> main] Improve vote logging

- libraries/chain/snapshot.cpp
spring main merge of AntelopeIO/leap#2398
> [5.0 -> main] fix some minor misspellings

- CMakeModules/EosioTester.cmake.in
- CMakeModules/EosioTesterBuild.cmake.in
> [1.0 -> main] add `BOOST_TEST_DEFAULTS_TO_CORE_DUMP` to libtester users

- plugins/net_plugin/net_plugin.cpp
- tests/test_snapshot_scheduler.cpp
- unittests/savanna_proposer_policy_tests.cpp
> [1.0 -> main] various different signedness warning fixes

- tests/disaster_recovery_2.py
Simplify integration tests and verify expected LIB is reached.
Merges `release/1.0` into `main` including #618
> [1.0 -> main] Test: Simplify disaster_recovery_2 test and verify correct LIB

- plugins/net_plugin/net_plugin.cpp
The change in #572: https://github.com/AntelopeIO/spring/pull/572#discussion_r1720822685 allows a node to sync ahead when it receives a irreversible block notice. Need to verify the main thread is not trailing too far behind before requesting additional blocks.
Merges `release/1.0` into `main` including #638 
Resolves #635
> [1.0 -> main] P2P: Prevent node from syncing too far ahead

- unittests/main.cpp
> [1.0.2] Enable debug logging of the vote logger for unittest --verbose

- libraries/libfc/include/fc/io/random_access_file.hpp
> [1.0.2 -> main] non-atomic append fallback to `random_access_file` for old kernels

- plugins/net_plugin/net_plugin.cpp
Reverts AntelopeIO/spring#853
SEGFAULTs in CI/CD run of `p2p_sync_throttle_test`
> [1.0.2] Revert "[1.0.2] P2P: Resolve on reconnect"

- unittests/savanna_cluster.hpp
- unittests/savanna_misc_tests.cpp
Resolves #869
I added a test attempting to reproduce the issue, but in order to activate the code in question, I would have to be able to update the blocks in fork_db to have validated = false, so they are not applied during the replay() call. I don't think it is worth adding an API in controller allowing to do this for this test.
**Important note**
I believe the issue was not present in `main` because of @heifner improvements to the block processing code, so the merge does not include any change to `controller.cpp`.
> [1.0.3 -> main] Restart with ctrl-c during replay of forkdb spams log

- libraries/chain/webassembly/runtimes/eos-vm-oc/LLVMJIT.cpp
> [1.0.3 -> main] fix building with LLVM 7, 8, and 9

- tests/TestHarness/Node.py
Resolves #848.
This updates the `verifyStartingBlockMessages` check in `Node.py` to check that we have only one `Starting block` in the log for any block number *unless*:
1. the block was restarted because it was exhausted, 
2. or the second `Starting block` is for a different block time than the first.
> [1.0.3 -> main] Test failure: distributed-transactions-if-test

- plugins/net_plugin/net_plugin.cpp
Small optimization of handling of errors for vote messages. Shortcut out of loop when connection is found.
Improve error message for invalid vote message.
Merges `release/1.0` into `main` including #913
> [1.0.3 -> main] Optimize handling of invalid vote message

- libraries/chain/block_state.cpp
- libraries/chain/controller.cpp
- libraries/chain/finality/qc.cpp
- libraries/chain/include/eosio/chain/block_state.hpp
- libraries/chain/include/eosio/chain/exceptions.hpp
- libraries/chain/include/eosio/chain/finality/qc.hpp
- unittests/block_state_tests.cpp
> Split verify_qc and add a new exception type invalid_qc

- libraries/chain/block_header_state.cpp
- libraries/chain/block_state.cpp
- libraries/chain/controller.cpp
- unittests/replay_block_invariants_tests.cpp
> [1.0.3] Improve validation

- tests/TestHarness/TransactionGeneratorsLauncher.py
- tests/trx_generator/trx_generator.cpp
Hopefully this will provide some information on why #425 is failing.
> Capture trx_generator output in tests

- .cicd/defaults.json
> [1.0.4 -> main] set cdt version used in CI to 4.1.x

- unittests/block_tests.cpp
Resolves https://github.com/AntelopeIO/spring/issues/1076
> Add a test for invalid QC block number

- plugins/producer_api_plugin/producer.swagger.yaml
Add documentation for new plugin producer method. Available for review on staging https://staging.docs.eosnetwork.com/apis/spring/latest/producer.api#operation/pause_at_block
Resolves #1087 
Related to PR #1056
> Update docs add pause_at_block

- libraries/chain/block_log.cpp
- tests/block_log.cpp
> [1.1.1 -> main] fix flat to pruned block log conversion

- plugins/net_plugin/net_plugin.cpp
Set a 1MB send/receive buffer for P2P similar to what we have for SHiP.
> P2P: 1MB send/receive buffer

- tests/nodeos_signal_throw_test.py
It is possible that an exception is handled and nodeos shuts down before it has the opportunity to reply to the http request that initiated the shutdown.
Resolves #1298
> [1.1.3] Test fix: Handle case where nodeos shutsdown before replying to http request

- tests/nodeos_signal_throw_test.py
It is possible that an exception is handled and nodeos shuts down before it has the opportunity to reply to the http request that initiated the shutdown.
Merges `release/1.1` into `main` including #1299 
Resolves #1298
> [1.1.3 -> main] Test fix: Handle case where nodeos shutsdown before replying to http request

- unittests/checktime_tests.cpp
Allow more time for block apply to start before sending interrupt to avoid sending the interrupt before the apply block starts.
Resolves #1262
> [1.1.4] Test fix: Allow more time for block apply to start before sending interrupt

- unittests/checktime_tests.cpp
Allow more time for block apply to start before sending interrupt to avoid sending the interrupt before the apply block starts.
Merges `release/1.1` into `main` including #1353 
Resolves #1262
> [1.1.4 -> main] Test fix: Allow more time for block apply to start before sending interrupt

- .cicd/defaults.json
- .github/workflows/build.yaml
Merges `release/1.2` into `main` including: #1462 & #1463 & #1465
> [1.2.0-rc1 -> main] Rename to vaultafoundation/system-contracts / Version bump to v1.1.5

- plugins/producer_plugin/producer_plugin.cpp
Add additional logging for aborted, forked, and expired trxs in the unapplied transaction queue. This additional logging should help debug test failures like #1471
Merges `release/1.2` into `main` including #1473
> [1.2.0-rc2 -> main] Additional logging of unapplied trxs

- .cicd/defaults.json
- .github/workflows/build.yaml
- .github/workflows/performance_harness_run.yaml
- docs/01_nodeos/03_plugins/chain_plugin/index.md
- docs/01_nodeos/03_plugins/http_plugin/index.md
- docs/01_nodeos/03_plugins/net_plugin/index.md
- docs/01_nodeos/03_plugins/producer_plugin/index.md
- docs/01_nodeos/03_plugins/resource_monitor_plugin/index.md
- docs/01_nodeos/03_plugins/state_history_plugin/index.md
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/name.hpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
- plugins/producer_plugin/producer_plugin.cpp
- programs/spring-util/actions/blocklog.cpp
- programs/spring-util/actions/blocklog.hpp
- tests/TestHarness/testUtils.py
- tests/block_log_util_test.py
- unittests/api_tests.cpp
- unittests/fork_db_tests.cpp
> [main -> 2.0] merge origin/main to release/2.0 (05/08/25) 

- .cicd/defaults.json
- .github/workflows/build.yaml
- .github/workflows/performance_harness_run.yaml
- docs/01_nodeos/03_plugins/chain_plugin/index.md
- docs/01_nodeos/03_plugins/http_plugin/index.md
- docs/01_nodeos/03_plugins/net_plugin/index.md
- docs/01_nodeos/03_plugins/producer_plugin/index.md
- docs/01_nodeos/03_plugins/resource_monitor_plugin/index.md
- docs/01_nodeos/03_plugins/state_history_plugin/index.md
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/name.hpp
- libraries/chain/webassembly/runtimes/eos-vm-oc/code_cache.cpp
- plugins/producer_plugin/producer_plugin.cpp
- programs/spring-util/actions/blocklog.cpp
- programs/spring-util/actions/blocklog.hpp
- tests/TestHarness/testUtils.py
- tests/block_log_util_test.py
- unittests/api_tests.cpp
- unittests/fork_db_tests.cpp
> [2.0 -> sync_call] SC: Merge release/2.0 to sync_call (5/8/25) 

- tests/block_log_util_test.py
> Failing test  block_log_util_if_test: simplify checks and add some extra debugging output.

- libraries/chain/controller.cpp
- plugins/net_plugin/net_plugin.cpp
- tutorials/bios-boot-tutorial/README.md
- tutorials/bios-boot-tutorial/bios-boot-tutorial.py
- tutorials/bios-boot-tutorial/test/tests.py
- unittests/blocks_log_replay_tests.cpp
One merge conflict, fixed by  e94e5545a7764a66bac8db7ef859a36f9ecc2fae
> [main -> 2.0.0-dev] Merge main 5/28/2025

- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/exceptions.hpp
- libraries/chain/include/eosio/chain/pending_snapshot.hpp
- libraries/chain/include/eosio/chain/snapshot_scheduler.hpp
- libraries/chain/snapshot_scheduler.cpp
- libraries/libfc/include/fc/exception/exception.hpp
- libraries/libfc/src/network/http/http_client.cpp
- libraries/libfc/test/CMakeLists.txt
- libraries/libfc/test/test_exception.cpp
- libraries/testing/tester.cpp
- plugins/http_plugin/include/eosio/http_plugin/macros.hpp
- plugins/net_plugin/net_plugin.cpp
- plugins/producer_api_plugin/producer_api_plugin.cpp
- plugins/producer_plugin/producer_plugin.cpp
- tests/chain_test_utils.hpp
- tests/nodeos_read_terminate_at_block_test.py
- tests/nodeos_snapshot_forked_test.py
- tests/test_snapshot_scheduler.cpp
- tutorials/bios-boot-tutorial/README.md
- tutorials/bios-boot-tutorial/bios-boot-tutorial.py
- tutorials/bios-boot-tutorial/test/tests.py
- unittests/api_tests.cpp
- unittests/blocks_log_replay_tests.cpp
- unittests/test_utils.hpp
- unittests/wasm_tests.cpp
> SC: Merge release/2.0.0-dev to sync call branch (5/28/2025) 

- docs/01_nodeos/03_plugins/trace_api_plugin/index.md
- plugins/trace_api_plugin/examples/abis/core.vaulta.abi
- plugins/trace_api_plugin/examples/abis/eosio.abi
- plugins/trace_api_plugin/examples/abis/eosio.msig.abi
- plugins/trace_api_plugin/examples/abis/eosio.token.abi
- plugins/trace_api_plugin/examples/abis/eosio.wrap.abi
Add `core.vaulta.abi` and update `eosio.*` abis in `trace_api_plugin` example abis.
Example output with:
```
--plugin eosio::trace_api_plugin --trace-rpc-abi eosio=../../../plugins/trace_api_plugin/examples/abis/eosio.abi --trace-rpc-abi eosio.token=../../../plugins/trace_api_plugin/examples/abis/eosio.token.abi --trace-rpc-abi core.vaulta=../../../plugins/trace_api_plugin/examples/abis/core.vaulta.abi
```
```
curl  http://127.0.0.1:8888/v1/trace_api/get_block -d '{"block_num": 439273660}' | jq  
...
{
"global_sequence": "363985764702",
"receiver": "eosiopowcoin",
"account": "eosio.token",
"action": "transfer",
"authorization": [
{
"account": "eosiopowcoin",
"permission": "active"
}
],
"data": "301d459c56ea3055502f459566aca461010000000000000004454f53000000000a526566756e6420454f53", …
```
> [1.2.0-rc3 -> main] TraceAPI: Add core.vaulta.abi and update eosio.* abis

- libraries/chain/abi_serializer.cpp
- libraries/chain/controller.cpp
- libraries/chain/include/eosio/chain/abi_serializer.hpp
- libraries/chain/include/eosio/chain/controller.hpp
> [2.0.0-dev] Remove deprecated functions.

- tests/auto_bp_gossip_peering_test.py
Cleanup test and improve reliability.
Resolves #1685
> [1.2.2] Test: Improve the reliability of gossip peer test

- tests/auto_bp_gossip_peering_test.py
Cleanup test and improve reliability.
Merges `release/1.2` into `main` including #1687 
Resolves #1685
> [1.2.2 -> main] Test: Improve the reliability of gossip peer test

- libraries/chain/include/eosio/chain/platform_timer.hpp
- libraries/chain/platform_timer_asio_fallback.cpp
- libraries/chain/platform_timer_kqueue.cpp
- libraries/chain/platform_timer_posix.cpp
> [1.2 -> main] protect against timer "rearm race": more timers approach with pointer tagging

- libraries/chain/include/eosio/chain/platform_timer.hpp
- libraries/chain/platform_timer_asio_fallback.cpp
- libraries/chain/platform_timer_kqueue.cpp
- libraries/chain/platform_timer_posix.cpp
- libraries/libfc/include/fc/io/raw.hpp
Clean merging.
For https://github.com/AntelopeIO/spring/pull/1832.
> [main -> 2.0] 8/21/2025 Merge main to release/2.0

- .cicd/platforms/asan.Dockerfile
- .cicd/platforms/ubsan.Dockerfile
Latest will hopefully have the best sanitizers
> update sanitizers to clang 21
